### ISSUE TITLE
omelasticsearch module

### ISSUE THREAD

**Issue by esazarain** [rsyslog/rsyslog#2818] opened 2018-07-04 12:08 UTC
### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

Hi
I'm Elham. I am going to create a log manager with rsyslog and elasticsearch.  I used of omelasticsearch module then defined a template for fetching IP from message.
In my template, message string was seprated base on space deliminator and the fieldnumber. The 6th field is my IP. the problem that i faced is that when date changed from "Jun 30 2018" to "Jul  1 2018", the sixth field changed to 7th field. you know i have 2 space in "Jul  1 2018" and it failed my result. I used of compressspace property but it didnt work.
please help me becouse im in force situation.

Thanks alot

**Comment by rgerhards** [comment] 2018-07-05 08:31
duplicate of #2817

**Closed by rgerhards** 2018-07-05 08:31 UTC
Labels: duplicate
