### ISSUE TITLE
rsyslog 8.2010.0: omkafka error at startup

### ISSUE THREAD

**Issue by newbie-rsyslog** [rsyslog/rsyslog#4465] opened 2020-11-12 10:37 UTC
### Expected behavior
Rsyslog should start

### Actual behavior
Rsyslog fails with error:
Starting system logger: rsyslogd: could not load module 'omkafka', errors: trying to load module /lib64/rsyslog/omkafka.so: /lib64/rsyslog/omkafka.so: undefined symbol: rd_kafka_flush [v8.2010.0 try https://www.rsyslog.com/e/2066 ]
rsyslogd: module name 'omkafka' is unknown [v8.2010.0 try https://www.rsyslog.com/e/2209 ]
rsyslogd: error during parsing file /etc/rsyslog.d/60-output-kafka.conf, on or before line 68: errors occured in file '/etc/rsyslog.d/60-output-kafka.conf' around line 68 [v8.2010.0 try https://www.rsyslog.com/e/2207 ]
I installed rysylog rpm packages.
It seems to be a packaging bug as installing librdkafka 0.11.5 fixes the issue (dependency installed is librdkafka 0.8.5) 

### Steps to reproduce the behavior
/etc/init.d/rsyslog start

### Environment
- rsyslog version: 8.2010.0
- platform: RedHat RHEL 6.6

**Comment by rgerhards** [comment] 2020-11-12 11:02
did you close this issue because their was a misunderstanding on your part? Aka we do not need to look into it?

**Comment by newbie-rsyslog** [comment] 2020-11-12 11:10
Actually I thought there was a misunderstanding but no, I encountered the problem again today so I reopen the issue, sorry

**Comment by bestlihj** [comment] 2021-01-05 07:18
I have the same problem
### Actual behavior
rsyslogd: version 8.2012.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: parameter "maxLinesAtOnce" not permited in inotify mode - ignored [v8.2012.0 try https://www.rsyslog.com/e/2222 ]
rsyslogd: could not load module 'omkafka', errors: trying to load module /usr/lib/rsyslog/omkafka.so: /usr/lib/rsyslog/omkafka.so: undefined symbol: rd_kafka_flush [v8.2012.0 try https://www.rsyslog.com/e/2066 ]
### Steps to reproduce the behavior
Install rsyslogd from ppa
sudo add-apt-repository ppa:adiscon/v8-stable
sudo apt-get update
sudo apt-get install rsyslog

rsyslogd -N 1

### Environment
os：Linux version 4.4.0-141-generic (buildd@lcy01-amd64-006) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4) ) 
packet_write_wait: Connection to 10.10.69.253 port 22: Broken pipe

# cat /proc/version
Linux version 4.4.0-141-generic (buildd@lcy01-amd64-006) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4) ) 
# ldd /usr/sbin/rsyslogd
	linux-vdso.so.1 =>  (0x00007ffc86dc9000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f7bd5700000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7bd54e2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7bd52de000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7bd50d6000)
	libestr.so.0 => /usr/lib/libestr.so.0 (0x00007f7bd4ed2000)
	libfastjson.so.4 => /usr/lib/libfastjson.so.4 (0x00007f7bd4cc7000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f7bd4ac2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7bd46fd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7bd5919000)

# ldd /usr/lib/rsyslog/omkafka.so
	linux-vdso.so.1 =>  (0x00007ffd584f1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007faf96f20000)
	/lib64/ld-linux-x86-64.so.2 (0x00007faf974f0000)

# nm -DC /usr/lib/rsyslog/omkafka.so | grep -i rd_kafka_flush
                 U rd_kafka_flush

# dpkg -l librdkafka1
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                     Version           Architecture      Description
+++-========================-=================-=================-=====================================================
ii  librdkafka1              0.8.3-1ubuntu2    amd64             library implementing the Apache Kafka protocol


# dpkg -l librdkafka-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                     Version           Architecture      Description
+++-========================-=================-=================-=====================================================
ii  librdkafka-dev           0.8.3-1ubuntu2    amd64             library implementing the Apache Kafka protocol (devel

**Comment by bestlihj** [comment] 2021-01-06 06:46
rsyslog-8.26.0 is ok

**Closed** 2021-01-18 11:00 UTC
