### ISSUE TITLE
rsyslog 8.24.0 SIGBUS on CentOS 7.4

### ISSUE THREAD

**Issue by ledgr** [rsyslog/rsyslog#1972] opened 2017-11-05 16:46 UTC
rsyslogd -v

```
rsyslogd 8.24.0, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64
```

Most relevant snippets (IMO) from `rsyslogd -dn`:

```
6402.793588364:main thread    : action 0 queue: params: type 1, enq-only 0, disk assisted 1, spoolDir '/var/lib/rsyslog', maxFileSz 1048576, maxQSize 1000, lqsize 0, pqsize 0, child 0, full delay 400, light delay 700, deq batch size 16, high wtrmrk 800, low wtrmrk 200, discardmrk 980, max wrkr 1, min msgs f. wrkr 1000


6402.793620387:main thread    : action 0 queue[DA]: starting queue
6402.793625338:main thread    : action 0 queue[DA]: .qi file name is '/var/lib/rsyslog/srvrfwd1.qi', len 28
6402.793628848:main thread    : action 0 queue[DA]: I am a child
6402.793637487:main thread    : file stream /var/lib/rsyslog/srvrfwd1.qi params: flush interval 0, async write 0
6402.793646776:main thread    : file '/var/lib/rsyslog/srvrfwd1.qi' opened as #3 with mode 384
6402.793653816:main thread    : strm 0x7f144b6d9100: opened file '/var/lib/rsyslog/srvrfwd1.qi' for READ as 3
6402.793661386:main thread    : strm 0x7f144b6d9100: file 3 read 547 bytes
6402.793675899:main thread    : file stream srvrfwd1 params: flush interval 0, async write 0
6402.793692296:main thread    : file stream srvrfwd1 params: flush interval 0, async write 0
6402.793703902:main thread    : file stream srvrfwd1 params: flush interval 0, async write 0
6402.793716949:main thread    : file '/var/lib/rsyslog/srvrfwd1.00000587' opened as #4 with mode 384
6402.793726476:main thread    : queue 'strm 0x7f144b6da520', file '/var/lib/rsyslog/srvrfwd1.00000587' opened for non-append write, but already contains 458089 bytes
6402.793732793:main thread    : strm 0x7f144b6da520: opened file '/var/lib/rsyslog/srvrfwd1.00000587' for WRITE as 4
6402.793737962:main thread    : strm 0x7f144b6da520: file 4 seek, pos 1150
6402.793747184:main thread    : file '/var/lib/rsyslog/srvrfwd1.00000086' opened as #17 with mode 384
6402.793755963:main thread    : strm 0x7f144b6db910: opened file '/var/lib/rsyslog/srvrfwd1.00000086' for READ as 17
6402.793762555:main thread    : strm 0x7f144b6db910: file 17 seek, pos 340553
6402.793770444:main thread    : file '/var/lib/rsyslog/srvrfwd1.00000086' opened as #18 with mode 384
6402.793778854:main thread    : strm 0x7f144b6dcba0: opened file '/var/lib/rsyslog/srvrfwd1.00000086' for READ as 18
6402.793785763:main thread    : strm 0x7f144b6dcba0: file 18 seek, pos 340553
6402.793792606:main thread    : strm 0x7f144b6d9100: file 3(/var/lib/rsyslog/srvrfwd1.qi) closing, bDeleteOnClose 0
6402.793803695:main thread    : action 0 queue[DA]: params: type 2, enq-only 0, disk assisted 0, spoolDir '/var/lib/rsyslog', maxFileSz 1048576, maxQSize 0, lqsize 431352, pqsize 431352, child 1, full delay -1, light delay -1, deq batch size 8, high wtrmrk 0, low wtrmrk 1, discardmrk 0, max wrkr 1, min msgs f. wrkr 0


6402.793962536:main thread    : action 1 queue: params: type 3, enq-only 0, disk assisted 0, spoolDir '/var/lib/rsyslog', maxFileSz 1048576, maxQSize 1000, lqsize 0, pqsize 0, child 0, full delay 970, light delay 700, deq batch size 16, high wtrmrk 800, low wtrmrk 200, discardmrk 980, max wrkr 1, min msgs f. wrkr 1000
6402.793991006:main thread    : action 2 queue: params: type 3, enq-only 0, disk assisted 0, spoolDir '/var/lib/rsyslog', maxFileSz 1048576, maxQSize 1000, lqsize 0, pqsize 0, child 0, full delay 970, light delay 700, deq batch size 16, high wtrmrk 800, low wtrmrk 200, discardmrk 980, max wrkr 1, min msgs f. wrkr 1000
6402.794016586:main thread    : action 3 queue: params: type 3, enq-only 0, disk assisted 0, spoolDir '/var/lib/rsyslog', maxFileSz 1048576, maxQSize 1000, lqsize 0, pqsize 0, child 0, full delay 970, light delay 700, deq batch size 16, high wtrmrk 800, low wtrmrk 200, discardmrk 980, max wrkr 1, min msgs f. wrkr 1000
6402.794045509:main thread    : action 4 queue: params: type 3, enq-only 0, disk assisted 0, spoolDir '/var/lib/rsyslog', maxFileSz 1048576, maxQSize 1000, lqsize 0, pqsize 0, child 0, full delay 970, light delay 700, deq batch size 16, high wtrmrk 800, low wtrmrk 200, discardmrk 980, max wrkr 1, min msgs f. wrkr 1000
6402.794072230:main thread    : action 5 queue: params: type 3, enq-only 0, disk assisted 0, spoolDir '/var/lib/rsyslog', maxFileSz 1048576, maxQSize 1000, lqsize 0, pqsize 0, child 0, full delay 970, light delay 700, deq batch size 16, high wtrmrk 800, low wtrmrk 200, discardmrk 980, max wrkr 1, min msgs f. wrkr 1000
6402.794097129:main thread    : action 6 queue: params: type 3, enq-only 0, disk assisted 0, spoolDir '/var/lib/rsyslog', maxFileSz 1048576, maxQSize 1000, lqsize 0, pqsize 0, child 0, full delay 970, light delay 700, deq batch size 16, high wtrmrk 800, low wtrmrk 200, discardmrk 980, max wrkr 1, min msgs f. wrkr 1000
6402.794151283:main thread    : main Q: params: type 0, enq-only 0, disk assisted 0, spoolDir '/var/lib/rsyslog', maxFileSz 1048576, maxQSize 100000, lqsize 0, pqsize 0, child 0, full delay 97000, light delay 70000, deq batch size 256, high wtrmrk 80000, low wtrmrk 20000, discardmrk 98000, max wrkr 2, min msgs f. wrkr 40000


6402.856719582:action 0 queue[DA]:Reg/w0: error -2031 deserializing property name, offset 618830, step 3
6402.857645762:action 0 queue[DA]:Reg/w0: error property name: 'json'
6402.857657951:action 0 queue[DA]:Reg/w0: error var type: '1'
6402.857665132:action 0 queue[DA]:Reg/w0: error len: '780'
6402.858134990:action 0 queue[DA]:Reg/w0: action 0 queue[DA]: error -2031 dequeueing element - ignoring, but strange things may happen
6402.858851692:action 0 queue[DA]:Reg/w0: objDeserialize error -2029 during header processing - trying to recover
6402.859348763:action 0 queue[DA]:Reg/w0: error -2031 deserializing property name, offset 622674, step 3
6402.859406149:action 0 queue[DA]:Reg/w0: error property name: 'pszRawMsg'
6402.859411768:action 0 queue[DA]:Reg/w0: error var type: '1'
6402.859417259:action 0 queue[DA]:Reg/w0: error len: '83'
6402.859949878:action 0 queue[DA]:Reg/w0: action 0 queue[DA]: error -2031 dequeueing element - ignoring, but strange things may happen
6402.860840615:action 0 queue[DA]:Reg/w0: objDeserialize error -2029 during header processing - trying to recover
6402.860970441:action 0 queue[DA]:Reg/w0: error -2059 deserializing property name, offset 626689, step 3
6402.861021925:action 0 queue[DA]:Reg/w0: error property name: 'tTIMESTAMP'
6402.861026839:action 0 queue[DA]:Reg/w0: error var type: '3'
6402.861031638:action 0 queue[DA]:Reg/w0: error len: '35'
6402.861556110:action 0 queue[DA]:Reg/w0: action 0 queue[DA]: error -2059 dequeueing element - ignoring, but strange things may happen
6402.861648150:action 0 queue[DA]:Reg/w0: objDeserialize error -2029 during header processing - trying to recover
6402.862278953:action 0 queue[DA]:Reg/w0: error -2031 deserializing property name, offset 630796, step 3
6402.862330317:action 0 queue[DA]:Reg/w0: error property name: 'pszTAG'
6402.862335254:action 0 queue[DA]:Reg/w0: error var type: '1'
6402.862339788:action 0 queue[DA]:Reg/w0: error len: '21'


6402.856719582:action 0 queue[DA]:Reg/w0: error -2031 deserializing property name, offset 618830, step 3
6402.856727019:imjournal.c    : main Q: qqueueAdd: entry added, size now log 92, phys 281 entries
6402.856733898:imjournal.c    : main Q: EnqueueMsg advised worker start
6402.856742174:action 0 queue[DA]:Reg/w0: strm 0x7f144b6dcba0: strmRead index 3845, max 4096, buf ': not enough free space in mail queue: 131072 bytes < 1.5*message size limit:
```

gdb /usr/sbin/rsyslogd
```
(gdb) set follow-fork-mode child
(gdb) catch signal SIGBUS
(gdb) run

Catchpoint 1 (signal SIGBUS), rsCStrDestruct (ppThis=ppThis@entry=0x7fffe80095f0) at stringbuf.c:216
216		free(pThis->pBuf);

(gdb) bt full
#0  rsCStrDestruct (ppThis=ppThis@entry=0x7fffe80095f0) at stringbuf.c:216
        pThis = 0x62c1812010b02
#1  0x000055555558a468 in varDestruct (ppThis=0x7fffee6bdbc0) at var.c:72
        pThis = 0x7fffe80095d0
#2  0x0000555555576314 in MsgDeserialize (pMsg=0x7fffe8010d90, pStrm=pStrm@entry=0x55555581fb80) at msg.c:1405
        myProp = 0x7fffee6bdc44
        propRcvFrom = 0x0
        propRcvFromIP = 0x0
        tokener = <optimized out>
        pVar = 0x7fffe80095d0
        iRet = RS_RET_INVALID_DELIMITER
#3  0x00005555555822a9 in objDeserializeWithMethods (ppObj=0x7fffee6bdcf0, pszTypeExpected=pszTypeExpected@entry=0x5555555bbfe6 "msg", lenTypeExpected=lenTypeExpected@entry=3, pStrm=0x55555581fb80, fFixup=fFixup@entry=0x0,
    pUsr=pUsr@entry=0x0, objConstruct=0x555555574100 <msgConstructForDeserializer>, objConstructFinalize=objConstructFinalize@entry=0x0, objDeserialize=0x5555555762b0 <MsgDeserialize>) at obj.c:915
        iRet = RS_RET_OK
        iRetLocal = <optimized out>
        pObj = 0x7fffe8010d90
        oVers = 1
        pstrID = 0x7fffe801c200
#4  0x000055555558c8b8 in qDeqDisk (pThis=<optimized out>, ppMsg=<optimized out>) at queue.c:988
        iRet = RS_RET_OK
#5  0x000055555558e741 in qqueueDeq (ppMsg=0x7fffee6bdcf0, pThis=0x55555581bd30) at queue.c:1115
        iRet = RS_RET_OK
#6  DequeueConsumableElements (pSkippedMsgs=<optimized out>, piRemainingQueueSize=<synthetic pointer>, pWti=<optimized out>, pThis=0x55555581bd30) at queue.c:1713
        rd_fd = <optimized out>
        rd_offs = <optimized out>
        wr_fd = <optimized out>
        wr_offs = <optimized out>
        localRet = <optimized out>
        iRet = RS_RET_OK
        nDequeued = 2
        nDiscarded = 0
        nDeleted = 0
        iQueueSize = 431122
        pMsg = 0x7fffe8004920
#7  DequeueConsumable (pThis=pThis@entry=0x55555581bd30, pWti=pWti@entry=0x55555581c280, pSkippedMsgs=pSkippedMsgs@entry=0x7fffee6bdd44) at queue.c:1767
        iRet = RS_RET_OK
        iQueueSize = 0
#8  0x000055555558ea92 in DequeueForConsumer (pSkippedMsgs=0x7fffee6bdd44, pWti=0x55555581c280, pThis=0x55555581bd30) at queue.c:1919
        iRet = RS_RET_OK
#9  ConsumerReg (pThis=0x55555581bd30, pWti=0x55555581c280) at queue.c:1975
        iCancelStateSave = 1
        bNeedReLock = 0
        skippedMsgs = 0
        iRet = RS_RET_OK
#10 0x000055555558b66e in wtiWorker (pThis=pThis@entry=0x55555581c280) at wti.c:365
        __clframe = {__cancel_routine = <optimized out>, __cancel_arg = 0x55555581c280, __do_it = 1, __cancel_type = <optimized out>}
        pWtp = 0x55555581c100
        pAction = <optimized out>
        bInactivityTOOccured = 0
        localRet = <optimized out>
        terminateRet = RS_RET_TERMINATE_WHEN_IDLE
        wrkrInfo = <optimized out>
        iCancelStateSave = 0
        i = <optimized out>
        j = <optimized out>
        k = <optimized out>
#11 0x000055555558a7dd in wtpWorker (arg=0x55555581c280) at wtp.c:410
        __clframe = {__cancel_routine = <optimized out>, __cancel_arg = 0x55555581c280, __do_it = 1, __cancel_type = <optimized out>}
        pThis = 0x55555581c100
        sigSet = {__val = {1048576, 0 <repeats 15 times>}}
        pszDbgHdr = <optimized out>
        thrdName = "rs:action 0 queue[DA]:R\000\000\000\000\000\000\000\000"
#12 0x00007ffff79b0e25 in start_thread (arg=0x7fffee6be700) at pthread_create.c:308
        __res = <optimized out>
        pd = 0x7fffee6be700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737193436928, -8867340970252891892, 1, 140737193437632, 140737193436928, 93824995148032, 8867372754048846092, 8867323132782119180}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0,
              0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
#13 0x00007ffff6aa934d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

cat /proc/`pidof rsyslogd`/limits
```
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             95559                95559                processes
Max open files            32768                32768                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       95559                95559                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```

/var/lib/rsyslog/srvrfwd1.qi contents
```
cat srvrfwd1.qi
<OPB:1:qqueue:1:
+iQueueSize:2:6:431352:
+tVars.disk.sizeOnDisk:2:9:525658231:
>End
.
<Obj:1:strm:1:
+iCurrFNum:2:3:587:
+pszFName:1:8:srvrfwd1:
+iMaxFiles:2:8:10000000:
+bDeleteOnClose:2:1:0:
+sType:2:1:1:
+tOperationsMode:2:1:2:
+tOpenMode:2:3:384:
+iCurrOffs:2:4:1150:
+inode:2:1:0:
+bPrevWasNL:2:1:0:
>End
.
<Obj:1:strm:1:
+iCurrFNum:2:2:86:
+pszFName:1:8:srvrfwd1:
+iMaxFiles:2:8:10000000:
+bDeleteOnClose:2:1:1:
+sType:2:1:1:
+tOperationsMode:2:1:1:
+tOpenMode:2:3:384:
+iCurrOffs:2:6:340553:
+inode:2:9:135634174:
+bPrevWasNL:2:1:0:
>End
.
```

/var/run/rsyslog contains 502 srvrfwd1.0000[0-9]+* files each containing from 944 to 1751 lines starting with `Obj:1:msg:1`. There is total of `432014` such lines. 

systemctl status rsyslog
```
  Process: 9974 ExecStart=/usr/sbin/rsyslogd -n $SYSLOGD_OPTIONS (code=killed, signal=BUS)
 Main PID: 9974 (code=killed, signal=BUS)
```

I suppose I will have to adjust my config to fix this error: `6402.856742174:action 0 queue[DA]:Reg/w0: strm 0x7f144b6dcba0: strmRead index 3845, max 4096, buf ': not enough free space in mail queue: 131072 bytes < 1.5*message size limit:`, but rsyslog should not just crash with `SIGBUS`.

Running this command did not fix the issue: `rsyslog-recover-qi.pl -w /var/lib/rsyslog/ -f srvrfwd1 -d 8 > srvrfwd1.qi`

Setting values as this also did not solve the issue:
```
$ActionQueueSize 10000000
$MainMsgQueueSize 10000000
```

I just had to remove files /var/lib/rsyslog/srvrfwd1.000* and that solved it.

**Comment by rgerhards** [comment] 2017-11-07 17:04
This looks like a duplicate of https://github.com/rsyslog/rsyslog/issues/1404, fixed in 8.25.0. Please try current version and report if the problem still exists. Thx.

**Closed by rgerhards** 2017-11-07 17:04 UTC
