### ISSUE TITLE
rsyslog imfile fails to detect log rotation

### ISSUE THREAD

**Issue by drdivano** [rsyslog/rsyslog#2659] opened 2018-04-22 05:56 UTC
### Expected behavior

Rsyslog imfile should detect log file rename and start reading from the new log file.

### Actual behavior

Rsyslog fails to detect input log rotation (rename operation) on most runs of my test.

### Environment
- rsyslog version: [e.g. 8.34.0 -- see rsyslogd -v]
- platform: Alpine 3.7  / Docker 18.03.0-ce

I created a docker image that runs the test and demonstrates the bug:
https://gist.github.com/drdivano/31b85271562b030783885763886ecb07

**Comment by rgerhards** [comment] 2018-05-02 09:50
thx for the bug report - unfortunately it's a busy time. We will look at this ASAP.

**Comment by Dieken** [comment] 2018-06-13 06:54
my config snippet:
```
input(Type="imfile"
      Tag="@@K8S_CLUSTER@@"
      File="@@DIRS@@/*.log"
      PersistStateInterval="1000"
      ReadMode="0"
      Ruleset="omrelp"
      AddMetaData="on"
      ReopenOnTruncate="on"
      TrimLineOverBytes="0"
      FreshStartTail="on")
```

**Comment by AlexClineBB** [comment] 2018-06-15 14:47
We may be hitting this as well. We launched new systems on May 4th, and May 5th rsyslog stopped collecting logs for them.

We've downgraded to 8.33.1 to resolve the issue temporarily.

**Comment by coreyappleby** [comment] 2018-06-16 01:09
Could this be related to #1605? If so setting the imfile mode to "polling" might fix it.

**Comment by Dieken** [comment] 2018-06-16 10:12
@coreyappleby  If I don't get it wrong, #1605 refers to log file truncation, same fd is reused, but according to my comment above, the log files were renamed and new file was created, Rsyslogd didn't pick the new file inode.

I have lost faith on the refactoring of imfile, will stick to old version although it stopping reading too time to time (but will resume later).

**Comment by matt-garman** [comment] 2018-06-19 19:34
Just wanted to add another "me too".  On CentOS 6.5, using rsyslog v8.35.0-2.el6 RPM from the [Adiscon repo](http://rpms.adiscon.com/).  Logrotate is v3.7.8-17.el6 (native CentOS 6.5 version).

The relevant part of my /etc/rsyslog.conf is very simple:
```
  module(load="imfile") # for tailing apache and subversion logs
  input(type="imfile" File="/var/log/httpd/*_log" Tag="apache:")
  input(type="imfile" File="/var/log/httpd/subversion.log" Tag="svnapache:")
  input(type="imfile" File="/var/log/svnserve/svn.log" Tag="svnserve:")
```
And /etc/logrotate.conf:
```
weekly
rotate 52
create
dateext
compress
include /etc/logrotate.d
/var/log/wtmp {
    monthly
    create 0664 root utmp
    minsize 1M
    rotate 1
}
/var/log/btmp {
    missingok
    monthly
    create 0600 root utmp
    rotate 1
}
```

And /etc/logrotate.d/httpd:
```
 /var/log/httpd/*log {
    missingok
    notifempty
    sharedscripts
    delaycompress
    postrotate
        /sbin/service httpd reload > /dev/null 2>/dev/null || true
        /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
    endscript
 }
```

I will switch to polling mode for now.

**Comment by rgerhards** [comment] 2018-06-19 19:42
@friedl can this be caused by missing our file, as logrotaze seems to still use it?

**Comment by friedl** [comment] 2018-06-22 08:19
If I am not mistaken, CentOS 6.5 should not be affected by the change about the pid file, because it does not use systemd for starting the service. Instead it uses the old init scripts. 

In fact, I just tried `rsyslog-8.35.0-2` on a CentOS 6 system and the file `/var/run/syslogd.pid` was present.

**Comment by nike38rus** [comment] 2018-06-27 10:41
Same here. We have a lot of Java applications, which rotate their logs via logging frameworks like Logback and Log4j. They use move&rename strategy on roll-over, just like Logrotate default behavior (nocopytruncate).
There is also such feeling that rsyslog doesn't delete stale StateFiles on IN_DELETE and/or IN_MOVED* signals, and in situations when inum is reusing by another file that should be read by imfile this behavior can cause lost messages because Rsyslog starts to read these files not from the beginning. Could someone please confirm or refute this?

Oracle Linux 7.5 + Rsyslog 8.35.0-2 from http://rpms.adiscon.com/v8-stable/epel-7/x86_64/

**Comment by eseres** [comment] 2018-07-03 13:52
We seem to be experiencing this very issue as well.

**Comment by rgerhards** [comment] 2018-07-03 13:53
could somebody post a debug log?

**Comment by nike38rus** [comment] 2018-07-06 02:17
@rgerhards Here https://gist.github.com/nike38rus/4057412e15d74cfe1ade7d1c7b86b76c

I've written tiny Java app that writes dummy log message every 5s through logging framework (Logback). Logback configured to rotate log every 1 minute and gzip it after that. That log added to imfile inputs.

At 7621.105902666 log was rotated

**Comment by rgerhards** [comment] 2018-07-06 07:05
thx for the log. It looks like the "reopenOnTruncate" option is not set: https://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html#reopenontruncate It is required to make rsyslog try to detect cases where a file is truncted. It is off by default because truncate leads to some data loss (the busier the system, the more). Can you set this option and re-try? If it still does not work, another debug log would be appreciated.

**Comment by rgerhards** [comment] 2018-07-06 07:06
@nike38rus mmh... reading your previous comment it looks like this is not the case. Could you provide me a test Java application plus some instructions on how to run it? Possibly it would be good to have something like this in the testbench (but my Java is weak ;-)).

**Comment by rgerhards** [comment] 2018-07-06 07:16
looking once more in-depth at the debug log, it looks a bit like a race where the file detection may not work properly when the file is deleted and very quickly recreated (a very valid case!). I am not yet sure this really is the issue, but it smells a bit into that direction. In theory, imfile should detect that as it checks the inode number. Well.. bottom line... we need to see if we need additional testbench tests.

**Comment by nike38rus** [comment] 2018-07-06 09:29
@rgerhards download archive from https://github.com/nike38rus/testlog/archive/master.zip, configure rotation policy by editing the logback.xml file (log file path, roll-over frequency, gzipping), and then execute run.sh with bash

**Comment by nike38rus** [comment] 2018-07-06 09:43
@rgerhards As you've noticed earlier, there is no file truncation on roll-over. Here's example. 
1. There is log file with inum X
1. On roll-over it is renamed. It has the same inum X
1. New log file is created with inum Y
1. In my case there is one more step - compression of rotated log file. As result of compression I got new file with inum Z, and rolled-over log with inum X is being deleted

There is situation when there isn't so many log messages produced by application and new log file is created some time after rotation. And if the rolled-over log file isn't so big, compression is completed before new log file is created. And this is started to look like this:
1. Log file with inum X
1. Renamed on roll-over, still inum X
1. Compression, inum Y, previous log with inum X is deleted
1. New log file with inum X (due to inode reusage) and old filesystem path

There could be 2 potential problems within this situation:
1. Rsyslog must reopen file and drop file offset to 0 to prevent data loss.  Otherwise Rsyslog will wait until new log file reaches offset of previous log file. Even after full daemon restart, because offset is kept in StateFile
1. If file inum was changed, Rsyslog must remove previous StateFile because it contains inum in StateFile name. Inum reusage can occur after some time (days,weeks...), and Rsyslog hypothetically can read rotated log file from offset stored in stale StateFile, and it leads to data loss just like in previous problem.

I wonder how Rsyslog handles such cases. Could you take a look at this please?

**Comment by rgerhards** [comment] 2018-07-09 13:03
just as a side-note: I have found out that when you run rsyslog inside a docker container and use AUFS inotify does not work correctly. There are quite some bug reports regarding that on the Internet, for example here: https://github.com/libuv/libuv/issues/1201

This problems happens e.g. with an Ubuntu docker host at 16.04, but works fine at 18.04.

I have been able to reproduce that problem. I have also seen some reports that the problem also does occur with volumes, but have not been able to experience that myself.

This may not be the root cause of this issue here (that I am still looking at), but it appears to be at least related.

**Comment by eseres** [comment] 2018-07-09 20:06
We are not running rsyslog in Docker and yet we experience this issue. Our env is Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-49-generic x86_64).

**Comment by billputer** [comment] 2018-07-19 18:17
We're seeing the same behavior starting around the same time when we upgraded to the rsyslog 8.35.0-0adiscon3trusty1 Ubuntu package.

**Environment**

* Ubuntu 14.04.5 LTS (Trusty)
* Package rsyslog 8.36.0-0adiscon2trusty1
* Package logrotate 3.8.7-1ubuntu1.2

**Logrotate config**
```
/home/rails/apps/liquidplanner_web/shared/log/production.json {
  daily
  rotate 7
  dateext
  missingok
  notifempty
  compress
  delaycompress

  copytruncate

  sharedscripts
  postrotate
    service rsyslog restart >/dev/null 2>&1
  endscript
}
```

The offset in the statefile is almost twice the size of our current logfile, so imfile is not picking up the most recent log entries. Previously the `service rsyslog restart` would reset this.
```
$ wc -c /home/rails/apps/liquidplanner_web/shared/log/production.json
111679997 /home/rails/apps/liquidplanner_web/shared/log/production.json

$ sudo ack /production.json /var/spool/rsyslog/
/var/spool/rsyslog/imfile-state:536165
1:{ "filename": "\/home\/rails\/apps\/liquidplanner_web\/shared\/log\/production.json", "prev_was_nl": 0, "curr_offs": 273561992, "strt_offs": 273561992 }
```

I'd love to downgrade to the most recent working version (8.34.0-0adiscon3trusty1), but unfortunately the adiscon/v8-stable PPA doesn't keep the old versions. Does anyone have a recommendation for downgrading that doesn't involve the experimental Docker images or building my own package?

**Comment by nike38rus** [comment] 2018-08-31 08:28
Any update on this?

**Comment by rgerhards** [comment] 2018-09-24 16:29
I assume this is fixed by https://github.com/rsyslog/rsyslog/pull/3052 - if not, please let us know so that we can dig further.

**Comment by rgerhards** [comment] 2018-09-24 16:37
sorry, I mixed issues up. This one is still being worked on by me.

**Comment by rgerhards** [comment] 2018-09-27 16:54
We assume this is solved by https://github.com/rsyslog/rsyslog/pull/3051 - if not please post your results (but only within the next month, else create a new issue pls).

**Closed by rgerhards** 2018-09-27 16:54 UTC
Labels: bug, imfile

**Comment by gianlucaceci** [comment] 2019-06-27 11:36
the problem is into imfile when restart tomcat rsyslog don't read imfile anche stoped process. For solution is  search imfile, delete and restart rsyslog

**Comment by drdivano** [comment] 2019-06-27 18:40
I just tried my test with rsyslog 8.1904.0 (Alpine 3.10). It looks like the problem is fixed.
