### ISSUE TITLE
testbench: libfaketime regression

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#992] opened 2016-04-26 10:47 UTC
@Whissi #965 seems to misdetect libfaketime almost everywhere, resulting in parts of the testbench not being executed. A sample can be found here:

http://build.rsyslog.com:8010/builders/rsyslog%20fedora23x64%20rsyslog/builds/161/steps/shell_3/logs/test-suite.log

I manually verified that libfaketime is installed on that machine.

I unfortunately did not notice this earlier.

**Comment by Whissi** [comment] 2016-04-26 11:19
How do you installed *libfaketime* on these systems? We are relying on `LD_LIBRARY_PATH`...

**Comment by rgerhards** [comment] 2016-04-26 11:27
Via the package Manager without anything special, e.g.

sudo dnf install libfaketime

Sent from phone, thus brief.
Am 26.04.2016 13:19 schrieb "Thomas D." <notifications@github.com>:

**Comment by Whissi** [comment] 2016-04-26 11:43
Looks like Fedora don't install the *libfaketime.so* symlink. :(

Not sure what we should do here. Placing all known versions in `LD_PRELOAD`? For *libfaketime* this could work (there's just one) however this isn't future proofed.

I am wondering if we can detect the library via autotools so we can set a variable.

Finally we could add a `configure` option so that the user can specify..

Mhh..

**Comment by Whissi** [comment] 2016-04-26 11:54
I think I'll prepare a hack using something like `find /usr/lib/ -name 'libfaketime.so*' -type f | sort -r | head -n 1`

**Comment by rgerhards** [comment] 2016-04-26 11:57
Problem is also in Ubuntu, via

sudo apt-get install faketime

Sent from phone, thus brief.
Am 26.04.2016 13:43 schrieb "Thomas D." <notifications@github.com>:

**Comment by Whissi** [comment] 2016-04-26 12:55
The better way seems to parse `ldconfig -p` output however it looks like we can only use `find` at the moment: On Debian Jessie *libfaketime.so.1* is in `/usr/lib/x86_64-linux-gnu/faketime` and Debian doesn't create a symlink from `/usr/lib/x86_64-linux-gnu/` to that file nor adds the folder to *ld.so.conf*.

@mbiebl: BTW, isn't that a Debian packaging bug of the faketime package? And do you have a better idea to find the value for `LD_PRELOAD` or do you agree that using `find` is acceptable?

**Comment by mbiebl** [comment] 2016-04-26 13:22
Using find sounds brittle. Maybe the best/most robust way to fix this is to add a command line switch to the faketime binary which tells us, where the library is installed
faketime --env or something like that.

**Comment by Whissi** [comment] 2016-04-26 13:34
I don't think this will work:

- *faketime* binary don't link to *libfaketime.so.1*. That means upstream would have to add something completely new to *faketime* to search for its own library. But how should that work? You could put your libs wherever you want to, thank's to ld.so.conf. Well, the package could provide a *pkg-config* file, however package maintainer could make sure they register the program with ldconfig when they install it into a sub directory.

- If we decide to go with an upstream solution, it will take years for Debian, Fedora... to pick up the new version. So how is your plan to fix this for Wheezy, Jessie...?

For me it is actual a problem with packaging. If the package maintainers agree that's something which could be fixed in Wheezy and Jessie and we wouldn't have to wait for a new version to get picked up.

For the records, the original problem why we moved from using *faketime* binary to `LD_PRELOAD` was issue #963.

**Comment by mbiebl** [comment] 2016-04-26 13:41
oh, the faketime binary does know very well where it's libfaketime binary is. See
https://github.com/wolfcw/libfaketime/blob/master/src/faketime.c#L295 ff

**Comment by mbiebl** [comment] 2016-04-26 13:46
since point2 of your list only happens with libfaketime from git master, how would that be an issue for wheezy/jessie?
So if upstream has changed the behaviour of libfaketime, adding a command line switch to faketime at the same time sounds like the ideal solution to me, so you can use something like this:

LD_PRELOAD=$(faketime --env) $more argument $command

**Comment by mbiebl** [comment] 2016-04-26 13:55
Let's say upstream adds such a switch, then you could do

# if the binary doesn't know this command line switch it will return 1
if faketime --env > /dev/null 2>&1 ; then
   LD_PRELOAD=$(faketime --env) ...
else
   # old version, use faketime binary 
   faketime ...
fi

Pretty clean and simple imho

**Comment by Whissi** [comment] 2016-04-26 14:00
Before I answer your new findings, could you please tell me if you agree with me that the *faketime* package in Debian/Fedora... is broken because these packages don't register *libfaketime.so*?

We wouldn't have this problem if the library would be properly registered.

**Comment by mbiebl** [comment] 2016-04-26 14:01
No, I don't think the package is broken. It's not like libfaketime is a typical system library.

**Comment by mbiebl** [comment] 2016-04-26 14:09
One could argue, that if upstream wants users to be able to use
LD_PRELOAD=libfaketime.so, then upstream should switch to an unversioned .so and install a ld.so.conf.d snippet. That's an upstream decision though. Not a downstream/packaging issue.

**Comment by Whissi** [comment] 2016-04-26 14:46
OK, I agree with your last comment. I'll bring this to libfaketime's attention. Maybe they just forgot about providing an unversioned library symlink...

However a changed Makefile, implementing *"--env"* or a switch which will restore previous behavior [like upstream suggested](https://github.com/wolfcw/libfaketime/issues/89#issuecomment-211591316) won't appear version soon.

In the meantime I would prefer keeping the `LD_PRELOAD` solution but use `find` to find the library. Otherwise we would have two ways running the tests which could add new problems in theory (remember when *util-linux* introduced new parameters and changed default behavior).

**Comment by mbiebl** [comment] 2016-04-26 14:54
Why are you building libfaketime from Git master? Just curious.

**Comment by Whissi** [comment] 2016-04-26 15:01
Well, the problem was spotted in a tinderbox (kind of CI) I am running for rsyslog to notice upcoming problems in advance (the tinderbox is running cutting edge versions)... this was turned into a bug for rsyslog after upstream confirmed that they want to keep this changed behavior.

**Closed** 2016-05-06 08:43 UTC
Labels: bug, testbench
