### ISSUE TITLE
compressed dynafile output corruption

### ISSUE THREAD

**Issue by davidelang** [rsyslog/rsyslog#933] opened 2016-03-31 01:22 UTC
I have the template

$template perserverjson,"/var/log/servers/%$year%/%$month%/%$day%/%hostname:::lowercase%/%hostname:::lowercase%.%$year%%$month%%$day%.%$hour%-%$qhour%.json.gz"

and the action:

action(type="omfile" template="json" dynafile="perserverjson" dynafilecachesize="1200" ziplevel="9" flushinterval="60" name="perserverjson" ioBufferSize="512k" )

but if I go into this directory and try to access the zip files, I get errors.

 zgrep -c ' ' _.17_json.gz

gzip: las1prsvc001.20160330.17-00.json.gz: invalid compressed data--format violated
las1prsvc001.20160330.17-00.json.gz:74

gzip: las1prsvc001.20160330.17-01.json.gz: invalid compressed data--format violated
las1prsvc001.20160330.17-01.json.gz:0

gzip: las1prsvc001.20160330.17-02.json.gz: invalid compressed data--format violated
las1prsvc001.20160330.17-02.json.gz:0

gzip: las1prsvc001.20160330.17-03.json.gz: invalid compressed data--format violated
las1prsvc001.20160330.17-03.json.gz:0

 ls -l _.17_json.gz
-rw-r--r-- 1 root root 24442 Mar 30 17:14 las1prsvc001.20160330.17-00.json.gz
-rw-r--r-- 1 root root 27403 Mar 30 17:30 las1prsvc001.20160330.17-01.json.gz
-rw-r--r-- 1 root root 32554 Mar 30 17:45 las1prsvc001.20160330.17-02.json.gz
-rw-r--r-- 1 root root 32656 Mar 30 18:00 las1prsvc001.20160330.17-03.json.gz

**Comment by davidelang** [comment] 2016-03-31 01:24
This is with 8.18 pre git tree as of 2016-03-30, but it's not a new error, I've been getting some erros with these files for many versions.

**Comment by rgerhards** [comment] 2016-03-31 07:59
Just to make sure: you cannot access currently open files. Might this be
the Problem?

Sent from phone, thus brief.
Am 31.03.2016 03:24 schrieb "davidelang" <notifications@github.com>:

**Comment by davidelang** [comment] 2016-03-31 14:17
no, it happens with older files as well. Things many HUPs old.

David Lang

**Comment by Omniflux** [comment] 2016-10-11 18:34
I see this too. My logrotate issues "invoke-rc.d rsyslog rotate" which runs "start-stop-daemon --stop --signal HUP --quiet --pidfile $PIDFILE --exec $DAEMON" at 6:25am.

All compressed log files are corrupt and end at this time and data is lost until a new log file is created and HUP issued, OR dynafile template causes a new file to be created.

Version: (Debian) 8.16.0-1~bpo8+1

template (name="DailyPerHostLogs"
          type="list") {
  constant (value="/var/log/remote/")
  property (name="hostname" securepath="replace")
  constant (value="/")
  property (name="$year")
  constant (value="/")
  property (name="$month")
  constant (value="/")
  property (name="hostname" securepath="replace")
  constant (value=".")
  property (name="$now")
  constant (value=".log.gz")
}

       action (type="omfile"
                dynafile="DailyPerHostLogs"
                dynaFileCacheSize="100"
                zipLevel="9"
                flushOnTXEnd="off"
                ioBufferSize="128k"
                asyncWriting="on")

**Comment by zhxiaom5** [comment] 2016-12-10 14:51
this also happend to me,after i restart the rsyslogd,i zcat the gzip file ,same error appeared. it seems the omfile not properly handle the gzip file,when rsyslog receive signal

**Comment by Omniflux** [comment] 2017-07-05 01:19
Still occurs with Debian version 8.24.0-1.

Is there any more information I can give to help resolve this?

**Comment by kortemik** [comment] 2017-08-21 13:27
+1 i have experienced this bug as well

**Comment by AnswerIsCat** [comment] 2017-08-21 13:45
```template (name="DailyPerHostLogs" type="list") {
         constant (value="/var/log/remote/")
         property (name="hostname" securepath="replace")
         constant (value="/")
         property (name="$year")
         constant (value="/")
         property (name="$month")
         constant (value="/")
         property (name="hostname" securepath="replace")
         constant (value=".")
         property (name="$now")
         constant (value=".log.gz")
}

action (type="omfile"
       dynafile="DailyPerHostLogs"
       dynaFileCacheSize="100"
       zipLevel="9"
       flushOnTXEnd="off"
       ioBufferSize="128k"
       asyncWriting="on"
)

action (type="omfile"
       dynafile="DailyPerHostLogs"
       dynaFileCacheSize="100"
       zipLevel="9"
       flushOnTXEnd="off"
       ioBufferSize="128k"
       asyncWriting="on"
)

input
(
        type="imfile"
        File="/tmp/test_omfile.log"
        Tag="test_omfile"
        Severity="info"
        Facility="local0"
        PersistStateInterval="1"
)```

Simply having two omfile directives that write to same file will break it. 

```echo "Hello" >> /tmp/test_omfile.log```

```# zcat test.domain.tld/2017/08/test.domain.tld.2017-08-21.log.gz

gzip: test.domain.tld/2017/08/test.domain.tld.2017-08-21.log.gz: invalid compressed data--format violated```

**Comment by liveder** [comment] 2019-05-14 10:24
Since it's impossible to append GZ file after receiving HUP signal there is an option to solve this issue with other way.
If we will append to DYNFILE template additional variable something like %RSYSLOG_PROCID%(not implemented) or %RSYSLOG_STARTTIME%(not implemented) then it will be possible to split files into several each time rsyslog restarts. So GZ file won't be corrupted.

**Comment by ondrejkopka** [comment] 2019-06-12 07:16
+1 exactly same issue here :(

**Comment by liveder** [comment] 2019-06-12 09:06
there is a workaround using veryRobustZip.
it will provide some extra overhead but it works great

**Comment by rgerhards** [comment] 2019-06-12 11:13
I revisited this issue, and I am still unable to reproduce. @ondrejkopka could you provide a debug log of a session where this problem occurs?

**Comment by rgerhards** [comment] 2019-07-01 16:38
The root cause of this problem was most probably fixed by https://github.com/rsyslog/rsyslog/commit/62fbef7f72170ebc2211c79f1e1bf989dfcf8e9f. Unfortunately, that commit introduced a regression, which has been fixed by PR https://github.com/rsyslog/rsyslog/pull/3715.

The whole set of patches will be part of 8.1907.0.

**Comment by rgerhards** [comment] 2019-07-05 09:05
closing for now - pls let us know if you see the issue with 8.1907 or later.

**Closed** 2019-07-05 09:05 UTC
Labels: potential bug
