### ISSUE TITLE
Segfault with rsyslog 8.23.0 on RHEL 7.2

### ISSUE THREAD

**Issue by B4yM4x** [rsyslog/rsyslog#1332] opened 2016-12-15 15:30 UTC
Hi all,
I am experiencing a segmentation fault when I start rsyslog on all my RHEL 7.2 machines. The issue appears even if I use the default /etc/rsyslog.conf file. 

Attached the debug file and the output from gdb.

Thank you
[rsyslog_debug.txt](https://github.com/rsyslog/rsyslog/files/655023/rsyslog_debug.txt)
[rsyslog_gdb.txt](https://github.com/rsyslog/rsyslog/files/655024/rsyslog_gdb.txt)

**Comment by mostolog** [comment] 2016-12-19 14:29
It could be great if you can paste your configuration and some log events to reproduce this issue. Maybe it's just a configuration issue.

**Comment by B4yM4x** [comment] 2016-12-19 14:42
The error appears even with the default rsyslog.conf file. Basically I install the latest version of rsyslog via yum, then restart the service and I get immediately the segmentation fault. The only configuration that probably is not the default one is with two files in the rsyslog.d folder:

21-cloudinit.conf

`# Log cloudinit generated log messages to file`
`:programname, isequal, "cloud-init" /var/log/cloud-init.log`
`# comment out the following line to allow CLOUDINIT messages through.`
`# Doing so means you'll also get CLOUDINIT messages in /var/log/syslog`
`& ~`

and listen.conf
`$SystemLogSocketName /run/systemd/journal/syslog`

**Comment by mostolog** [comment] 2016-12-20 12:26
Could you just comment one of these, trying to narrow where the issue is?
I'm not used to legacy syntax, neither journal so probably other people could help more with this.

**Comment by B4yM4x** [comment] 2016-12-20 15:47
Moved into another folder both of them, once at a time, restarted rsyslog every time, and then both all together, but still get this segmentation fault.

**Comment by rgerhards** [comment] 2016-12-20 16:19
This is fixed in current master and will be released with 8.24, from
current master ChangeLog:

- bugfix imuxsock: segfault non shutdown when $OmitLocalLogging is on
  Imuxsock tries to close socket on index 0 which ends with segfault.
  Thanks to Tomas Sykora for the patch.

Rainer

2016-12-20 16:47 GMT+01:00 B4yM4x <notifications@github.com>:

**Closed** 2016-12-20 16:19 UTC
Labels: bug

**Comment by B4yM4x** [comment] 2016-12-20 16:48
That's great, thanks. Would you have any timeline for 8.24?

**Comment by rgerhards** [comment] 2016-12-20 16:49
Jan, 10th 2017

Rainer

2016-12-20 17:48 GMT+01:00 B4yM4x <notifications@github.com>:

**Comment by B4yM4x** [comment] 2016-12-20 16:51
That's great, thank you very much
