### ISSUE TITLE
imfile in inotify mode never stops monitoring moved files

### ISSUE THREAD

**Issue by kkoppel** [rsyslog/rsyslog#324] opened 2015-05-06 14:08 UTC
I'm using imfile in inotify mode to monitor a directory with many log files being regularly created and then moved out of the directory some time later. After a while imfile stops monitoring new files, because I believe it runs into the fs.inotify.max_user_watches limit, which on my servers is 8192 by default.

I get this in rsyslogd debug log when it happens:
6803.683077833:imfile.c       : DDDD: imfile event notification: rd 48[0], wd (1, mask 00000100, cookie 0000, len 32)
6803.683079397:imfile.c       : file was CREATED: some.log
6803.683081618:imfile.c       : DDDD: imfile: wd 1 got file (nil), dir 0
6803.683083071:imfile.c       : DDDD: handle dir event for /logs
6803.683084680:imfile.c       : DDDD: imfile: dirs.currMaxfiles 8168
6803.683086321:imfile.c       : DDDD: imfile: TABLE 0x7f63e40020a8 CONTENTS, 0->0x7f63e4003b50:'another.log'
... (8000+ lines with other log files)
6803.696175387:imfile.c       : DDDD: imfile: TABLE 0x7f63e40020a8 CONTENTS, 8167->0x7f63daa8eb80:'another.log'
6803.696397593:imfile.c       : DDDD: file 'some.log', found:4799
6803.696400183:imfile.c       : DDDD: file 'some.log' associated with dir '/logs'
6803.696405370:imfile.c       : ratelimit:imfile[/logs/some.log]:new ratelimiter:bReduceRepeatMsgs 0
6803.696412032:imfile.c       : imfile: could not create file table entry for '/logs/some.log' - not processing it now: No space left on device

So, it seems that imfile is not handling the IN_MOVE* events?

**Comment by merginator** [comment] 2015-06-02 23:17
https://github.com/rsyslog/rsyslog/pull/388 should fix this issue.

**Comment by hakman** [comment] 2015-06-05 04:48
I think we hit this issue also and got fixed, by accident, when we started compressing old logs.

**Comment by kkoppel** [comment] 2015-06-05 10:26
In your case the original log file probably gets deleted after compressing and that inotify event is already being handled properly.

That's not really an option for me. I need to move the files away before doing anything else with them. So, I need rsyslog to handle the respective inotify event.

**Comment by hakman** [comment] 2015-06-05 11:08
I am not sure though if #388 got merged before it was closed.

**Comment by merginator** [comment] 2015-06-05 19:51
I retracted (closed) my pull request for a couple reasons:

1) I think there's a better way to handle moves.  I didn't realize that IN_MOVED_FROM events would be created on the directory watches in addition to IN_MOVE_SELF notifications on the file watches.  Dealing with moves using the directory watches is cleaner, so my next patch will deal with that.

2) There's a bug in file deletion that needs to be fixed first before I add this functionality: https://github.com/rsyslog/rsyslog/issues/392.

**Comment by otisg** [comment] 2015-06-15 13:57
I think @rgerhards may want to know which rsyslog version you guys are using...

**Comment by kkoppel** [comment] 2015-06-15 21:16
I'm currently running v8.10.0 and still experiencing this problem.

**Comment by vlinevich** [comment] 2015-06-19 16:26
I'm on 8.8 and I still have this issue. 
I've switched to polling mode for now.

**Comment by rparkhunovsky** [comment] 2015-07-15 14:19
still reproducible with 8.11!

**Closed** 2015-07-28 08:48 UTC

**Comment by hakman** [comment] 2015-08-24 07:32
I don't want to be the one that brings bad news, but I don't think this works ok for me.
I still see files moved files kept open by rsyslog (Ubuntu 14.04, files rotated by logrotate):
```
> sudo lsof | grep '(deleted)' | grep upstart
rsyslogd  2386      syslog 12r REG 202,1 31583 269359 /var/log/upstart/consumer.log.1 (deleted)
in:imuxso 2386 2388 syslog 12r REG 202,1 31583 269359 /var/log/upstart/consumer.log.1 (deleted)
in:imklog 2386 2389 syslog 12r REG 202,1 31583 269359 /var/log/upstart/consumer.log.1 (deleted)
in:imfile 2386 2390 syslog 12r REG 202,1 31583 269359 /var/log/upstart/consumer.log.1 (deleted)
rs:main   2386 2391 syslog 12r REG 202,1 31583 269359 /var/log/upstart/consumer.log.1 (deleted)
rs:action 2386 2392 syslog 12r REG 202,1 31583 269359 /var/log/upstart/consumer.log.1 (deleted)
...
```

**Comment by kkoppel** [comment] 2015-08-24 08:55
I've been running rsyslogd v8.12.0 since August 11th and have had no more problems like the original reported issue. Thanks @alorbach !

@hakman, I don't see rsyslogd keeping any moved files open on my servers.

**Comment by hakman** [comment] 2015-08-24 09:02
OK, I will do a little debugging later today and get back with feedback. Thanks!

**Comment by ymattw** [comment] 2015-08-24 09:10
Looks like the one I reported in #488?

**Comment by lea4n** [comment] 2015-12-28 02:37
it looks like v8.15 will hang also
