### ISSUE TITLE
Build omczmq module rpm for RH/CentOS

### ISSUE THREAD

**Issue by jay7x** [rsyslog/rsyslog#1556] opened 2017-05-12 03:56 UTC
As far as I see there is no `omczmq` module rpm is supplied. Is it possible to have it in http://rpms.adiscon.com repo as well?

Actually If you provide rpm spec which is used to build those packages I'll try to add `omczmq` there.

**Comment by rgerhards** [comment] 2017-05-12 06:16
I think the problem is that there do not exist packages for the dependencies. @taotetek may comment on this. Please also note that this is an issue for https://github.com/rsyslog/rsyslog-pkg-rhel-centos, so I am closing this one here.

**Closed by rgerhards** 2017-05-12 06:16 UTC

**Comment by taotetek** [comment] 2017-05-15 11:04
I would love to have both debs and rpms for the zeromq input and output
modules. The reason I haven't pursued this is that up until very recently
the zeromq / czmq libraries either weren't packaged for various distros, or
the versions included if included were rather old.

At work, I custom build debs for various ubuntu versions for our internal
builds.

I'd be happy to look more into this with other people who are interested in
this being packaged - at the very least I'm glad  to answer questions about
dependencies / versions etc.

Cheers,
Brian

**Comment by jay7x** [comment] 2017-05-15 11:10
I'll try to build this module later on CentOS 7. Thank to Rainer now I know where to look for specs :)

**Comment by itkovian** [comment] 2017-06-07 12:35
Hi. Any progress here?
