### ISSUE TITLE
all-json/jsonmesg seem to trip the template on non-ASCII characters

### ISSUE THREAD

**Issue by radu-gheorghe** [rsyslog/rsyslog#1094] opened 2016-07-18 02:21 UTC
Basically, it seems like whenever it encounters a non-ASCII character (I've tested with `¥`, which I believe is a valid UTF8 char), the template just gives up and prints `\u00` and nothing after that. This breaks the JSON, of course, besides losing information.

Here's a config to reproduce:
```
module(load="imuxsock")
module(load="mmnormalize")
action(type="mmnormalize" rulebase="/etc/rulebase")
template(name="allthejson" type="list") { property(name="jsonmesg") constant(value="\n")}
action(type="omfile" file="/var/log/test" template="allthejson")
```

Where `/etc/rulebase` can be as simple as:
```
rule=:%blob:rest%
```

It doesn't matter if it parses the message or not. Then, to trigger the bug, you'd do, for example:
```
logger "af ¥ dsft"
```

At which point in `/var/log/test` you'll see:
```
{ "msg": " af \u00
```

The same goes with `$!all-json`. However, if I refer to the `blob` property directly in the template, it works. This can be a workaround for those who know upfront what fields to expect. Otherwise, it might work with a [foreach loop](http://www.rsyslog.com/doc/v8-stable/rainerscript/control_structures.html#foreach) to build the JSON in a local variable, but I haven't tried.

To reproduce, I've used rsyslog 8.19 on Ubuntu 14.04, installed from the packages.

**Comment by rgerhards** [comment] 2016-07-18 05:29
This is almost 100% sure the result of this bug https://github.com/rsyslog/libfastjson/issues/107

It is fixed in libfastjson 0.99.3. If upgrading doesn't solve your issue, please re-open this issue here.

**Closed by rgerhards** 2016-07-18 05:29 UTC

**Comment by radu-gheorghe** [comment] 2016-07-19 12:59
Thanks, Rainer! I'm guessing libfastjson 0.99.3 will be in the repos along with the 8.20 packages, when they'll be ready?

**Comment by rgerhards** [comment] 2016-07-19 13:49
2016-07-19 14:59 GMT+02:00 Radu Gheorghe <notifications@github.com>:

> Thanks, Rainer! I'm guessing libfastjson 0.99.3 will be in the repos along
> with the 8.20 packages, when they'll be ready?
>

First thing is to remeber that 0.99.3 is already released and can be
installed from source.

Secondly we (including me) are working on getting the packages up, but
there seem to be a lot of stumbling blocks in the way. Yesterday morning I
thought I had implemented a solution for Ubuntu in the daily build system,
but right now things do not even build on launchpad and I admit I do not
even have a slight idea of what the issue is. So googling and try-and-error
goes on ;) I really have no idea when packages will be available. Maybe we
even drop the idea of providing them [at least for some distros] given the
vast amount of work this requires for us and the [IMHO] often not very
professional result :-(

On the bright side, we seem to have a workable solution for Centos now.
Florian will post more info shortly.

Rainer

**Comment by rgerhards** [comment] 2016-07-22 06:52
sorry, the PPAs will be discontinued: http://lists.adiscon.net/pipermail/rsyslog/2016-July/043092.html

So you need to build from source.

**Comment by radu-gheorghe** [comment] 2016-07-23 18:56
Yes, I've seen that. Let's hope we can find a solution eventually.
