### ISSUE TITLE
rsyslog-8.2106 tests fail

### ISSUE THREAD

**Issue by baal-zebub** [rsyslog/rsyslog#4619] opened 2021-06-30 12:24 UTC
### Expected behavior
Tests pass
### Actual behavior
Over 50 tests fail
### Steps to reproduce the behavior
I haven't run it outside of Void Linux so it may not work on other distros, but here it is anyway - in short, I'm trying to package the most recent rsyslog version for Void:

1. Clone [baal-zebub/void-packages](https://github.com/baal-zebub/void-packages) and check out `rsyslog` branch
2. `cd` to the cloned directory and run `./xbps-src binary-bootstrap`
3. Run `./xbps-src -Q pkg rsyslog` - this will run the tests while attempting to build a package
4. Test log can be found in `masterdir/builddir/rsyslog-8.2106.0/tests/test-suite.log` - [here's mine](https://github.com/rsyslog/rsyslog/files/6740799/test-suite.log)

### Environment
- rsyslog version: 8.2106
- platform: Void Linux x86_64

**Comment by rgerhards** [comment] 2021-06-30 13:02
> 3\. Run `./xbps-src -Q pkg rsyslog` - this will run the tests while attempting to build a package

I have no idea what this does, but it looks like it does not set environment variables correctly or has an issue calling make. Also, is this IPv6 only? The testbench needs 127.0.0.1.

**Comment by rgerhards** [comment] 2021-06-30 15:27
mhhh, that's strange, we also use github inside CI, see e.g. here: https://github.com/rsyslog/rsyslog/pull/4618/checks?check_run_id=2947923851 - Note, though, that we do usually run inside containers, not on top of the native VM.

Well, you can disable tests by doing `exit 77` right at the top of the test - that's the easiest way. But usually all should be well by leaving everything as usual. You can also disable some tests groups via configure switches.

**Comment by zdykstra** [comment] 2021-06-30 15:33
> mhhh, that's strange, we also use github inside CI, see e.g. here: https://github.com/rsyslog/rsyslog/pull/4618/checks?check_run_id=2947923851 - Note, though, that we do usually run inside containers, not on top of the native VM.
> 
> Well, you can disable tests by doing `exit 77` right at the top of the test - that's the easiest way. But usually all should be well by leaving everything as usual. You can also disable some tests groups via configure switches.

Ahh, thank you. That's good to know. I'll dig through the tests that are failing on the Void side to see if I can find a common thread on them.  It's not ideal to disable tests - they're there for a specific reason.

**Comment by rgerhards** [comment] 2021-06-30 15:35
even more so as it looks like a systematic issue. I don't see the make check invocation. You may want to try `make check -j1` to disable parallelism if that causes some problems. Should be the case, but may be worth a try.

If you run it with excessive parallelism (-j alone or -jnn with nn> 10), btw, you will run into problems (often resource constraints).

**Comment by rgerhards** [comment] 2021-06-30 15:39
side-note: we see some flakes in sometimes in a couple of tests, because it is very hard to get the timing right, especially when run in parallel. E.g. some tests kill -9 rsyslog and, to make this real, we catch it whereever it is. Bad timing can cause bad things in these tests very occasionally. Similarly, we have not yet found a reliable way to assign free ports to some test tools, so the higher the system load (and parallel runs), the higher the likelyhood that something with the port assignment will go wrong.

We usually run 8 tests  in parallel and that works sufficiently well.

**Comment by rgerhards** [comment] 2021-06-30 15:48
This is from your log:
```
rsyslogd: Error while binding tcp socket: Permission denied [v8.2106.0]
rsyslogd: Error while binding tcp socket: Permission denied [v8.2106.0]
rsyslogd: Could not create tcp listener, ignoring port 514 bind-address (null). [v8.2106.0 try https://www.rsyslog.com/e/2077 
```
It is strange, because the testbench plumbing will not use privileged ports (we usually run as non-root). So I wonder why 514 was selected. I don't see enough from the test-suite log.

If you can run individual tests (in some stage), you can cd into the `./tests` dir and just call the test in question via `./sndrcv_udp_nonstdpt_v6.sh`. If you modify diag.sh beforehand and enable the debug settings in line 79 and 80 ( https://github.com/rsyslog/rsyslog/blob/master/tests/diag.sh#L79 ), you get a very in-depth log file `log`  after the run. That would be helpful for me.

**Comment by rgerhards** [comment] 2021-06-30 15:50
I just notice the test I was quoting is a special case, you can uncomment just the RSYSLOG_DEBUG setting in this test. It writes both a server and receiver log file.

**Comment by zdykstra** [comment] 2021-06-30 16:15
Based on what I'm seeing, Void isn't running parallel builds or tests for rsyslog. I've enabled both of the RSYSLOG_DEBUG exports, and tests are running now on my local machine. The log file is already 3+GB and I'm only ~30 tests in. Hopefully I'll be able to send the debug log to you in some fashion.

```
$ git diff .
diff --git a/srcpkgs/rsyslog/template b/srcpkgs/rsyslog/template
index 33c55076e9..f87677831c 100644
--- a/srcpkgs/rsyslog/template
+++ b/srcpkgs/rsyslog/template
@@ -1,24 +1,25 @@
 # Template file for 'rsyslog'
 pkgname=rsyslog
-version=8.2010.0
-revision=4
+version=8.2106.0
+revision=1
 build_style=gnu-configure
 configure_args="--sbindir=/usr/bin --enable-gnutls --enable-mysql
  --enable-pgsql --enable-imdiag --enable-imfile --enable-mail --enable-imptcp
  --enable-gssapi-krb5 --enable-mmsnmptrapd --enable-impstats --enable-omprog
  --enable-omstdout --enable-pmlastmsg --enable-pmcisconames --enable-pmsnare
  --enable-pmaixforwardedfrom --enable-omuxsock --disable-generate-man-pages
- --enable-elasticsearch --enable-testbench"
+ --enable-elasticsearch --enable-testbench --disable-libsystemd"
 hostmakedepends="pkg-config postgresql-libs-devel"
 makedepends="gnutls-devel libcurl-devel libestr-devel libfastjson-devel
- liblogging-devel libmariadbclient-devel mit-krb5-devel postgresql-libs-devel"
+ liblogging-devel libmariadbclient-devel mit-krb5-devel postgresql-libs-devel
+ libgcrypt-devel"
 short_desc="Enhanced multi-threaded syslog daemon"
 maintainer="Orphaned <orphan@voidlinux.org>"
 license="GPL-3.0-or-later, Apache-2.0"
 homepage="https://www.rsyslog.com"
 changelog="https://raw.githubusercontent.com/rsyslog/rsyslog/master/ChangeLog"
 distfiles="${homepage}/files/download/rsyslog/${pkgname}-${version}.tar.gz"
-checksum=19b232f765c4ba7a35b91ef1f5f9af775f6ff78ef56bb7737a2ce79ccbb32b98
+checksum=faf45c25a2265c001739e8888b3652cf685eb3f35cd65d17d5c38fd44b9ddd81
 conf_files="/etc/rsyslog.conf"
 make_dirs="/etc/rsyslog.d 0755 root root"
 lib32disabled=yes
@@ -33,6 +34,8 @@ pre_configure() {
                vsed -e "s,\`\$PG_CONFIG --libdir\`,\"$XBPS_CROSS_BASE/usr/lib\",g" -i configure
                vsed -e "s,\`\$PG_CONFIG --includedir\`,\"$XBPS_CROSS_BASE/usr/include\",g" -i configure
        fi
+
+       vsed -e "s,#export\ RSYSLOG_DEBUG,export\ RSYSLOG_DEBUG,g" -i tests/diag.sh
 }

 post_install() {
```

**Comment by zdykstra** [comment] 2021-06-30 16:25
Ahh, it looks like each test writes their output to an individual log file. Would you just like the failed test logs, or would everything be helpful?

**Comment by rgerhards** [comment] 2021-06-30 17:14
The individual log files are just combined by make dist into test-suite.log. So a real (real!) verbose log you get only by setting the DEBUG variable. However, they write to the same log, and this mode is soo slow, that you cannot run the full test bench.

Instead run the individual test as I said above.

**Comment by zdykstra** [comment] 2021-06-30 17:34
Ahh, I see. 

Truncated build log showing only the check stage: https://pastebin.stratumzero.date/u/p/a9bab2f6fe/build.txt
Log file generated by the test: https://pastebin.stratumzero.date/u/p/761b49fc62/log

I should note that `xbps-src` runs builds as an unprivileged user inside a restricted environment. It'll for sure hit issues binding to ports below 1024 as a result of this.

**Comment by rgerhards** [comment] 2021-06-30 18:35
That's the same we do. Thus I wonder how port 514 is selected. We query the OS either for a free port (racy, only done when no other way) or bind to port 0 and let the OS assign a non-priv port.

**Comment by zdykstra** [comment] 2021-06-30 18:41
I'm waiting for all the tests to finish; The only tests/Makefile target that compiles the required test helpers also executes all of the tests. I'm running the full suite without debug logging enabled, and then I'll enable debug logging and run `sndrcv_udp_nonstdpt_v6.sh` inside the build environment. Should hopefully be done soon. Thanks for your help and patience!

**Comment by zdykstra** [comment] 2021-06-30 19:19
Whoops. This makes sense now. The number of failures and even the individual test failures weren't the same between runs. We were hitting a timing error because `ps` isn't in our build environment by default. Adding that in, I was able to pass 477 tests and skip 11, out of 488.  We'll run this against our glibc/musl CI again, but I _believe_ the issue is now fixed on our end.

Thank you for the help!

**Comment by rgerhards** [comment] 2021-07-01 06:51
Thx for the info. Hadn't thought that `ps` might not be present. Please let me know how it finally turns out.

**Comment by baal-zebub** [comment] 2021-08-03 21:41
Currently six tests still fail locally and on GitHub. I can't find a way to access the test log for the former, but locally each test output has the following message prepended to it which causes them to fail  -`event-horizon` is my hostname:
```
getaddrinfo failed obtaining local hostname - using 'event-horizon' instead; error: No address associated with hostname [v8.2106.0]
```

The full log is available [here](https://pastebin.com/HUr6rJ2T).

**Comment by rgerhards** [comment] 2021-08-06 09:05
Is this an IPv6-only environment? We may have an issue in this regard.

**Comment by rgerhards** [comment] 2021-08-06 09:14
forget about IPv6 ;-). What we do is

1. query the local host name
2. if it is not a FQDN, check if we can obtain the FQDN via address resolution

However, it looks like `getaddrinfo()`, the resolving function, fails. So your resolver seems not to be able to resolve the local host name at all. To me this looks like a system misconfiguration (can you do a `ping event-horizon`?).

That in turn triggers output unexpected by the test and causes it to fail. One can argue that the test should be hardened against all unexpected output. This is true, but probably hard (when we try to keep the test otherwise minimal). I will see if I can do something in this regard.

Can you pls also check your system config and report your findings?

**Comment by rgerhards** [comment] 2021-08-06 09:17
Oh, and BTW for some reason `tr` fails at

https://github.com/rsyslog/rsyslog/blob/master/tests/diag.sh#L2530

I don't know why, but that explains why tests cannot be run in parallel. If you have a hint of what may make it fail (what is missing?) I would appreciate it.

**Comment by zdykstra** [comment] 2021-08-07 00:52
The tests that are failing on GitHub CI are different than what are failing locally for @baal-zebub 

[GitHub CI/CD](https://github.com/zdykstra/void-packages/pull/1/checks?check_run_id=3266997674#step:8:2219)
* omfile-read-only-errmsg.sh
* omfile-read-only.sh
* privdropuser.sh
* privdropuserid.sh
* privdropgroup.sh
* privdropgroupid.sh

[local build](https://pastebin.com/HUr6rJ2T)

* omfwd-keepalive
* msgdup
* imuxsock_legacy
* imuxsock_logger
* imuxsock_logger_parserchain
* imuxsock_logger_syssock

The tests for a local build seem to be entirely related to broken hostname resolution. Tests under GitHub CI/CD are something else. A high-level log of the test suite is available at https://github.com/zdykstra/void-packages/pull/1/checks?check_run_id=3266997674#step:8:2219 .

**Comment by rgerhards** [comment] 2021-08-09 08:55
I have patched the tests to be tolerant against the extra messages for the failed resolution. That patch should solve the issues on your local system.

Re the posted check links - I don't see a failure there - am I overlooking something? If so, please point me to the exact check in question. Thx!

**Comment by zdykstra** [comment] 2021-08-09 14:17
> I have patched the tests to be tolerant against the extra messages for the failed resolution. That patch should solve the issues on your local system.
> 
> Re the posted check links - I don't see a failure there - am I overlooking something? If so, please point me to the exact check in question. Thx!

Hopefully this link works for you - https://github.com/zdykstra/void-packages/pull/1/checks?check_run_id=3267316292#step:8:2217

**Comment by rgerhards** [comment] 2021-08-09 15:39
Thx, that helps me.

Do I correctly see that `make distcheck` is run as root? That may cause issues at least for the privilege drop test (we anticipate that the testbench is run by a non-root user).

**Comment by zdykstra** [comment] 2021-08-09 16:02
I've confirmed that `xbps-src` and everything it invokes is run as root in the container under our CI/CD. For the log output / run linked above, I'm executing `make check`. I don't think there's a reasonable option to run `make check` as an unprivileged user in our current CI/CD process.

**Comment by rgerhards** [comment] 2021-08-23 07:43
@zdykstra I would appreciate if you could give #4662 a try - it should fix the remaining issues with the PrivDrop tests. I have set it to close this issue when merged.

**Closed** 2021-09-07 07:45 UTC

**Comment by rgerhards** [comment] 2021-09-07 07:47
@zdykstra I have now merged the PR and guess it will finally fix your issues. If problems persist, please let us know.
