### ISSUE TITLE
cannot find error in my config file

### ISSUE THREAD

**Issue by mfeagley** [rsyslog/rsyslog#3554] opened 2019-03-19 15:46 UTC
### Actual behavior
I'm experiencing an issue with rsyslog in that something in my .conf file is not correct causing the errors included below.  I wish to use "if/then" to route four different types of "mcafee" events to separate log directories.  I have included the related portion of my /etc/rsyslog_tls_splunk.conf file below.  BTW...line 79 is the last line of the .conf file.

Mar 19 09:26:20 lacross systemd[1]: Starting System Logging Service...
Mar 19 09:26:20 lacross rsyslogd[39823]:  [origin software="rsyslogd" swVersion="8.24.0-34.el7" x-pid="39823" x-info="http://www.rsyslog.com"] start
Mar 19 09:26:21 lacross rsyslogd[39823]: error during parsing file /etc/rsyslog_tls_splunk.conf, on or before line 79: syntax error on token '' [v8.24.0-34.el7 try http://www.rsyslog.com/e/2207 ]
Mar 19 09:26:21 lacross rsyslogd[39823]: CONFIG ERROR: could not interpret master config file '/etc/rsyslog_tls_splunk.conf'. [v8.24.0-34.el7 try http://www.rsyslog.com/e/2207 ]

### Environment
- rsyslog version: 8.24.0-34.el7
- platform: Red Hat Enterprise Linux Server release 7.6 (Maipo)
- for configuration questions/issues, include rsyslog.conf and included config files

Here is the pertinent portion of my .conf file:
```
# -----------------------------------------------------------

# INPUTS:
input(type="imtcp" port="6514" address="xxx.xxx.xxx.xxx"
      ruleset="writemcafee")
# -----------------------------------------------------------

# TEMPLATES:
template(name="virusscan" type="string" string="/data/lmintel/syslog-den/mcafee/virusscan/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%-%$HOUR%.log")

template(name="msme" type="string" string="/data/lmintel/syslog-den/mcafee/msme/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%-%$HOUR%.log")

template(name="avecto" type="string" string="/data/lmintel/syslog-den/mcafee/avecto/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%-%$HOUR%.log")

template(name="endpoint" type="string" string="/data/lmintel/syslog-den/mcafee/endpoint/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%-%$HOUR%.log")

# -----------------------------------------------------------

# RULESETS:
# now define our rulesets, which also can include
# threading and queue parameters.
#
ruleset(name="writemcafee")
{
   if $rawmsg contains "VirusScan Enterprise" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="virusscan")
   }
   else
   {
   if $rawmsg contains "ProductName=*MSME*" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="msme")
   }
   else
   {
   if $rawmsg contains "Avecto Defendpoint" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="avecto")
   }
   else
   {
   if $rawmsg contains "McAfee Endpoint Security" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="endpoint")
}
```

**Comment by mfeagley** [comment] 2019-03-19 15:47
Thank you in advance!

**Comment by davidelang** [comment] 2019-03-19 17:33
please post your complete config. When there is a syntax error it is frequently 
caused by something prior to the part of the file that shows up in the error 
message (and it's much easier to see where line 79 is with the entire file than 
with a portion of it)

David Lang

**Comment by mfeagley** [comment] 2019-03-19 17:52
#
$MaxMessageSize 256k
#
# Set gtls driver
$DefaultNetstreamDriver gtls
#
# Certs
$DefaultNetstreamDriverCAFile /xxx/xxx/xxx/xxx/xxx/xxx-ca-bundle.pem
$DefaultNetstreamDriverCertFile /xxx/xxx/xxx/certs/xxxxxx.xxx.com.pem
$DefaultNetstreamDriverKeyFile /xxx/xxx/xxx/certs/xxxxxx.xxx.com.key
#
# Listen for TCP
$ModLoad imtcp #tcp listener
#
$InputTCPServerStreamDriverMode 1

# Auth mode
$InputTCPServerStreamDriverAuthMode anon

# Listen on port 6514
$InputTCPServerRun 6514

#$EscapeControlCharactersOnReceive off

# listeners
# repeat blocks if more listeners are needed
# alternatively, use array syntax:
# port=["6514",...]
#
# -----> This section below will change based on application
# -----> Replace APPn with the appropriate Source Names 1 --> 20
#
# -----------------------------------------------------------

# INPUTS:
input(type="imtcp" port="6514" address="xxx.xxx.xxx.xxx"
      ruleset="writemcafee")
# -----------------------------------------------------------

# TEMPLATES:
template(name="virusscan" type="string" string="/data/xxxxxx/syslog-den/mcafee/virusscan/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%-%$HOUR%.log")
template(name="msme" type="string" string="/data/xxxxxx/syslog-den/mcafee/msme/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%-%$HOUR%.log")
template(name="avecto" type="string" string="/data/xxxxxx/syslog-den/mcafee/avecto/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%-%$HOUR%.log")
template(name="endpoint" type="string" string="/data/xxxxxx/syslog-den/mcafee/endpoint/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%-%$HOUR%.log")

# -----------------------------------------------------------

# RULESETS:
# now define our rulesets, which also can include
# threading and queue parameters.
#
ruleset(name="writemcafee")
{
   if $rawmsg contains "VirusScan Enterprise" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="virusscan")
   }
   else
   {
   if $rawmsg contains "ProductName=*MSME*" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="msme")
   }
   else
   {
   if $rawmsg contains "Avecto Defendpoint" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="avecto")
   }
   else
   {
   if $rawmsg contains "McAfee Endpoint Security" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="endpoint")
}

**Comment by rgerhards** [comment] 2019-03-20 09:06
missing brace. buggy:
```
   if $rawmsg contains "McAfee Endpoint Security" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="endpoint")
}
```
fixed:
```
   if $rawmsg contains "McAfee Endpoint Security" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="endpoint")
   }
}
```
Hard to detect by parser. Not sure if the current version can generate a better error message, bug I fear that's not the case.

**Comment by mfeagley** [comment] 2019-03-20 11:17
Added ending brace:

{
   if $rawmsg contains "McAfee Endpoint Security" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="endpoint")
   }
}



Error is now:

Mar 20 05:13:13 lacross systemd[1]: Starting System Logging Service...
Mar 20 05:13:13 lacross rsyslogd[2569]:  [origin software="rsyslogd" swVersion="8.24.0-34.el7" x-pid="2569" x-info="http://www.rsyslog.com"] start
Mar 20 05:13:14 lacross rsyslogd[2569]: error during parsing file /etc/rsyslog_tls_splunk.conf, on or before line 80: syntax error on token '' [v8.24.0-34.el7 try http://www....com/e/2207 ]
Mar 20 05:13:14 lacross rsyslogd[2569]: CONFIG ERROR: could not interpret master config file '/etc/rsyslog_tls_splunk.conf'. [v8.24.0-34.el7 try http://www.rsyslog.com/e/2207 ]
Mar 20 05:13:14 lacross systemd[1]: Started System Logging Service.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by rgerhards** [comment] 2019-03-20 11:18
As @davidelang said, it would be useful to have your full config. With just the include file I don't see the issue.

**Comment by mfeagley** [comment] 2019-03-20 11:40
Error is now:

Mar 20 05:37:50 %hostname% rsyslogd[4432]: error during parsing file /etc/rsyslog_tls_splunk.conf, on or before line 80: syntax error on token '' [v8.24.0-34.el7 try http://www.rsyslog.com/e/2207 ]
Mar 20 05:37:50 %hostname% rsyslogd[4432]: CONFIG ERROR: could not interpret master config file '/etc/rsyslog_tls_splunk.conf'. [v8.24.0-34.el7 try http://www.rsyslog.com/e/2207 ]



#
$MaxMessageSize 256k
#
# Set gtls driver
$DefaultNetstreamDriver gtls
#
# Certs
$DefaultNetstreamDriverCAFile /xxx/xxx/xxx/xxx/xxx/xxxxxx.pem
$DefaultNetstreamDriverCertFile /xxx/xxx/xxx/xxx/xxxxxx.com.pem
$DefaultNetstreamDriverKeyFile /xxx/xxx/xxx/xxx/xxxxxx.key
#
# Listen for TCP
$ModLoad imtcp #tcp listener
#
$InputTCPServerStreamDriverMode 1

# Auth mode
$InputTCPServerStreamDriverAuthMode anon

# Listen on port 6514
$InputTCPServerRun 6514

#$EscapeControlCharactersOnReceive off

# listeners
# repeat blocks if more listeners are needed
# alternatively, use array syntax:
# port=["6514",...]
#
# -----> This section below will change based on application
# -----> Replace APPn with the appropriate Source Names 1 --> 20
#
# -----------------------------------------------------------

# INPUTS:
input(type="imtcp" port="6514" address="xxx.xxx.xxx.xxx"
      ruleset="writemcafee")
# -----------------------------------------------------------

# TEMPLATES:
template(name="virusscan" type="string" string="/data/xxxxxx/syslog-den/mcafee/virusscan/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%-%$HOUR%.log")
template(name="msme" type="string" string="/data/xxxxxx/syslog-den/mcafee/msme/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%-%$HOUR%.log")
template(name="avecto" type="string" string="/data/xxxxxx/syslog-den/mcafee/avecto/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%-%$HOUR%.log")
template(name="endpoint" type="string" string="/data/xxxxxx/syslog-den/mcafee/endpoint/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%-%$HOUR%.log")

# -----------------------------------------------------------

# RULESETS:
# now define our rulesets, which also can include
# threading and queue parameters.
#
ruleset(name="writemcafee")
{
   if $rawmsg contains "VirusScan Enterprise" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="virusscan")
   }
   else
   {
   if $rawmsg contains "ProductName=*MSME*" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="msme")
   }
   else
   {
   if $rawmsg contains "Avecto Defendpoint" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="avecto")
   }
   else
   {
   if $rawmsg contains "McAfee Endpoint Security" then
   {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="endpoint")
   }
}

**Comment by rgerhards** [comment] 2019-03-20 11:44
This is still not the **full** config, just an include file. The problem may exist outside of that file. Include doc: https://www.rsyslog.com/doc/master/rainerscript/include.html

Oh, but I see what happens: you open many more blocks than you close! I use an editor which matches braces, and now the mismatch is on the one before. You need to close each brace that you open.

**Comment by rgerhards** [comment] 2019-03-20 11:52
or better do not use blocks for the else part if what you really want to do is an else-if chain. I have condensed the ruleset definition and remove the (invalid) block structure in else:
```
ruleset(name="writemcafee")
{
   if $rawmsg contains "VirusScan Enterprise" then {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="virusscan")
   } else  if $rawmsg contains "ProductName=*MSME*" then {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="msme")
   } else if $rawmsg contains "Avecto Defendpoint" then {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="avecto")
   } else if $rawmsg contains "McAfee Endpoint Security" then {
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="endpoint")
   }
}
```
I haven't tested it, but I think it should work. It's so much easier to read as well.

As you only use a single action, you could also reduce the `then` part a bit further:
```
ruleset(name="writemcafee")
{
   if $rawmsg contains "VirusScan Enterprise" then
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="virusscan")
   else  if $rawmsg contains "ProductName=*MSME*" then
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="msme")
   else if $rawmsg contains "Avecto Defendpoint" then
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="avecto")
   else if $rawmsg contains "McAfee Endpoint Security" then
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="endpoint")
}
```
You need braces only for blocks (multiple statements). For single statements they are purely optional. Nevertheless it often is a good idea to use them in `then`. If you later add more statements you sometimes do not realize what the problem is when braces are missing.

**Comment by rgerhards** [comment] 2019-03-20 12:01
For further reference. What you actually did looks, with proper indention like this:
```
ruleset(name="writemcafee")
{
   if $rawmsg contains "VirusScan Enterprise" then
	   {
	      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="virusscan")
	   }
   else
	   {
	   if $rawmsg contains "ProductName=*MSME*" then
		   {
		      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="msme")
		   }
	   else
		   {
		   if $rawmsg contains "Avecto Defendpoint" then
			   {
			      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="avecto")
			   }
		   else
		   {
			   if $rawmsg contains "McAfee Endpoint Security" then
			   {
			      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="endpoint")
}
```
Now it is easy to see that the closing braces are matching.

It saves a lot of trouble if you indent each time you open a brace and go one level back when you close one.

**Comment by mfeagley** [comment] 2019-03-20 12:06
I included:

ruleset(name="writemcafee")
{
   if $rawmsg contains "VirusScan Enterprise" then
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="virusscan")
   else  if $rawmsg contains "ProductName=*MSME*" then
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="msme")
   else if $rawmsg contains "Avecto Defendpoint" then
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="avecto")
   else if $rawmsg contains "McAfee Endpoint Security" then
      action(type="omfile" fileOwner="splunk" dirOwner="splunk" dirCreateMode="0755" fileCreateMode="0644" dynaFile="endpoint")
}

That worked!    

Many thanks!

**Closed** 2020-06-05 07:07 UTC
Labels: question
