### ISSUE TITLE
problem on disk queue ... 1 messages fewer than specified ... we lost those messages

### ISSUE THREAD

**Issue by mostolog** [rsyslog/rsyslog#1269] opened 2016-11-21 10:42 UTC
Hi

This warning appears sometimes when using 8.23+RELP. Could anyone tell me how whould I proceed? Debug? Backtrace?

```
rsyslogd: problem on disk queue 'main Q[DA]': queue files contain 1 messages fewer than specified in .qi file -- we lost those messages. That's all we know. [v8.23.0.master try http://www.rsyslog.com/e/0 ]
```

**Comment by rgerhards** [comment] 2016-11-22 17:20
A debug log of such a case would be most helpful. I've heard about some cases, but have no way yet to reproduce it. It looks unrelated to relp, more inside the queue subsystem.

**Comment by mostolog** [comment] 2016-11-23 11:16
As I have a heavy-test pending, I'll try to catch what's happening. Sadly, this errors doesn't seem to raise when debug is enabled...

**Comment by rgerhards** [comment] 2016-11-23 13:42
Can you collect pstats data during the test, in short intervals? Maybe this
helps us to understand what happens. I admit the chance is slim, but it may
be better than nothing...

Rainer

**Comment by davidelang** [comment] 2016-11-23 16:37
> As I have a heavy-test pending, I'll try to catch what's happening. Sadly, this errors doesn't seem to raise when debug is enabled...

Unfortunantly this is fairly common. Debug mode ends up serializing a lot of 
things and so race conditions are hard to track down.

I would guess that the problem you have is a race condition betwen writing the 
.qi file and writing the message contents to the queue file. It may even be a 
race that happened in the filesystem/kernel code rather than in the rsyslog 
code.

remember that to perform well, rsyslog doesn't do fsyncs, so in a crash, some 
stuff may not end up making it to disk.

David Lang

**Comment by rgerhards** [comment] 2016-11-23 16:45
He is not talking about a crash, so things *should* be serialized. I, however, also have heard (vaguely) that this can happen during normal operations and thus would be very interested to see an actual case. Code review brought nothing up.

The warning was added in 8.21 (I think) as part of the queue robustness improvements. Formerly, this lead to queue corruption. So we are way better off now, but still don't know the root cause.

**Comment by mostolog** [comment] 2016-11-23 16:49
I'll try to reproduce it tomorrow...due to some problems on source computers, they weren't able to send me logs today.

**Comment by rgerhards** [comment] 2017-03-24 10:10
8.26 will probably have better error messages. Closing this, as it is dormant for some time. If current master shows same issue, let us know, we can always re-open.

**Closed by rgerhards** 2017-03-24 10:10 UTC

**Comment by radosroka** [comment] 2017-08-28 15:12
Hi @rgerhards,

I discovered that "omfwd" has some problem with TCP and queue.
When TCP server side is not available then first N messages are messing.

N >= 1

Steps:
0. rm -rf /var/spool/rsyslog/*q_fwd*
1. # service rsyslog start && for i in {01..100}; do logger -u /var/run/test "test message >$i<"; done && service rsyslog stop
2. check queue content (some messages are missing)
3. nc -l 127.0.0.1 514 | tee queue_dump.txt &
4. service rsyslog start

This is always reproducible. I tried this on RHEL7.4 with official rsyslog-8.24.0.

```
global( workDirectory="/var/spool/rsyslog" )
module( load="builtin:omfile" )

module( load="imuxsock"
        SysSock.Use="off"
)

input(
        type="imuxsock"
        Socket="/var/run/test"
        CreatePath="on"
)

*.* action(     type="omfwd"
        queue.type="LinkedList"
        queue.filename="q_fwd"
        action.resumeRetryCount="-1"
        queue.saveonshutdown="on"
        Target="127.0.0.1"
        Port="514"
        Protocol="udp"
)

*.* action(     type="omfile"
        file="/var/log/messages1"
)
```

What do you think? I tried to change queue type and ResendLastMSGOnReconnect without success. I'm suspicious about some race condition in TCP or rsyslog implementation.

**Comment by davidelang** [comment] 2017-08-28 16:30
forwqarding over tcp is not reliable, if the sender thinks that there is a 
connection, but the receive (or a firewall in the way) doesn't, all messages 
sent will be lost because the sender has no way of knowing that they didn't get 
through. Eventually the sender gets a network error and opens a new connection.

over a local network, UDP can end up being more reliable (it has different 
failure modes, which are less likely to cause problems over a local network)

If you need reliable delivery, you need to use RELP.

see rainer's blog post about TCP syslog being unreliable. IIRC it's linked to 
from the RELP documentation page or google "tcp syslog not reliable"
