### ISSUE TITLE
Unable to load mmnormalize module on v8.28

### ISSUE THREAD

**Issue by coleaeason** [rsyslog/rsyslog#1703] opened 2017-08-01 20:11 UTC
After updating to v8.28 of rsyslog, rsyslog-mmjsonparse, rsyslog-elasticsearch, rsyslog-mmnormalize from the Adiscon Ubuntu Repo; rsyslog is unable to load the mmnormalize module. When rsyslog is restarted it gives this error:
```
rsyslogd: could not load module '/usr/lib/rsyslog/mmnormalize.so', dlopen: /usr/lib/rsyslog/mmnormalize.so: undefined symbol: ln_loadSamplesFromString  [v8.28.0 try http://www.rsyslog.com/e/2066 ]
```

However, not all of our servers that were running v8.28 failed to load the mmnormalize module. One out of six identical servers was able to load it successfully.

**Comment by wdauchy** [comment] 2017-08-02 07:49
maybe an issue for https://github.com/rsyslog/rsyslog-pkg-ubuntu

**Comment by jay7x** [comment] 2017-08-16 07:11
It's packaging issue. I had the same on CentOS when using official rpm's. `rsyslog-mmnormalize` have no version on `liblognorm` runtime dependency. You may get the same for `rsyslog-relp` because `librelp` required version was bumped as well.

**Comment by friedl** [comment] 2017-08-16 13:35
@jay7x I tried what you described, but didn't experience the same. For me, yum installs the dependencies just fine.

Can you try with a fresh rsyslog installation? E.g. uninstall, then do a new install through yum?
Also, which EL version are you using and which rsyslog version did show this problem?

@coleaeason Which Ubuntu version are you on? 
Also, did you try with the latest version?

In the meantime I'll try to reproduce this.

**Comment by jay7x** [comment] 2017-08-17 08:02
@friedl This never happens on fresh install because package manager will install latest `liblognorm5` and `librelp`. But when you upgrading from previous version of rsyslog it will not. There is no runtime version requirement in RPM spec. So yum will not upgrade `liblognorm5` and `librelp` if you are running just `yum upgrade rsyslog`.

**Comment by rgerhards** [comment] 2017-09-15 16:39
closing as this is a packaging issue.

**Closed by rgerhards** 2017-09-15 16:39 UTC

**Comment by ralleman** [comment] 2017-09-20 22:57
So what's the solution?

**Comment by ralleman** [comment] 2017-09-20 23:06
I'm still getting this after removing and readding:

8750.085944398:main thread    : errmsg.c: Called LogMsg, msg: could not load module '/lib64/rsyslog/mmnormalize.so', dlopen: /lib64/rsyslog/mmnormalize.so: undefined symbol: ln_loadSamplesFromString
8750.090904918:main thread    : errmsg.c: Called LogMsg, msg: module name 'mmnormalize' is unknown

**Comment by friedl** [comment] 2017-09-22 13:13
There was a package conflict with the liblognorm version provided by the base repo. This should be fixed now in our own repo. 

You might need to uninstall the liblognorm from the base repo manually though.

**Comment by alecswan** [comment] 2018-05-01 02:00
I am seeing a similar issue on CentOS 7 with 8.34.0 which I was finally able to build myself. What was the compatibility problem that you fixed in your repo?

```
May 01 01:51:16 rsyslogd[23041]: environment variable TZ is not set, auto correcting this to TZ=/etc/localtime  [v8.34.0 try http://www.rsyslog.com/e/2442 ]
May 01 01:51:16 rsyslogd[23041]: could not load module '/usr/lib64/rsyslog/mmnormalize.so', dlopen: /usr/lib64/rsyslog/mmnormalize.so: undefined symbol: ln_loadSamp...com/e/2066 ]
May 01 01:51:16 systemd[1]: Started System Logging Service.
May 01 01:51:16 rsyslogd[23041]: module name 'mmnormalize' is unknown [v8.34.0 try http://www.rsyslog.com/e/2209 ]
May 01 01:51:16 rsyslogd[23041]: error during parsing file /etc/rsyslog.d/pp-logfiles.conf, on or before line 109: errors occured in file '/etc/rsyslog.d/pp-logfile...com/e/2207 ]
May 01 01:51:16 rsyslogd[23041]: module name 'mmnormalize' is unknown [v8.34.0 try http://www.rsyslog.com/e/2209 ]
May 01 01:51:16 rsyslogd[23041]: error during parsing file /etc/rsyslog.d/pp-logfiles.conf, on or before line 176: errors occured in file '/etc/rsyslog.d/pp-logfile...com/e/2207 ]
May 01 01:51:16 rsyslogd[23041]: debug log file is '/var/log/rsyslog/rsyslog.debug', fd 4 [v8.34.0 try http://www.rsyslog.com/e/0 ]
May 01 01:51:16 rsyslogd[23041]:  [origin software="rsyslogd" swVersion="8.34.0" x-pid="23041" x-info="http://www.rsyslog.com"] start
May 01 01:51:17 rsyslogd[23041]: imjournal from <m0084354.lab.ppops.net:postfix>: begin to drop messages due to rate-limiting
```
Here are rsyslog related packages on my system.

# rpm -qa | grep 'rsyslog\|liblogn\|libfast'
rsyslog-mmnormalize-8.34.0-2.el7.centos.x86_64
libfastjson4-0.99.8-1.el7.centos.x86_64
rsyslog-8.34.0-2.el7.centos.x86_64
rsyslog-gnutls-8.34.0-2.el7.centos.x86_64
liblognorm-2.0.2-1.el7.x86_64
rsyslog-elasticsearch-8.34.0-2.el7.centos.x86_64

Thanks!

**Comment by rgerhards** [comment] 2018-05-01 08:58
looking the conversation as it is a packaging issue and I guess any new such issues that comes up is not related to the old one in any case. If you have a similar issue, please create an issue tracker in the right packaging project. Then it also directly goes to the right people.
