### ISSUE TITLE
Test failures on a 2 socket box with v8.14 branch

### ISSUE THREAD

**Issue by portante** [rsyslog/rsyslog#605] opened 2015-11-19 01:33 UTC
Just thought I would post the test failures that I found compiling and running on a Fedora 21 2 socket box:

```
==========================================
   rsyslog 8.14.0: tests/test-suite.log
==========================================

# TOTAL: 163
# PASS:  154
# SKIP:  5
# XFAIL: 0
# FAIL:  4
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

SKIP: sndrcv_udp.sh
===================

===============================================================================
[sndrcv_udp.sh]: testing sending and receiving via udp

FAIL: queue-persist.sh
======================

[queue-persist.sh]:
testing memory queue persisting to disk, mode LinkedList
rsyslogd started with pid  9895
injecting 5000 messages
imdiag[13500]: 5000 messages injected
There must exist some files now:
total 2172
-rw------- 1 pportant pportant 1048728 Nov 19 01:26 mainq.00000001
-rw------- 1 pportant pportant 1048728 Nov 19 01:26 mainq.00000002
-rw------- 1 pportant pportant  114622 Nov 19 01:26 mainq.00000003
-rw------- 1 pportant pportant     523 Nov 19 01:26 mainq.qi
rsyslogd started with pid  9917
imdiag[13500]: mainqueue empty
-------------------------------------------------------------------------------
testing memory queue persisting to disk, mode FixedArray
rsyslogd started with pid  9963
injecting 5000 messages
imdiag[13500]: 5000 messages injected
There must exist some files now:
total 2172
-rw------- 1 pportant pportant 1048728 Nov 19 01:26 mainq.00000001
-rw------- 1 pportant pportant 1048728 Nov 19 01:26 mainq.00000002
-rw------- 1 pportant pportant  114178 Nov 19 01:26 mainq.00000003
-rw------- 1 pportant pportant     523 Nov 19 01:26 mainq.qi
rsyslogd started with pid  9984
imdiag[13500]: mainqueue empty
read value 20, but expected value 19
sequence error detected

SKIP: imuxsock_logger_root.sh
=============================

[imuxsock_logger_root.sh]: test trailing LF handling in imuxsock
This test must be run as root with no other active syslogd

SKIP: imuxsock_traillf_root.sh
==============================

[imuxsock_traillf_root.sh]: test trailing LF handling in imuxsock
This test must be run as root with no other active syslogd

SKIP: imuxsock_ccmiddle_root.sh
===============================

[imuxsock_ccmiddle_root.sh]: test trailing LF handling in imuxsock
This test must be run as root with no other active syslogd

FAIL: mmnormalize_variable.sh
=============================

===============================================================================
[mmnormalize_variable.sh]: basic test for mmnormalize module variable-support
rsyslogd started with pid  13270
starting run 1
Sending file './testsuites/date_time_msg' 1 times.
00000001 kb sent
runtime: 0.000
End of tcpflood Run
doing shutdown
imdiag[13500]: mainqueue empty
wait on shutdown
content-check failed

FAIL: mmnormalize_tokenized.sh
==============================

===============================================================================
[mmnormalize_tokenized.sh]: test for mmnormalize tokenized field_type
rsyslogd started with pid  13311
starting run 1
Sending file './testsuites/tokenized_input' 1 times.
00000001 kb sent
runtime: 0.000
End of tcpflood Run
doing shutdown
imdiag[13500]: mainqueue empty
wait on shutdown
content-check failed

FAIL: mmnormalize_regex.sh
==========================

===============================================================================
[mmnormalize_regex.sh]: test for mmnormalize regex field_type
rsyslogd started with pid  13460
starting run 1
Sending file './testsuites/regex_input' 1 times.
00000001 kb sent
runtime: 0.000
End of tcpflood Run
doing shutdown
imdiag[13500]: mainqueue empty
wait on shutdown
content-check failed

SKIP: omod-if-array.sh
======================

[omod-if-array.sh]: test omod-if-array via udp
NOTE: the interface checked with this test is currently NOT
supported. We may support it again in the future. So for now,
we just skip this test and do not remove it.
```

**Comment by alorbach** [comment] 2015-11-19 13:59
The queue-persist test fails from time to time, the problem is very complex, the mmnormalize issues shouldn't fail. Which liblognorm version is installed by default?

**Comment by portante** [comment] 2015-11-19 17:57
I think `liblognorm` on Fedora 21 ships as 0.3.7-3, but I have installed 1.1.2-2.

**Comment by portante** [comment] 2015-11-25 00:55
@theinric, another concern I have for Fedora, CentOS, and RHEL.

**Comment by rgerhards** [comment] 2016-02-03 15:35
for queue-persists, see here: https://github.com/rsyslog/rsyslog/issues/262
Right now I consider this solved (patch upcoming very soon)

**Comment by rgerhards** [comment] 2016-03-03 13:11
this is solved, closing the bug was forgotten

**Closed by rgerhards** 2016-03-03 13:11 UTC
