### ISSUE TITLE
assertion failure and core dump when using bad configuration values in `omrelp`

### ISSUE THREAD

**Issue by nbrownus** [rsyslog/rsyslog#1024] opened 2016-05-11 17:42 UTC
Easy to reproduce with 

`action(type="omrelp" target="127.0.0.1" windowSize="-1")`

This is part of the debug log output

```
6156.998306188:7f2473fff700: thread created, tid 5670, name '...'
6156.998413378:... queue:Reg/w0: wti 0x12ee1a0: worker starting
6156.998426429:... queue:Reg/w0: DeleteProcessedBatch: we deleted 0 objects and enqueued 0 objects
6156.998434369:... queue:Reg/w0: doDeleteBatch: delete batch from store, new sizes: log 1, phys 1
6156.998470336:... queue:Reg/w0: action '...': is transactional - executing in commit phase
6156.998480261:... queue:Reg/w0: wti 0x12ee1a0: we need to create a new action worker instance for action 0
6156.998492869:... queue:Reg/w0: relp engine created new client 0x7f24680022e0
6156.998508684:... queue:Reg/w0: doTransaction: action 0, currIParam 1
6156.998514765:... queue:Reg/w0: omrelp: beginTransaction
rsyslogd: relpclt.c:161: relpCltReconnect: Assertion `(pThis->pSess) != ((void *)0)' failed.
Aborted (core dumped)
```

`doCreateRelpClient` fails in `BEGINcreateWrkrInstance` but the code in `action.c` disregards the failure and tries to use the half created relp client leading to the assertion failure.

This likely also impacts `omelasticsearch`.

**Comment by mostolog** [comment] 2016-11-02 08:15
@rgerhards This seems to be a "check return values" issue. Perhaps I could try to have an eye on it?

**Comment by rgerhards** [comment] 2016-11-02 08:18
Not sure what kind of issue it is, but any help you can provide for sure is appreciated. I would just suggest to also do a valgrind run (or address sanitizer build) as this might be the result of a previous misadressing that got uncought. It would also be great to craft a testbench test, if possible at all (I usually craft the test first, and then work on fixing, so I have a test environment).

**Comment by mostolog** [comment] 2016-11-02 08:57
If I'm not wrong, as reporter said, there's an assert at https://github.com/rsyslog/librelp/blob/master/src/relpclt.c#L160 which _compares_ instance,created at https://github.com/rsyslog/rsyslog/blob/master/plugins/omrelp/omrelp.c#L257 which invokes https://github.com/rsyslog/rsyslog/blob/master/plugins/omrelp/omrelp.c#L184.

To my understanding, if _doCreateRelpClient_ fails, BEGINcreateWrkrInstance _should?_ fail, not reaching _relpCltReconnect_, and not rising a core-dump.

Or is this the desired behaviour?

**Comment by rgerhards** [comment] 2016-11-02 09:11
Abort if of course but intended, but might still be the result of an
earlier misadressing...

Sent from phone, thus brief.

Am 02.11.2016 09:57 schrieb "mostolog" <notifications@github.com>:

**Comment by mostolog** [comment] 2016-11-04 08:19
I'm not able to reproduce it on 8.22+ reading from imfile, target omrelp and windowSize="-1". Tried both, with RELP target up and down.
@nbrownus Could you give us some more information on this?

**Comment by rgerhards** [comment] 2017-12-24 10:18
@nbrownus I assume this is solved, so I am closing. If not, please let us know and I'll re-open.

**Closed by rgerhards** 2017-12-24 10:18 UTC
