### ISSUE TITLE
RFE: Log the values for imrelp's MaxDataSize and global() maxMessageSize parameter values

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog#2215] opened 2017-12-13 14:55 UTC
While troubleshooting issues that apparently involve the size of the messages sent from the client, I was unable to locate the values for either of these parameters (assuming they're related) in the debug log.

While I can understand the argument that info is not really suited for a standard log output message, I believe it would be useful to at least have the information mentioned in the debug log. That said, I'd be happy to see something along the lines of, "XYZ input enabled, max message size limit of 128,000 bytes set" (with wording altered to fit the existing language/style).

refs:

- [source/rainerscript/global.rst](https://github.com/rsyslog/rsyslog-doc/blob/master/source/rainerscript/global.rst)
- [source/configuration/modules/imrelp.rst](https://github.com/rsyslog/rsyslog-doc/blob/master/source/configuration/modules/imrelp.rst)
- rsyslog/rsyslog#1782
- rsyslog/rsyslog#1741
- rsyslog/rsyslog-doc#432

**Comment by rgerhards** [comment] 2017-12-13 15:13
That's a bug, global(maxmessagesize="") is intended to set it for all modules.

**Comment by rgerhards** [comment] 2017-12-13 15:14
duplicate of https://github.com/rsyslog/rsyslog/issues/1741

**Comment by rgerhards** [comment] 2017-12-13 15:15
I see you mean the debug log output... let me check...

**Comment by rgerhards** [comment] 2017-12-13 15:17
you are right, it's not output (only as part of a parameter in a set operation). but RELP doesn't deserve it's own output ;-)

**Comment by deoren** [comment] 2017-12-13 15:19
Thanks for agreeing to work this in. This change and #2190 will be immensely helpful in troubleshooting RELP transfer issues.

**Comment by rgerhards** [comment] 2017-12-13 16:00
As imrelp actually has its own override (overlooked that initially), I now indeed output both as requested. Note that imrelp output is per listener basis, so potentially multiple times.

**Comment by rgerhards** [comment] 2017-12-13 16:01
@deoren #2190 does not have my priority. We should rather fix the root issue first. This one here was a real quick side-activity while checking the code. Thus the quick turnaround.

**Comment by deoren** [comment] 2017-12-13 16:04
@rgerhards Understood, thanks for working this in. This change alone will be useful for troubleshooting.

**Comment by deoren** [comment] 2017-12-13 21:46
@rgerhards I meant to say in my last response that implementing #2190 first (when you have time to look at the RELP problems noted on #1782 and #1741) could help with troubleshooting RELP transfer issues. This isn't an argument for looking at the RELP issues over something else, just noting that it would be helpful to troubleshoot on our end and collect more data to help solve the root issue.

**Closed** 2017-12-15 07:11 UTC
Labels: enhancement

**Comment by deoren** [comment] 2017-12-15 15:45
@rgerhards thanks again for implementing this. Already it has helped show that imrelp's `MaxDataSize` is not defaulting to the provided global `maxMessageSize` value as expected (https://github.com/rsyslog/rsyslog/issues/1782#issuecomment-352027757).
