### ISSUE TITLE
imfile + ReadMode 2 should accept patterns for handling stacktraces

### ISSUE THREAD

**Issue by radu-gheorghe** [rsyslog/rsyslog#282] opened 2015-03-25 17:00 UTC
See https://github.com/rsyslog/rsyslog/issues/144#issuecomment-85015662

Basically, ReadMode 2 currently works like this: if a line starts with a tab or a space, it belongs to the same event as the previous line. This doesn't work for all stacktraces, for example those having the second line starting with the class giving the stacktrace (most Java apps seem to log like that).

I see two options here:
- ideally, we'd be able to specify a regular expression that would match the whole line and check whether that line belongs to the previous or not. This is how syslog-ng and Logstash do it and seems to work well, but it might be tricky for rsyslog as it seems that stream.c reads one character at a time
- an easier way could be to configure which characters will make the current line belong to the previous one. Currently, spaces and tabs are hardcoded. Maybe if we make characters and character ranges configurable (and also to be able to negate) it would cover most cases. For example, one could say "if the line doesn't start with a square bracket". Still, this sounds hacky to me, I'm not sure how much it would help considering things like performance and other modules using stream.c's ReadLine()

**Comment by rgerhards** [comment] 2015-03-25 17:41
Sorry to be insistive, but please provide me with a text file of a couple of the stack traces you have on your mind. I am asking around at all places for several weeks now, and I *never* got at least one file. This can be interpreted so that nobody has interest in that functionality ;)

Can you elaborate a little bit on the regex approach: I guess it can't work on the line per se, because we have multiple lines and do not know how many we have. So do they just take an arbitrary large bunch of the file and see if it matches a regex and, if so, conclude that is what they are looking for. Also, does that mean that a file must contain stacktraces only or may different formats be mixed?

As I wrote in the other message, I intend to refactor the whole way imfile reads log lines. So there are no restrictions on what we may want to implement. But I want to have a really good solution, not just a quick one. We've been with (even defective ;)) ReadMode for so long, I think it doesn't hurt to wait another two or three month for an even better solution.

**Comment by otisg** [comment] 2015-03-27 18:05
Here is an example of a typical Java exception stack trace and the log line that printed it.  This is what log4j, logback, etc. output when one logs with e.g. LOG.warn("Here is the message", e); where 'e' is an instance (Java object instance) of Exception/Throwable, which ends up printing the stacktrace part of the log:

2014-09-22 10:09:49,864  WARN netty:129 - [Lightmaster] exception caught on transport layer [[id: 0xc23bb87c]], closing connection
java.net.NoRouteToHostException: No route to host
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:735)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)



Here is another one.  This one has info about nested exceptions (there are a lot more lines with "at ....", but I cut them out to keep things a little shorter) and, as you can see, NOT all lines that are part of the same stack trace are indented!

2015-03-27 17:29:29,542  WARN RMIAsynchronousCacheReplicator:325 - Unable to send message to remote peer.  Message was: RemoteException occurred in server thread; nested exception is: 
        java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is: 
        java.io.InvalidObjectException: Could not find a SessionFactory [uuid=12345,name=null]
java.rmi.ServerException: RemoteException occurred in server thread; nested exception is: 
        java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is: 
        java.io.InvalidObjectException: Could not find a SessionFactory [uuid=12345,name=null]
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:353)
        at sun.rmi.transport.Transport$1.run(Transport.java:177)
        at sun.rmi.transport.Transport$1.run(Transport.java:174)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:173)
Caused by: java.io.InvalidObjectException: Could not find a SessionFactory [uuid=12345,name=null]
        at org.hibernate.internal.SessionFactoryImpl.locateSessionFactoryOnDeserialization(SessionFactoryImpl.java:1781)
        at org.hibernate.internal.SessionFactoryImpl.readResolve(SessionFactoryImpl.java:1761)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:307)
        ... 10 more

I think all log files with Java exception traces have this format.  In 15-20 years working with Java I don't recall seeing any other formats. HTH

**Comment by rgerhards** [comment] 2015-03-27 18:07
Any chance to get this as a text file? ;)

**Comment by radu-gheorghe** [comment] 2015-03-30 09:30
I sent you quite a lot of logs from ES and Solr (lots of stacktraces there) a while ago. Subject was "Log Collapsing?" initiated by Otis. I think you got it, because you said thanks. But I can resend it.

**Comment by rgerhards** [comment] 2015-03-30 09:36
2015-03-30 11:30 GMT+02:00 Radu Gheorghe <notifications@github.com>:

> I sent you quite a lot of logs from ES and Solr (lots of stacktraces
> there) a while ago. Subject was "Log Collapsing?" initiated by Otis. I
> think you got it, because you said thanks. But I can resend it.
>
>
doh! my bad. I archived them improperly and wasn't aware they were present
:-( Now re-gained them and will have a log of fun with them.

Just for the recoreds: are the individual files in the format before
rsyslog processed them? I mean like the app has written them. Or are they
the result of rsyslog processing (which may has mangled things)?

From quick sampling it looks like they are original, but I thought I better
confirm.

Rainer

**Comment by radu-gheorghe** [comment] 2015-03-30 11:46
rsyslog didn't touch them, apps were writing files to disk using the default configuration. One can mangle with that configuration, but as Otis was suggesting very few people actually do.

**Comment by otisg** [comment] 2015-05-16 19:10
@rgerhards was this handled by #333 ?

**Comment by rgerhards** [comment] 2015-05-16 19:15
Yup, we now have regex.

Sent from phone, thus brief.
Am 16.05.2015 21:10 schrieb "Otis Gospodnetic" <notifications@github.com>:

**Comment by rgerhards** [comment] 2015-05-18 07:46
The new functionality will be released with 8.10.0.

**Closed by rgerhards** 2015-05-18 07:46 UTC
