### ISSUE TITLE
omkafka leaks memory when using compression

### ISSUE THREAD

**Issue by wanghonglei5181** [rsyslog/rsyslog#2586] opened 2018-03-27 07:18 UTC
memory leak? help!!!
**rsyslog use too much memory! i must be restart rsyslog every day  to avoid this problem!
rsyslog read a soft link and push data to kafka
if a real file not soft link every thing will be ok
help!!!!**

lrwxrwxrwx 1 root root   73 3月  27 00:00 nginx_rsyslog -> /data1/logs/nginx/access/2018/03/27/access_log

the size of file
0> du -sh /data1/logs/nginx/access/2018/03/26/isdn-access-test_log
24G	/data1/logs/nginx/access/2018/03/26/isdn-access-test_log
0> du -sh /data1/logs/nginx/access/2018/03/27/isdn-access-test_log
15G	/data1/logs/nginx/access/2018/03/27/isdn-access-test_log

this soft link will be created every day at 00:00
00 00 * * * root bash /usr/local/bin/create_soft_link.sh > /dev/null 2>&1

top 
PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                                                                       
 6871 root      20   0 4100m 616m  992 S  5.0  3.9  52:18.74 rsyslogd 

rsyslog version
130> rpm -qa |grep rsyslog
rsyslog-kafka-8.25.0-1.el6.x86_64
rsyslog-8.25.0-1.el6.x86_64

system 
0> uname -sr
Linux 2.6.32-431.11.2.el6.toa.2.x86_64

rsyslog.conf
0> cat /etc/rsyslog.conf| grep -v ^# | grep -v ^$
module(load="imuxsock") # provides support for local system logging (e.g. via logger command)
module(load="imklog")   # provides kernel logging support (previously done by rklogd)
module(load="imfile")
module(load="omkafka")
module(load="imudp") # needs to be done just once
$PreserveFQDN on
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$IncludeConfig /etc/rsyslog.d/*.conf
*.info;mail.none;authpriv.none;cron.none;local5.none;local6.none                /var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  /var/log/maillog
cron.*                                                  /var/log/cron
*.emerg                                                 :omusrmsg:*
uucp,news.crit                                          /var/log/spooler
local7.*                                                /var/log/boot.log
local6.*                                                @10.13.1.120:1590
global (
    maxMessageSize="32m"
    workDirectory="/data1/rsyslog"
    net.enableDNS="off"
)
main_queue (
    queue.filename="mainQ"
    queue.size="100000"
    queue.type="fixedarray"
    queue.maxfilesize="200M"
    queue.maxdiskspace="1G"
    queue.workerthreads="10"
    queue.discardseverity="8"
    queue.checkpointinterval="10"
    queue.saveonshutdown="on"
    queue.HighWatermark="60000"
    queue.LowWatermark="1000"
    queue.DiscardMark="100000"
    queue.DequeueBatchSize="500"
)

rsyslog.d/locafile.conf    ##included by rsyslog.conf
module(load="omkafka")
module(load="imfile")
$template test,"%$myhostname% %msg%"
ruleset(name="test") {
    action (
        name="action_logkafka"
        type="omkafka"
        partitions.auto="on"
        template="test"
        topic="wapcms_access_http"
        broker=["10.39.40.101:9110","10.39.40.102:9110","10.39.40.103:9110","10.39.40.104:9110","10.39.40.105:9110"]
        confParam=["compression.codec=snappy","socket.timeout.ms=5000","socket.keepalive.enable=true"]
        queue.filename="rsyslog_disk"
        queue.spoolDirectory="/data1/rsyslog"
        queue.maxdiskspace="10G"
        queue.maxfilesize="200M"
        queue.type="LinkedList"
        queue.size="360000"
        queue.workerthreads="12"
        queue.timeoutenqueue="0"
        queue.dequeuebatchsize="256"       
        queue.discardmark="288000"
        queue.discardseverity="8"
        queue.highwatermark="216000"
        queue.lowwatermark="2048"
        queue.fulldelaymark="1080000"
        queue.saveonshutdown="on"
    )
        action (
        name="action_logkafka"
        type="omkafka"
        partitions.auto="on"
        template="test"
        topic="langshou-nginx"
        broker=["10.13.88.190:9092","10.13.88.191:9092","10.13.88.192:9092","10.13.88.193:9092","10.13.88.194:9092"]
        confParam=["compression.codec=snappy","socket.timeout.ms=5000","socket.keepalive.enable=true"]
        queue.filename="rsyslog_disk"
        queue.spoolDirectory="/data1/rsyslog"
        queue.maxdiskspace="10G"
        queue.maxfilesize="200M"
        queue.type="LinkedList"
        queue.size="360000"
        queue.workerthreads="12"
        queue.timeoutenqueue="0"
        queue.dequeuebatchsize="256"
        queue.discardmark="288000"
        queue.discardseverity="8"
        queue.highwatermark="216000"
        queue.lowwatermark="2048"
        queue.fulldelaymark="1080000"
        queue.saveonshutdown="on"
    )
}
input(type="imfile" Tag="access_test" File="/data1/logs/nginx_rsyslog" Ruleset="test")

rsyslog.d/status.conf    ##included by rsyslog.conf
130> cat /etc/rsyslog.d/status.conf 
module(load="impstats"
    interval="60"
    severity="7"
    resetCounters="on"
    log.syslog="off"
    /* need to turn log stream logging off! */
    log.file="/data1/rsyslog/status.log"
)

/data1/rsyslog/status.log   ##the out put of impstat
Tue Mar 27 15:00:59 2018: main Q: origin=core.queue size=0 enqueued=69137 full=0 discarded.full=0 discarded.nf=0 maxqsize=3192 
Tue Mar 27 15:01:59 2018: global: origin=dynstats 
Tue Mar 27 15:01:59 2018: imuxsock: origin=imuxsock submitted=14 ratelimit.discarded=0 ratelimit.numratelimiters=0 
Tue Mar 27 15:01:59 2018: omkafka: submitted=137630 maxoutqsize=14999 failures=0 topicdynacache.skipped=0 topicdynacache.miss=0 topicdynacache.evicted=0 
Tue Mar 27 15:01:59 2018: action_logkafka: origin=core.action processed=68813 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:01:59 2018: action_logkafka: origin=core.action processed=68813 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:01:59 2018: action_logkafka: origin=core.action processed=4 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:01:59 2018: action 3: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:01:59 2018: action 4: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:01:59 2018: action 5: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:01:59 2018: action 6: origin=core.action processed=14 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:01:59 2018: action 7: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:01:59 2018: action 8: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:01:59 2018: action 9: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:01:59 2018: action 10: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:01:59 2018: resource-usage: origin=impstats utime=2204854811 stime=956716556 maxrss=636204 minflt=6978951 majflt=7 inblock=792 oublock=38568 nvcsw=68009898 nivcsw=80324 
Tue Mar 27 15:01:59 2018: action_logkafka queue[DA]: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Tue Mar 27 15:01:59 2018: action_logkafka queue: origin=core.queue size=0 enqueued=68813 full=0 discarded.full=0 discarded.nf=0 maxqsize=1928 
Tue Mar 27 15:01:59 2018: action_logkafka queue[DA]: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Tue Mar 27 15:01:59 2018: action_logkafka queue: origin=core.queue size=0 enqueued=68813 full=0 discarded.full=0 discarded.nf=0 maxqsize=2183 
Tue Mar 27 15:01:59 2018: action_logkafka queue[DA]: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Tue Mar 27 15:01:59 2018: action_logkafka queue: origin=core.queue size=0 enqueued=4 full=0 discarded.full=0 discarded.nf=0 maxqsize=1 
Tue Mar 27 15:01:59 2018: main Q[DA]: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Tue Mar 27 15:01:59 2018: main Q: origin=core.queue size=0 enqueued=68831 full=0 discarded.full=0 discarded.nf=0 maxqsize=3192 
Tue Mar 27 15:02:59 2018: global: origin=dynstats 
Tue Mar 27 15:02:59 2018: imuxsock: origin=imuxsock submitted=5 ratelimit.discarded=0 ratelimit.numratelimiters=0 
Tue Mar 27 15:02:59 2018: omkafka: submitted=137010 maxoutqsize=14999 failures=0 topicdynacache.skipped=0 topicdynacache.miss=0 topicdynacache.evicted=0 
Tue Mar 27 15:02:59 2018: action_logkafka: origin=core.action processed=68504 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:02:59 2018: action_logkafka: origin=core.action processed=68504 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:02:59 2018: action_logkafka: origin=core.action processed=2 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:02:59 2018: action 3: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:02:59 2018: action 4: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:02:59 2018: action 5: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:02:59 2018: action 6: origin=core.action processed=3 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:02:59 2018: action 7: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:02:59 2018: action 8: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:02:59 2018: action 9: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:02:59 2018: action 10: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Tue Mar 27 15:02:59 2018: resource-usage: origin=impstats utime=2206797515 stime=957443446 maxrss=636752 minflt=6986163 majflt=7 inblock=792 oublock=38584 nvcsw=68064046 nivcsw=80378 
Tue Mar 27 15:02:59 2018: action_logkafka queue[DA]: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Tue Mar 27 15:02:59 2018: action_logkafka queue: origin=core.queue size=0 enqueued=68504 full=0 discarded.full=0 discarded.nf=0 maxqsize=1928 
Tue Mar 27 15:02:59 2018: action_logkafka queue[DA]: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Tue Mar 27 15:02:59 2018: action_logkafka queue: origin=core.queue size=0 enqueued=68504 full=0 discarded.full=0 discarded.nf=0 maxqsize=2183 
Tue Mar 27 15:02:59 2018: action_logkafka queue[DA]: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Tue Mar 27 15:02:59 2018: action_logkafka queue: origin=core.queue size=0 enqueued=2 full=0 discarded.full=0 discarded.nf=0 maxqsize=1 
Tue Mar 27 15:02:59 2018: main Q[DA]: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Tue Mar 27 15:02:59 2018: main Q: origin=core.queue size=0 enqueued=68511 full=0 discarded.full=0 discarded.nf=0 maxqsize=3192 

/var/log/messages   ## some log about rsyslog
Mar 26 12:06:03 web003.langshou.msina.dbl.sinanode.com rsyslogd: omkafka: kafka message 10.13.88.190:9092/190: 6 request(s) timed out: disconnect [v8.25.0 try http://www.rsyslog.com/e/2422 ]
Mar 26 12:06:04 web003.langshou.msina.dbl.sinanode.com rsyslogd: omkafka: kafka message 10.13.88.190:9092/190: 3 request(s) timed out: disconnect [v8.25.0 try http://www.rsyslog.com/e/2422 ]
Mar 26 15:36:03 web003.langshou.msina.dbl.sinanode.com rsyslogd: omkafka: kafka message 10.13.88.192:9092/192: 3 request(s) timed out: disconnect [v8.25.0 try http://www.rsyslog.com/e/2422 ]
Mar 26 17:11:15 web003.langshou.msina.dbl.sinanode.com rsyslogd: omkafka: kafka message 10.13.88.193:9092/193: 3 request(s) timed out: disconnect [v8.25.0 try http://www.rsyslog.com/e/2422 ]
Mar 26 17:43:27 web003.langshou.msina.dbl.sinanode.com rsyslogd: omkafka: kafka message 10.13.88.193:9092/193: 3 request(s) timed out: disconnect [v8.25.0 try http://www.rsyslog.com/e/2422 ]
Mar 26 23:12:35 web003.langshou.msina.dbl.sinanode.com rsyslogd: omkafka: kafka message 10.13.88.193:9092/bootstrap: 3 request(s) timed out: disconnect [v8.25.0 try http://www.rsyslog.com/e/2422 ]
Mar 27 00:00:04 web003.langshou.msina.dbl.sinanode.com rsyslogd:  [origin software="rsyslogd" swVersion="8.25.0" x-pid="6871" x-info="http://www.rsyslog.com"] start
Mar 27 00:00:05 web003.langshou.msina.dbl.sinanode.com rsyslogd: module 'omkafka' already in this config, cannot be added  [v8.25.0 try http://www.rsyslog.com/e/2221 ]
Mar 27 00:00:05 web003.langshou.msina.dbl.sinanode.com rsyslogd: module 'imfile' already in this config, cannot be added  [v8.25.0 try http://www.rsyslog.com/e/2221 ]
Mar 27 00:00:05 web003.langshou.msina.dbl.sinanode.com rsyslogd: imudp: module loaded, but no listeners defined - no input will be gathered [v8.25.0 try http://www.rsyslog.com/e/2212 ]
Mar 27 12:12:19 web003.langshou.msina.dbl.sinanode.com rsyslogd: omkafka: kafka message 10.13.88.193:9092/193: 3 request(s) timed out: disconnect [v8.25.0 try http://www.rsyslog.com/e/2422 ]

**Comment by rgerhards** [comment] 2018-03-27 11:17
This is a known issue caused by a bug in librdkafka. With current releases of librdkafka, you cannot use compression. Recently the librdkafka team crafted a fix for that, but they did not yet craft a release.

**Comment by friedl** [comment] 2018-04-06 08:48
There was a new release of librdkafka that has the fix for this. The packages for the rsyslog project have also been updated to use this. 

You can install rsyslog 8.34.0 from our repositories to obtain the fixed version. Else you need to make sure to at least obtain the newest version of librdkafka (0.11.4)

**Closed** 2018-04-06 13:39 UTC

**Comment by wanghonglei5181** [comment] 2018-04-08 03:48
Thanks
I will have a try！！

**Comment by wanghonglei5181** [comment] 2018-04-16 01:48
I upgrade librdkafka!
in some time ,There is still have the problem! @friedl
