### ISSUE TITLE
imrelp stops receiving messages after rsyslogd receives sigHUP (i.e. logrotate)

### ISSUE THREAD

**Issue by jfwvv** [rsyslog/rsyslog#3776] opened 2019-07-30 08:56 UTC
### Expected behavior

rsyslogd with an imrelp listener should keep on listening after a sigHUP is received. (Normally sent by logrotate.)

### Actual behavior

rsyslogd with an imrelp listener stops listening after receiving a sigHUP

### Steps to reproduce the behavior

Setup test environment:
```bash
# create test setup directories
mkdir -p /tmp/rsyslog.test/conf /tmp/rsyslog.test/pid /tmp/rsyslog.test/debuglog \
        /tmp/rsyslog.test/spool/s /tmp/rsyslog.test/spool/c

# configure an rsyslogd listening for relp messages
cat > /tmp/rsyslog.test/conf/relp_server.conf <<EndOfConf
global(workDirectory="/tmp/rsyslog.test/spool/s")

module(load="imrelp" ruleset="relpIn" tls.tlslib="openssl")
module(load="mmnormalize")

input(type="imrelp" port="2514" tls="on" maxDataSize="64k")

ruleset(name="relpIn") {
        # send to file
        action(
                name="outToFile"
                type="omfile"
                file="/tmp/rsyslog.test/sink.log"
                template="RSYSLOG_DebugFormat"
        )
}
EndOfConf

# configure an rsyslogd sending relp messages (from a file)
cat > /tmp/rsyslog.test/conf/relp_client.conf <<EndOfConf
global(workDirectory="/tmp/rsyslog.test/spool/c")

module(load="imfile")
module(load="omrelp" tls.tlslib="openssl")

input(
  type="imfile"
  File="/tmp/rsyslog.test/source.log"
  Ruleset="relpOut"

  Tag="test"
  Facility="local7"
  Severity="debug"
)

ruleset(name="relpOut") {
  action(
    name="outToRelp"
    type="omrelp"
    Target="127.0.0.1"
    port="2514"
    tls="on"
    action.resumeRetryCount="-1"
    action.ResumeInterval="15"

    queue.type="LinkedList"
    queue.filename="relpsendtest"
    queue.maxdiskspace="1m"
    queue.saveonshutdown="on"
    queue.size="10"

    template="RSYSLOG_ForwardFormat"
  )
}
EndOfConf

# have some data in the source logfile
echo "Lorem ipsum dolor sit amet, consectetuer adipiscing elit." >> /tmp/rsyslog.test/source.log
```

Start the relp server:
```bash
env RSYSLOG_DEBUGLOG="/tmp/rsyslog.test/debuglog/relp_server.log" RSYSLOG_DEBUG="NoStdOut Debug" rsyslogd -f /tmp/rsyslog.test/conf/relp_server.conf -i/tmp/rsyslog.test/pid/server.pid
```
Wait for this (the server) rsyslogd to be fully started:
```txt
4728.726991941:main thread    : operatingstate.c: osf: MSG rsyslogd fully started up and initialized - begin actual processing: signaling new internal message via SIGTTOU: 'rsyslogd fully started up and initialized - begin actual processing [v8.1907.0 try https://www.rsyslog.com/e/0 ]'
```

Start the relp client:
```bash
env RSYSLOG_DEBUGLOG="/tmp/rsyslog.test/debuglog/relp_client.log" RSYSLOG_DEBUG="NoStdOut Debug" rsyslogd -f /tmp/rsyslog.test/conf/relp_client.conf -i/tmp/rsyslog.test/pid/client.pid
```
As expected the file sink.log is now created and contains the Lorem ipsum text (and related debug values).

Add a second line to source.log to show new logentries get picked up:
```bash
echo "Aenean commodo ligula eget dolor." >> /tmp/rsyslog.test/source.log
```
This text now again as expected appears in the sink.log.

Emulate a logrotate:
```bash
kill -HUP `cat /tmp/rsyslog.test/pid/server.pid`
```
In the server debuglog this shows:
```txt
5227.190116608:main thread    : rsyslogd.c: awaking mainthread on HUP
5227.190169697:main thread    : imrelp.c: imrelp: termination requested via SIGTTIN - telling RELP engine
5227.190190995:main thread    : janitor.c: janitorRun() called
5227.190218711:main thread    : iminternal.c: signaling new internal message via SIGTTOU: '[origin software="rsyslogd" swVersion="8.1907.0" x-pid="30374" x-info="https://www.rsyslog.com"] rsyslogd was HUPed'
5227.192305740:main thread    : glbl.c: GenerateLocalHostName uses 'werkpaard'
5227.192315473:main thread    : ruleset.c: iterateAllActions calling into action 0x5637f30ba890
5227.192318464:main thread    : ../action.c: Action 0x5637f30ba890 checks HUP hdlr, act level: 0x5637f1b630a0, wrkr level (nil)
5227.192322065:main thread    : strm 0x7efd900010a0: stream.c: file 5(/tmp/rsyslog.test/sink.log) closing, bDeleteOnClose 0
5227.192324636:main thread    : strm 0x7efd900010a0: stream.c: strmFlushinternal: file 5(/tmp/rsyslog.test/sink.log) flush, buflen 0 (no need to flush)
```
Add an other line to source.log to show the system is now broken:
```bash
echo "Aenean massa." >> /tmp/rsyslog.test/source.log
```
Now, against expectations, no new message appears in sink.log and the server debuglog shows:
```txt
5556.189979291:imrelp.c       : imrelp.c: librelp: done epoll_wait, nEvents:1
5556.190029134:imrelp.c       : imrelp.c: librelp: delete sock 0 from epoll set
5556.190049658:imrelp.c       : imrelp.c: librelp: delete sock 4 from epoll set
5556.190076673:imrelp.c       : ../threads.c: thrdStarter: usrThrdMain imrelp - 0x7efd9ff43700 returned with iRet 0, exiting now.
```

The smoking gun seems to be the line `5227.190169697:main thread    : imrelp.c: imrelp: termination requested via SIGTTIN - telling RELP engine`.

### Workaround
Stop and start the imrelp rsyslogd process after each logrotate.

### Environment
`Ubuntu 18.04.2 LTS` with:
```txt
rsyslog/bionic,now 8.1907.0-0adiscon1bionic1 amd64 [installed]`
rsyslog-relp/bionic,now 8.1907.0-0adiscon1bionic1 amd64 [installed]

rsyslogd  8.1907.0 (aka 2019.07) compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/rsyslogd.pid
        Number of Bits in RainerScript integers: 64
```

**Comment by rgerhards** [comment] 2019-07-30 10:24
Thx for the great bug report - I wish I had gotten it a couple of days ago ;-). Now it is a duplicate of #3760 - pls subscribe there.

**Closed by rgerhards** 2019-07-30 10:24 UTC
