### ISSUE TITLE
[8.2010.0, 8.2104.0] Rsyslog couldn't start on Debian 10

### ISSUE THREAD

**Issue by PioDer** [rsyslog/rsyslog#4576] opened 2021-04-21 08:58 UTC
Hello,
Few months ago and today I've tried install and run rsyslog from our repo:
https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog

Unfortunately, both versions 8.2010.0 and 8.2104.0 won't start properly (as systemd service).
### Actual behavior
```
● rsyslog.service - System Logging Service
   Loaded: loaded (/lib/systemd/system/rsyslog.service; enabled; vendor preset: enabled)
   Active: activating (start) since Wed 2021-04-21 08:41:18 UTC; 56s ago
     Docs: man:rsyslogd(8)
           http://www.rsyslog.com/doc/
 Main PID: 7452 (rsyslogd)
    Tasks: 10 (limit: 4915)
   Memory: 21.2M
   CGroup: /system.slice/rsyslog.service
           └─7452 /usr/sbin/rsyslogd -n

Apr 21 08:41:18 sd1.example.com systemd[1]: Starting System Logging Service...
```

and in /var/log/syslog i can see following lines:
```
Apr 21 08:50:21 sd1 rsyslogd: [origin software="rsyslogd" swVersion="8.2104.0" x-pid="11517" x-info="https://www.rsyslog.com"] start
[normal system logs - looks like rsyslog works]
```

Then it looks like rsyslog works, but systemd service state is still "activating" until timeout (90 seconds). 

Thanks for your help in advance.

**Comment by wxiaoguang** [comment] 2021-04-26 14:15
The reason is that non-debian rsyslogd doesn't use systemd's notification api (sd_notify)

But in systemd unit, it's said "Type=notify"

So all debian users must set "Type=exec" in rsyslog.service.

eg: `vim /etc/systemd/system/rsyslog.service.d/override.conf`

```
[Service]
Type=exec
```

**Comment by WISPa-Chris** [comment] 2021-05-06 06:35
Confirmed the same issue on Debian 10 and resolved by the systemd override to `Exec` in lieu of `notify`.

Thanks @wxiaoguang for the pointer.

**Comment by PioDer** [comment] 2021-05-13 12:46
> The reason is that non-debian rsyslogd doesn't use systemd's notification api (sd_notify)
> 
> But in systemd unit, it's said "Type=notify"
> 
> So all debian users must set "Type=exec" in rsyslog.service.
> 
> eg: `vim /etc/systemd/system/rsyslog.service.d/override.conf`
> 
> ```
> [Service]
> Type=exec
> ```

It works, thank you @wxiaoguang for your workaround.

**Comment by rgerhards** [comment] 2021-06-12 09:06
see https://github.com/rsyslog/rsyslog/issues/4602#issuecomment-860025065 -- as I begun work on the other tracker, I close this one here. sorry for overlooking this one.

**Closed by rgerhards** 2021-06-12 09:06 UTC
