### ISSUE TITLE
rsyslog/omkafka segfaults when communicating with Kafka cluster over longer distance

### ISSUE THREAD

**Issue by oysteila** [rsyslog/rsyslog#2067] opened 2017-11-21 09:18 UTC
I am pushing messages to a Kafka cluster in another location in this city. Normally we only do this within sites. Intermittently, rsyslog will segfault: 

```
[8902665.158154] rs:main Q:Reg[19145]: segfault at 0 ip 00007fcf30e66c20 sp 00007fcee4ff8818 error 6 in libc-2.19.so[7fcf30dcc000+1be000]
[8902665.419698] init: rsyslog main process (18123) killed by SEGV signal
[8902665.419726] init: rsyslog main process ended, respawning
```
Here is the omkafka action configuration: 

```
            action(
                name="MyLogsOmkafkaKafkaprodRemote"
                type="omkafka"
                broker=["kafka-server1-remote:9092","kafka-server2-remote:9092","kafka-server3-remote:9092","kafka-server4-remote:9092"]
                partitions.auto="on"
                topic="mytopic"
                confparam=["compression.codec=snappy", "socket.keepalive.enable=true", "queue.buffering.max.messages=200000", "queue.buffering.max.ms=1000"]
                resubmitOnFailure="on"
                template="mytemplate-json"
                action.resumeRetryCount="-1"
            )


```
Is the issue here that omkafka is not at all designed for higher-latency network links? Or is there some underlying error that could appear also in our local topologies given, for instance, increased load? 

If you need any other debug runs, but ask and I shall provide.

**Comment by rgerhards** [comment] 2017-11-21 09:59
We recently had a couple of bugfixes to omkafka. You may want to try with git master branch or the daily build packages for Ubuntu.

That said, if you can run your current version under valgrind control, I would definitely have a look at the output.

**Comment by oysteila** [comment] 2017-11-30 08:24
I managed to reproduce it on 8.30 as well. Here is a Valgrind run for you.

[rsyslog-2.log](https://github.com/rsyslog/rsyslog/files/1516992/rsyslog-2.log)

**Comment by oysteila** [comment] 2017-11-30 08:25
I'll try to reproduce on 8.31 today. Will notify here if it persists.

**Comment by rgerhards** [comment] 2017-11-30 09:11
thanks for the updated. Please also let us know if the problem is gone, else we are unsure of the actual state ;-)

**Comment by rgerhards** [comment] 2017-11-30 09:12
The valgrind log unfortunately has no symbols. Which platform is this running on? Have you built yourself or used our packages (or some others)?

**Comment by oysteila** [comment] 2017-11-30 09:25
Ah, I see. I used the standard Ubuntu 14.04 packages. I can see if I can make the time to re-compile with symbols enabled. I'll first try 8.31 now to try to reproduce.

**Comment by oysteila** [comment] 2017-12-07 11:27
8.31 unfortunately did not resolve the issues. We are preparing to run Rsyslog through Valgrind hoping to provoke segfaults like before. Currently, my configure options will give the following debug settings (tailed from ./configure - I figured the full configure options are a bit too tedious to look through):
---{ debugging support }---
    Testbench enabled:                        yes
    Extended Testbench enabled:               no
    MySQL Tests enabled:                      no
    PostgreSQL Tests enabled:                 no
    Kafka Tests enabled:                      no
    Debug mode enabled:                       yes
    Runtime Instrumentation enabled:          no
    (total) debugless mode enabled:           no
    Diagnostic tools enabled:                 no
    End-User tools enabled:                   yes
    Enhanced memory checking enabled:         yes
    Valgrind support settings enabled:        yes

Does this look like what you need? If so, I will build and try to provoke new segfaults under Valgrind. 

We also have done a little reverse engineering to analyze the binaries by looking at the crash dumps and will try to see if this gives us any new perspective on the hopefully forthcoming Valgrind output runs.

**Comment by oysteila** [comment] 2017-12-08 13:38
In setting up the test server, I just used a simple imfile input connected to an omrelp output, and was actually able to make it segfault quite quickly. The attached Valgrind Memcheck log file should provide you with more detail than the previous log. I'll produce an omkafka run more closely representing our production environment, but this is at least something for now - hopefully it's not simply due to a poorly set up rsyslog installation, since I had to build from source. 
[rsyslog-8.32-valgrind-memcheck-imfile-omrelp-segfault.log](https://github.com/rsyslog/rsyslog/files/1542765/rsyslog-8.32-valgrind-memcheck-imfile-omrelp-segfault.log)

**Comment by rgerhards** [comment] 2017-12-19 09:23
Unfortunately, debug symbols are missing. Could you please add ```-g``` to your ```CFLAGS``` and re-run?

**Comment by rgerhards** [comment] 2017-12-19 09:25
mhhh... looking twice -- might it be that the os-provided version of imfile is present in ```/usr/lib/rsyslog/imfile.so``` and not overwritten by your custom build? I ask because the rest is NOT missing symbol info, so somthing is a bit fishy here...

**Comment by rgerhards** [comment] 2017-12-21 16:44
#2184 is most likely addressing this issue here as well - so further responses are right now not needed. I'll report when a fix is available. Then we need to re-check here as well.

**Comment by rgerhards** [comment] 2017-12-21 18:21
PR #2288 matches exactly your description. So I will close this bug after it is merged. Please re-try with the new code when merged and let me know the result. If the problem persists, I can re-open.

**Closed** 2017-12-22 11:46 UTC
Labels: bug
