### ISSUE TITLE
[OMFILE][OMKAFKA]Upgrade to 8.33.1 is filling kafka topic with error logs instead of the actual logs

### ISSUE THREAD

**Issue by sharma-samta** [rsyslog/rsyslog#2544] opened 2018-03-14 15:28 UTC
I'm aggregating logs on one server and then using omkafka to send them to kafka topic on another server. I can get the server to consume the logs and save it locally in log files perfect and I could see all the logs in my kafka topic too. It was working perfect until I upgraded to 8.33.1 and i see huge number of error logs as in my kafka topic along with few correct expected syslogs :

```
4,5,Mar 14 10:55:21,LINUX1,rsyslogd:, action 'action 4' suspended (module 'builtin:omfile'), retry 0. There should be messages before this one giving the reason for suspension. [v8.33.1 try http://www.rsyslog.com/e/2007 ]
6,5,Mar 14 10:55:47,LINUX1,rsyslogd:, action 'action 3' resumed (module 'builtin:omfile') [v8.33.1 try http://www.rsyslog.com/e/2359 ]
 4,5,Mar 14 10:55:47,LINUX1,rsyslogd:, action 'action 3' suspended (module 'builtin:omfile'), retry 0. There should be messages before this one giving the reason for suspension. [v8.33.1 try http://www.rsyslog.com/e/2007 ]
```

Environment
- rsyslog version:  8.33.1 
- platform:  Ubuntu 16.04

I have my own config file in /etc/rsyslog.d named as 00-my-config.conf with another 50-default.conf and 20-ufw.conf. 

```
# provides support for local system logging
$ModLoad imuxsock 

# provides kernel logging support (previously done by rklogd)
$ModLoad imklog

# provides UDP syslog reception. For TCP, load imtcp.
$ModLoad imudp

# For TCP, InputServerRun 514
$UDPServerRun 514

# This one is the template to generate the log filename dynamically, depending on the client's IP address.
$template FILENAME,"/var/log/%fromhost-ip%/syslog.log"

# Log all messages to the dynamically formed file. Now each clients log (192.168.1.2, 192.168.1.3,etc...), will be under a separate directory which is formed by the template FILENAME.
*.* ?FILENAME

# sender
module(load="omkafka")

template(name="kafkamsg" type="string" string="%syslogpriority%,%syslogfacility%,%timegenerated%,%HOSTNAME%,%syslogtag%,%msg%") 

action(
  broker=["kafka:9092"]
  type="omkafka"
  topic="log_topic"
  partitions.auto="on"
  partitions.number="3"
  errorfile="/var/log/omkafka/rsyslog-kafka-error.json"
  resubmitOnFailure="on"
  keepFailedMessages="on"
  template="kafkamsg"
)
```
Here is the resolv.conf /  :
```

#  /etc/rsyslog.conf	Configuration file for rsyslog.
#
#			For more information see
#			/usr/share/doc/rsyslog-doc/html/rsyslog_conf.html
#
#  Default logging rules can be found in /etc/rsyslog.d/50-default.conf


#################
#### MODULES ####
#################

$ModLoad imuxsock # provides support for local system logging
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
#$ModLoad immark  # provides --MARK-- message capability

# provides UDP syslog reception
#$ModLoad imudp
#$UDPServerRun 514

# provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514


###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# Filter duplicated messages
$RepeatedMsgReduction on

#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

#
# Where to place spool files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf
```
I cant find anything meaningful in rsyslog.log except the same messages being sent to my kafka topic. 

Could you guys check if something is wrong with config or upgrading to rsyslog 8.33 broke something because it was working perfect before i upgraded. 

Thanks

**Comment by rgerhards** [comment] 2018-03-16 07:34
Well, as far as I can see, you tell rsyslog to send **all** logs to kafka and so it does. Probably 8.33 exposes an error condition that previously existed, but was ignored.

It might be useful to have a debug log, as from what you post the root cause of the error seems not to be emitted, but the debug log should tell what it is.

**Comment by alorbach** [comment] 2018-09-12 11:04
Please create full debug logging: 
https://www.rsyslog.com/doc/v8-stable/troubleshooting/debug.html#enabling-debug-via-rsyslog-conf

We will need to see what omkafka is doing in order to say more. 
You are using a single partition, could it be the partition runs full at some point?

**Comment by rgerhards** [comment] 2018-09-25 16:56
@sharma-samta do you still see the issues? If so, pls provide the info @alorbach has requested.

**Comment by alorbach** [comment] 2019-01-10 11:07
Closing Issue, response timeout.

**Closed by alorbach** 2019-01-10 11:07 UTC
Labels: question, waitingOnResponse
