### ISSUE TITLE
Fork pipe error during start up on FreeBSD

### ISSUE THREAD

**Issue by kuPyxa** [rsyslog/rsyslog#5241] opened 2023-10-13 10:45 UTC
Hi.

After updating Rsyslog to the latest version 8.2310.0 on FreeBSD, I see an error during start up:

3284.449390867:main thread    : rsyslogd.c: rsyslogd: in child, finalizing initialization
3284.449464175:main thread    : rsyslogd.c: closes unneeded files: opendir failed for /proc/self/fd
3284.449487278:main thread    : rsyslogd.c: closes unneeded files: opendir failed for /proc/fd
3284.449519181:main thread    : rsyslogd.c: rsyslogd: select() returns 1: OK
3284.449563086:main thread    : rsconf.c: telling modules to activate config (before dropping privs) 0x800e12000
3284.449571887:main thread    : rsconf.c: pre priv drop activating config 0x800e12000 for module imuxsock
3284.449584088:main thread    : imuxsock.c: imuxsock: allocating memory for 0 listeners
3284.449606490:main thread    : rsyslogd.c: rsyslog parent startup failure: error reading "fork pipe": No such file or directory
rsyslog startup failure: error reading "fork pipe": No such file or directory

Looks like it's trying to find the /proc filesystem, but FreeBSD doesn't have one :)

**Comment by Helmut1972** [comment] 2023-10-15 14:12
Similar here but with:

```
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]
Oct 15 16:00:54 BSDHelmut. rsyslogd[29360] imuxsock: recvfrom UNIX: Socket operation on non-socket [v8.2310.0]

```

eating up all memory.

**Comment by nhuff** [comment] 2023-10-21 18:20
The initial issue @kuPyxa reported appears to be caused by the introduction of the use of close_range in commit  144cc03d90293cc09c4c100dd941226b421709e2.  The child is closing the parentPipeFD file descriptor before writing the OK message to it.

**Closed** 2023-10-24 14:08 UTC
Labels: bug
