### ISSUE TITLE
rsyslog doesn't close file descriptor 

### ISSUE THREAD

**Issue by Zakaria-Baani** [rsyslog/rsyslog#5123] opened 2023-04-25 14:36 UTC
### Expected behavior
Release file descriptors once the file marked deleted
### Actual behavior
The only way to release the file descriptor is by restarting Rsyslog service. 
### Steps to reproduce the behavior
Rsyslog pod running as a daemonset on a worker node. The Rsyslog pod mount the `/var/log` directory. 
Get the rsyslog process id: `ps -ef | grep rsyslog `
Get the list of open files: `lsof -p processId | grep deleted`
The output of the last command only keeps increasing until it reaches the max file descriptors. 

### Environment
- rsyslog version: 8.2210.0
- platform: x86_64-pc-linux-gnu
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by davidelang** [comment] 2023-04-25 17:23
do you need to do a full restart? or does a HUP trigger the release?

David Lang

**Comment by Zakaria-Baani** [comment] 2023-04-25 17:46
A full restart releases the file descriptors, but I am trying to avoid it. With full restart there is a potential risk of loosing logs.

**Comment by davidelang** [comment] 2023-04-25 17:57
yes, a full restart would solve this. My question is if a HUP solves this as 
well (I believe that it should)

David Lang

**Comment by Zakaria-Baani** [comment] 2023-04-25 18:00
I have tried something like this `kill -HUP processID`, but that didn't solve the issue.

**Comment by rgerhards** [comment] 2023-04-25 18:08
HUP is sufficient.

Rainer

Sent from phone, thus brief.

David Lang ***@***.***> schrieb am Di., 25. Apr. 2023, 19:23:

**Comment by Zakaria-Baani** [comment] 2023-04-25 18:14
Probably I am using the wrong command `kill -HUP processID`. Do you mind sharing the command to send the signal to rsyslog?

**Comment by rgerhards** [comment] 2023-04-25 18:16
Command looks right, but do you have the correct MAIN process Id and permissions?

**Comment by Zakaria-Baani** [comment] 2023-04-25 18:19
I have root access and I am using the correct process id, which is 18 on my example. 
root          **18**      17  0 15:57 ?        00:00:53 rsyslogd
`kill -HUP 18`

**Comment by rgerhards** [comment] 2023-04-26 06:54
As a test, send -9 via kill instead of HUP. That should unconditionally terminate rsyslog. I suspect that the signal never arrives.

**Comment by Zakaria-Baani** [comment] 2023-04-26 12:04
That's correct. Sending -9 via kill worked. 
Is it safe to say that the only approach to release the file descriptors is by restarting Rsyslog?

**Comment by rgerhards** [comment] 2023-04-26 13:59
> Is it safe to say that the only approach to release the file descriptors is by restarting Rsyslog?

no - there must be something specific in your environment. closing on HUP is a standard feature.

Please create a debug log. Instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

Be sure that the problem in question occurs at least once during the debug run. Once this is done, please post the debug log (e.g. via pastbin or github). After that, we can review the contents and check how exactly rsyslog processing worked.

**Comment by Zakaria-Baani** [comment] 2023-04-27 14:15
How I collected the [debug](https://pastebin.pl/view/040116da) log?
I have a Rsyslog daemonset running on a worker node. I sent signal to rsyslog to collect debugging logs `kill -USR1 `cat /var/run/rsyslogd.pid``. I waited until the count of the file descriptor went up, then I sent another signal to stop debugging logs. 
Below are the results of the file descriptors count inside the worker node and rsyslog pod, respectively. 
```
ncn-w003:~ # lsof -p 1862639 | grep deleted | wc -l
3695
```
and the rsyslog container: 
```
root@rsyslog-collector:/# ls -l /proc/18/fd/ | grep deleted | wc -l
3695
```

**Comment by andrewpbarry** [comment] 2023-04-27 17:13
Some context: 
rsyslog is configured to watch pod logs with imfile. 
`input(type="imfile" File="/var/log/containers/*.log" ruleset="podlogs")`
That directory is full of symlinks to files in another directory: /var/log/pods/podnameX/podnameY/number.log
kubernetes creates one of these files in /var/log/pods for every pod that is run, and creates a link in /var/log/containers for each one. 
Rsyslog is opening a filedescriptor on the files in /var/log/containers, but not closing the fd when the file is unlinked. (the symlink is always removed when the file is unlinked.)

**Comment by andrewpbarry** [comment] 2023-05-04 13:32
Are the attached debug logs sufficient to make progress?

**Comment by Zakaria-Baani** [comment] 2023-05-10 12:57
I did run Rsyslog with [Valgrind](https://valgrind.org/), but it didn't detect any memory leaks.
Here is the command I used: 
`/usr/bin/valgrind.bin --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes --log-file=valgrind.log rsyslogd -n -f /etc/rsyslog-collector.conf`

Here is the content of the valgrind.log for more than 12hours:
```
==1== Memcheck, a memory error detector
==1== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==1== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==1== Command: rsyslogd -n -f /etc/rsyslog-collector.conf
==1== Parent PID: 0
==1==
```

**Comment by Zakaria-Baani** [comment] 2023-05-10 13:23
No problem at all. I appreciate your assistance.

**Comment by Zakaria-Baani** [comment] 2023-05-22 12:52
I am just checking for any update on this issue. I understand how busy you are and I appreciate your help so far. 
If there's anything I can do to move this issue forward, please let me know.

**Comment by rgerhards** [comment] 2023-05-24 07:35
sry, there was a misunderstanding on my part. I always assumed (somehow, don't ask me why...) the output side (omfwd). Anyhow, imfile closes the handle when it detects the input file goes away. The same is true if the name persists, but the inode changes.

I am not sure if the symlinks are the problem (and can currently not test it out). I theory, they should work OK. Can you try using a non-symlinked file to see if it works there as expected?

**Comment by rgerhards** [comment] 2023-05-24 07:36
oh, I think the debug log went away in the meantime? At least I do not see it.

**Comment by Zakaria-Baani** [comment] 2023-05-24 12:04
sorry, It seems like I did set the expiry date to either one week or a month. Here is another[ link](https://gist.github.com/Zakaria-Baani/940a02784801dc8f8bcc8afd0c572077) to the debug log in Gist. Meanwhile, I will test non-symlinked file and update you.

**Comment by rgerhards** [comment] 2023-05-24 12:13
thx - a month should have been sufficient ;-) I've downloaded the log just now and hope to be able to look into it today or tomorrow.

**Comment by Zakaria-Baani** [comment] 2023-05-24 12:14
Sounds good! Thanks

**Comment by sakateka** [comment] 2023-05-24 13:58
I go across the same issue, my env is a kubernetes cluster and rsyslog as a log collector.
Could you like to write more about your env?

My pr and detailed explanation of bug is here https://github.com/rsyslog/rsyslog/pull/5012

**Comment by rgerhards** [comment] 2023-05-25 06:36
@Zakaria-Baani I forgot: please let me know the name of a file that should have been closed. Without that, it is extremely hard to find relevant info inside the debug log. Keep in mind that I need to find debug info on why the file is not closed, so I need to see open, reads and (non-) close. If you can point me to when it should have been closed (e.g. after file xyz has been created), that would also be immensely helpful.

**Comment by rgerhards** [comment] 2023-06-06 12:40
I am back at the desk. Unfortunately, the debug log does not show a clear error indication. I see that the file is registered, but than I see no further notifications or actions.

Would it be possible for you to run rsyslog, for testing, under valgrind? Maybe this gives us some hints of what kind of problem occurs. Also, do you know if that issue only happens in container environment or also in regular VM?

**Comment by rgerhards** [comment] 2023-06-06 12:55
> I have already shared the output of Valgrind [here](https://github.com/rsyslog/rsyslog/issues/5123#issuecomment-1542164754).

sry, I overlooked that. I also seem to have overlooked #5012 which may be the root cause. I'll have a look there now.

**Comment by Zakaria-Baani** [comment] 2023-06-06 12:58
Great! Thank you @rgerhards

**Comment by sakateka** [comment] 2023-06-07 09:04
@rgerhards  For some reason, the daily build started only for the trusty, could you see why it didn't start for bionic, please?

**Comment by rgerhards** [comment] 2023-06-19 10:13
@sakateka sry for the late treply. I investigated and it looks like we provide the daily stable not for all Ubuntu versions. There are some build automation reasons.

The good news is that tomorrow will be the next scheduled stable release.

**Closed by rgerhards** 2023-06-19 10:13 UTC
Labels: bug

**Comment by Zakaria-Baani** [comment] 2023-08-23 12:47
@rgerhards I apologize for the delayed response. The proposed solution didn't resolve the issue. @sakateka could you please confirm whether it worked for you?

**Comment by sakateka** [comment] 2023-08-23 13:28
> @rgerhards I apologize for the delayed response. The proposed solution didn't resolve the issue. @sakateka could you please confirm whether it worked for you?

Yes, for the version listed below, the problem no longer occurs.
```
user@n0:~$ sudo crictl exec -it 34e78a36b6290  rsyslogd -v
rsyslogd  8.2306.0 (aka 2023.06) compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Config file:				/etc/rsyslog.conf
	PID file:				/var/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.
user@n0:~$ sudo bash inotify-consumers

   INOTIFY   INSTANCES
   WATCHES      PER
    COUNT     PROCESS   PID USER         COMMAND
------------------------------------------------------------
     880         5      272358 root        /usr/bin/kubelet --bootstrap-kubeconfig=/etc/
     129         1      977923 root        /usr/sbin/rsyslogd -n -f/configs/rsyslog.conf      <<< before the fix there were thousands of watches
...

    1156  WATCHES TOTAL COUNT

```

Maybe you have an old version of the binary running?

**Comment by Zakaria-Baani** [comment] 2023-10-12 13:26
@sakateka and @rgerhards, I recently re-tested the fix against the latest version of rsyslog. Here's the specific version I am using:
```
rsyslogd  8.2312.0.master (aka 2023.12) compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	Yes
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Config file:				/etc/rsyslog.conf
	PID file:				/var/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64
```
Setup and Procedure:

1. I executed commands inside the rsyslog pod.
2. I initiated a loop to continuously capture the file descriptors associated with the deleted files using the following command:

`while true; do ls -l /proc/18/fd | grep deleted | wc -c >> /deleted.txt ; sleep 10; done`

You can examine the content of the `deleted.txt` [here](https://gist.github.com/Zakaria-Baani/de76b4ecb2e633347481a7e040b2a848). 

Observations:

- The `deleted.txt` file showed a consistent increase in the number of file descriptors, implying that the number of file descriptors (FDs) keeps growing.
- Additionally, I compared the number FDs in the host node with the records inn `deleted.txt` from inside the rsyslog pod. They were consistent.

Given these findings, it seems that the underlying issue might still be present in the latest release. I'm happy to provide more information or collaboration on further testing if needed. 

Thank you for your attention to this bug.

**Comment by sakateka** [comment] 2023-10-12 14:40
It seems that the problem I fixed is different from yours and it is very difficult to understand why, without a detailed examination of your environment.
Can you show ls -lh/var/log/containers/* ?
And also show the names of deleted symbolic links where they are located. 
Whether the directories of deleted files have been deleted?
The minimum reproducible configuration will help a lot, for example in the tests.
The problem that I fixed, I reproduced in the test [tests/imfile-symlink-ext-tmp-dir-tree.sh](https://github.com/rsyslog/rsyslog/blob/master/tests/imfile-symlink-ext-tmp-dir-tree.sh)

**Comment by Zakaria-Baani** [comment] 2023-10-12 15:40
Thank you for your prompt response. Please find the information you requested:
1.     Output of `ls -lh /var/log/containers/*`: https://gist.github.com/Zakaria-Baani/d60d6799f8a1316075085e9b94e74047
2.     Names of Deleted Symbolic links: https://gist.github.com/Zakaria-Baani/86467d1196c3918ee355a93e9aa568e0
3.     Status of Directories of Deleted Files:
        The directories where the deleted files were located have been deleted. 
4.     The rsyslog configuration: https://gist.github.com/Zakaria-Baani/db704ecde66e292113852357f30430dd
Let me know if you need any additional information.

**Comment by andrewpbarry** [comment] 2023-10-12 16:47
My suspicion is that this is related to issues 5215, 5194, and 5176. 
I think that this is due to the active-items entry not being removed when a file is renamed in /var/log/pods/DIR/ .
Once the file is renamed, it no longer matches the symlink in /var/log/containers/LINK that points to it, thus no longer matches the wildcard string in the config file, but the active item entry does not seem to be removed. This is despite getting the inotify_moved event. I think rsyslog is getting the inotify delete event, but I'm not sure why that isn't matching the active item entry. I'm trying to put together a simplified use case to prove this out.
