### ISSUE TITLE
imfile will skip last lines in rotated file

### ISSUE THREAD

**Issue by eseres** [rsyslog/rsyslog#523] opened 2015-09-16 09:37 UTC
I have imfile configured to monitor one specific file. That file gets rotated daily. On rotation, imfile will successfully detect the newly created file each day and will start processing it from the first line in it. The problem I encounter, is that occasionally, imfile will not process the last few lines in the old, rotated file.

Here is my logrotate config:

<path to file> {
rotate 60
daily
missingok
notifempty
compress
delaycompress
nocreate
postrotate
<post rotate action to ask the application writing into the file to reopen the file>
endscript
}

And here is my rsyslog imfile config:

input(
type="imfile"
File="<path to file>"
Tag="<tag>"
Facility="user"
Severity="notice"
PersistStateInterval="1000"
ReadMode="0"
MaxSubmitAtOnce="1024"
deleteStateOnFileDelete="on"
Ruleset="<ruleset name>"
addMetadata="off"
)

The monitored file is created and written by our custom application. When logrotate rotates the file, the application is notified by logrotate as a post-rotate action. In response to that notification, the application closes the file and reopens it. That is, it is possible that the application will continue to write to the rotated file until it receives the notification and reopens the file.

As seen above, logrotate is set up to not create a new file after rotation, it is the application that will create the file after rotation.

I looked at imfile.c and see that it registers for the IN_CREATE, IN_DELETE and IN_MOVED_FROM events. With debug messages enabled and our custom app shut down, I see that the IN_CREATE event and its handling will not happen upon rotation - which is expected as the application is not running. With the application running, I do see that imfile does receive the IN_CREATE event and handles it.

What leaves me puzzled is that I know that our application won't write to the rotated file after it has closed and created a new one. From interpreting rsyslog debug output, I also understand that imfile will continue to monitor the rotated file until the IN_CREATE event has been received - at which point there should be no further lines written into the old files. I don't see the potential for a race condition here.

One other piece of information is that this will only happen if the message rate is at least a few per second. It has not happened so far at lower rates.

We have six servers running the same application but three of them are running rsyslog-relp 8.11 and three running 8.12. The error is happening only on those running rsyslog-relp 8.12.

**Comment by rgerhards** [comment] 2016-03-03 13:12
There were several fixes to imfile in the last versions. I think 8.16.0 solves this issue. If not, please re-open.

**Comment by eseres** [comment] 2016-04-08 13:32
Unfortunately, this issue has not been fixed in 8.16.0 or 8.17.0.

**Comment by eseres** [comment] 2016-04-08 13:35
I can't seem to reopen the ticket.

**Comment by mostolog** [comment] 2016-11-04 09:18
@eseres Are you able to reproduce it with latest 8.22?

**Comment by eseres** [comment] 2017-06-01 21:44
8.25 still has the same issue.

**Comment by mostolog** [comment] 2017-06-02 07:01
Are you using "readTimeout" ?

**Comment by eseres** [comment] 2017-06-02 07:01
No, I am not.

**Comment by eseres** [comment] 2017-06-16 14:50
It turns out that the issue has nothing to do with the file being rotated. Quite simply, syslog seems to not pick up the last line in a file occasionally. We did not have to rotate the file for it to happen. We would just stop writing to the file and observe how the last line never gets transmitted by rsyslog.

**Comment by rgerhards** [comment] 2017-06-16 15:29
Can you provide some samples of such lines. Most importantly, are these
complete lines, including a LF?

Thanks,
Rainer

Sent from phone, thus brief.

Am 16.06.2017 16:50 schrieb "Erik Seres" <notifications@github.com>:

**Comment by eseres** [comment] 2017-06-16 15:34
The file contains lines of the same format as shown below. And yes, they are always LF terminated, including the last one in the file.

onepcas-prod-019_1p,4256261{"t":1497594687,"w":"04faa179277291f97171e66a064a22af616b545d","r":"30e48fa5b16051db603690985d21edde9992b8cc","l":"http","m":"counter","c":1}
onepcas-prod-019_1p,4256262{"t":1497594687,"w":"7ab9950a3ea081696a32e5adb6ae1636420392ab","r":"7bf6c2d21852e600ad317c60c1be181e07eb3b24","l":"http","m":"counter","c":1}

**Comment by davidelang** [comment] 2017-06-17 02:14
is the config still the same as what's listed in the first post on this issue?

**Comment by eseres** [comment] 2017-07-12 09:19
Yes, the config file has not changed.

**Comment by rgerhards** [comment] 2017-11-26 11:05
This should be fixed by now. I don't remember the version, but I remember fixing it. If the problem still persists, let us know.

**Closed by rgerhards** 2017-11-26 11:05 UTC

**Comment by eseres** [comment] 2018-03-06 10:01
We just got around to updating rsyslog on our systems and removing the hack that was in place to work this issue around and found that the same issue is still happening.

**Comment by rgerhards** [comment] 2018-04-03 15:27
Please create a new one, this is most probably different. But be sure to confirm that the issue remains with 8.34.

**Comment by eseres** [comment] 2018-04-04 08:09
If I opened a new ticket, I could only duplicate the description as the issue is exactly the same. Would it not confuse matters?

**Comment by rgerhards** [comment] 2018-04-04 08:11
I do not see any new ticket. So let's discuss for a moment here. Did you check that 8.34.0 does not solve the issue?

**Comment by eseres** [comment] 2018-04-04 08:15
No, we are running 8.33 still but I'm about to update to 8.34 as you suggested, run it for a few days to see if the error still happens and then report back here.

**Comment by csrl** [comment] 2018-06-28 14:37
@rgerhards we are trying to identify changed behavior since the 8.34 rewrite, and would like to be able to go back to old versions, but we're having trouble tracking down .deb packages for specifically 8.33.1-0adiscon2trusty1.  Are those available somewhere?  Or do we have to build from source?
