### ISSUE TITLE
imjournal reloading repeatedly on older CentOS 7.x

### ISSUE THREAD

**Issue by jfield** [rsyslog/rsyslog#2931] opened 2018-08-15 00:51 UTC
### Expected behavior
imjournal to reload once per roll

### Actual behavior
imjournal reloading a lot more than once per roll

### Steps to reproduce the behavior
Use imjournal on our 200+ log line per second hosts.
And use a version of CentOS that is no longer current.

I'm mostly documenting this in case someone else runs into it, or in case someone wants to fix it for 7.3.1611 (but really, people should just not run 7.3.1611 anymore!). We're downgrading to 8.36.0-3 and then rolling 8.37+ back out after we upgrade the OS.

### Environment
- rsyslog version: 8.37
- platform: CentOS 7.3.1611

On some higher logging volume 7.3.1611 hosts, we're currently getting spammed with:
```
Aug 14 23:34:03 our-awesome-hostname0000 rsyslogd[25787]: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
Aug 14 23:34:03 our-awesome-hostname0000 rsyslogd[25787]: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
Aug 14 23:34:03 our-awesome-hostname0000 rsyslogd[25787]: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
Aug 14 23:34:03 our-awesome-hostname0000 rsyslogd[25787]: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
Aug 14 23:34:03 our-awesome-hostname0000 rsyslogd[25787]: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
Aug 14 23:34:03 our-awesome-hostname0000 rsyslogd[25787]: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
Aug 14 23:34:03 our-awesome-hostname0000 rsyslogd[25787]: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
Aug 14 23:34:03 our-awesome-hostname0000 rsyslogd[25787]: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
Aug 14 23:34:03 our-awesome-hostname0000 rsyslogd[25787]: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
Aug 14 23:34:03 our-awesome-hostname0000 rsyslogd[25787]: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
```

For reference, the host above is doing about 280 log lines per second through journald. This was no problem on 8.36.0-3, which we've rolled back to. 

I tried rsyslog debug logging for a 30 second window and this is what came out in relation to imjournal:
```
7651.143667849:imjournal.c    : iminternal.c: signaling new internal message via SIGTTOU: 'imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]'
7651.143737389:imjournal.c    : main Q: queue.c: qqueueAdd: entry added, size now log 1, phys 1 entries
7651.143747282:imjournal.c    : main Q: queue.c: EnqueueMsg advised worker start
7651.143751216:imjournal.c    : ratelimit.c: RRRRR: ratelimitAddMsg returns 0
7651.143817775:main Q:Reg/w0  : ruleset.c: processBATCH: next msg 0: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
7651.145372695:imjournal.c    : errmsg.c: Called LogMsg, msg: imjournal: journal reloaded...
7651.145388042:imjournal.c    : iminternal.c: signaling new internal message via SIGTTOU: 'imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]'
7651.145457017:imjournal.c    : main Q: queue.c: qqueueAdd: entry added, size now log 1, phys 1 entries
7651.145483490:imjournal.c    : main Q: queue.c: EnqueueMsg advised worker start
7651.145494030:imjournal.c    : ratelimit.c: RRRRR: ratelimitAddMsg returns 0
7651.145565243:main Q:Reg/w0  : ruleset.c: processBATCH: next msg 0: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
7651.147369101:imjournal.c    : errmsg.c: Called LogMsg, msg: imjournal: journal reloaded...
7651.147389489:imjournal.c    : iminternal.c: signaling new internal message via SIGTTOU: 'imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]'
7651.147484356:imjournal.c    : main Q: queue.c: qqueueAdd: entry added, size now log 1, phys 1 entries
7651.147499077:imjournal.c    : main Q: queue.c: EnqueueMsg advised worker start
7651.147515164:imjournal.c    : ratelimit.c: RRRRR: ratelimitAddMsg returns 0
7651.147718735:main Q:Reg/w0  : ruleset.c: processBATCH: next msg 0: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
7651.149373398:imjournal.c    : errmsg.c: Called LogMsg, msg: imjournal: journal reloaded...
7651.149388685:imjournal.c    : iminternal.c: signaling new internal message via SIGTTOU: 'imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]'
7651.149454021:imjournal.c    : main Q: queue.c: qqueueAdd: entry added, size now log 1, phys 1 entries
7651.149479014:imjournal.c    : main Q: queue.c: EnqueueMsg advised worker start
7651.149490220:imjournal.c    : ratelimit.c: RRRRR: ratelimitAddMsg returns 0
7651.150536169:main Q:Reg/w0  : ruleset.c: processBATCH: next msg 0: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
7651.152173382:imjournal.c    : errmsg.c: Called LogMsg, msg: imjournal: journal reloaded...
7651.152193281:imjournal.c    : iminternal.c: signaling new internal message via SIGTTOU: 'imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]'
7651.152259022:imjournal.c    : main Q: queue.c: qqueueAdd: entry added, size now log 1, phys 1 entries
7651.152269465:imjournal.c    : main Q: queue.c: EnqueueMsg advised worker start
7651.152272954:imjournal.c    : ratelimit.c: RRRRR: ratelimitAddMsg returns 0
7651.152343424:main Q:Reg/w0  : ruleset.c: processBATCH: next msg 0: imjournal: journal reloaded... [v8.37.0 try http://www.rsyslog.com/e/0 ]
7651.155033297:main thread    : ../threads.c: request term via SIGTTIN for input thread 'imjournal' 0x7fc939f41700
7651.155037230:main thread    : ../threads.c: thread imjournal: initiating termination, timeout 1000 ms
7651.155901413:imjournal.c    : errmsg.c: Called LogMsg, msg: imjournal: journal reloaded...
```

If the full log would be useful, I can scrub them and submit them somewhere - we can also reproduce it on demand by upgrading a host to 8.37.0. We got this behavior both with and without the new WorkAroundJournalBug setting.

**Comment by rgerhards** [comment] 2018-08-15 06:34
@jvymazal @richm any idea of what we broke with the recent changes? Any way other than full revert to make it work with older journal again?

**Comment by jvymazal** [comment] 2018-08-15 07:02
@jfield just for reference which version of journald do you have there?

**Comment by jvymazal** [comment] 2018-08-15 07:15
@rgerhards I don't think revert will be necessary, depending on journal version which causes this, it should be possible to do some non-invasive change to keep the reloading frequency at acceptable level

**Comment by jvymazal** [comment] 2018-08-15 07:25
Well, considering amount of work we had last time with journal enabled-CI I did not think you want more of those in your worker setup, however if you do want to go that way, depending on how we resolve this, we can make some addition.

I would strongly prefer fix without `if(journal_version...) { ` switch, but if APIs in question behave in really conflicting way it might end that way.

**Comment by rgerhards** [comment] 2018-08-15 11:02
> Well, considering amount of work we had last time with journal enabled-CI I did not think you want more of those in your worker setup, however if you do want to go that way, depending on how we resolve this, we can make some addition.

my point is that we should try to test during CI what we **commonly** find. I don't know how strange a system with that journal issue can be found. It if is exotic, there is no good reason to create an extra CI system for it. But if it is kind of commonplace, we should do it. It's of course inconvenient, but it's more inconvenient to see users hitting the problem.

**Comment by duylong** [comment] 2018-08-17 08:54
Same problem since update to 8.37 on RHEL7. No problem with rsyslog 8.35.

systemd version: systemd-219-19.el7_2.7.x86_64

**Comment by rgerhards** [comment] 2018-08-17 09:09
This seems to be a regression in the new imjournal code introduced in v8.37. We will see that we fix it in 8.38.

**Comment by rgerhards** [comment] 2018-08-17 09:12
@jvymazal it looks like the business of the journal seems to be a triggering condition. Probably hard to craft a test for, but would you like to give it a try?

**Comment by jvymazal** [comment] 2018-08-17 09:29
@rgerhards I am in contact with systemd guys to investigate, say, _variable_ behavior of `SD_JOURNAL_INVALIDATE` retcode, will submit a PR once I get to the root of this, the test will very much depend on nature of the fix.

**Comment by rgerhards** [comment] 2018-08-20 10:54
here is another incarnation from yesterday: https://build.rsyslog.com/#/builders/175/builds/160/steps/6/logs/test-suite_log (from PR https://github.com/rsyslog/rsyslog/pull/2946)

**Comment by rgerhards** [comment] 2018-08-29 11:09
@jvymazal  The journal test failure is actually around 30%-40% of the time. I'll see that I disable it inside CI. While we got some extra CI instablity due to my recent changes, I think the majority of false positives is related to imjournal. I'll still see to keep it active in the daily builds.

Once things settles - or it's not as bad as I thought - we can re-enable.

**Comment by rgerhards** [comment] 2018-09-26 21:17
@jvymazal  I think I have an idea how I can work around the Journal Test failure, I'll try that soon. Do you got any info on the original posting? Or should we revert to old state?

**Comment by rgerhards** [comment] 2018-10-26 06:44
idea did not work out (it was to check via regular tools, but that's already present)

@jvymazal any news? I consider reverting the last patch...

**Comment by jvymazal** [comment] 2018-10-26 12:58
@rgerhards sorry for not being here sooner, got some other things to do...

I have originally investigated some option of detecting this at build-time and switching to another (possibly even previous code style) handling of journal ret-codes. However given that we are now talking patch-level version this approach os not really feasible. So I just tried to craft some detect-prevent mechanism for this, PR following in few minutes.

**Comment by jvymazal** [comment] 2018-10-26 13:11
@jfield if the issue is still relevant for you, you can use [this](https://koji.fedoraproject.org/koji/taskinfo?taskID=30473146) experimental build with #3192 applied to 8.38.0 fedora rsyslog to test if it works for you (it worked for me on 7.3 test box).

**Comment by jvymazal** [comment] 2018-10-29 13:45
@rgerhards do we want to close this now or leave it open till 8.39 release / some other verification?

**Comment by rgerhards** [comment] 2018-10-29 16:13
I think we can close - and re-open if necessary. btw: 8.39 will be released tomorrow. Just crafted the tarball.

**Closed by rgerhards** 2018-10-29 16:13 UTC
Labels: bug
