### ISSUE TITLE
"bad file descriptor" errors using omprog with rsyslogd in daemon mode

### ISSUE THREAD

**Issue by ddresser** [rsyslog/rsyslog#4247] opened 2020-04-15 03:37 UTC
### Expected behavior
rsyslogd starts in daemon mode without errors and passes log messages to my program via omprog plugin

### Actual behavior
When run in daemon mode, I see "bad file descriptor" errors and my program is not started successfully.

apr 14 23:07:38.968884 RSYSLO  omprog: error sending message to program: Bad file descriptor [v8.2002.0 try https://www.rsyslog.com/e/2119 ] 
apr 14 23:07:38.968978 RSYSLO  action 'action-1-omprog' suspended (module 'omprog'), retry 0. There should be messages before this one giving the reason for suspension. [v8.2002.0 try https://www.rsyslog.com/e/2007 ] 
apr 14 23:07:39.970158 RSYSLO  action 'action-1-omprog' resumed (module 'omprog') [v8.2002.0 try https://www.rsyslog.com/e/2359 ] 
apr 14 23:07:39.970283 RSYSLO  omprog: error sending message to program: Bad file descriptor [v8.2002.0 try https://www.rsyslog.com/e/2119 ] 
apr 14 23:07:39.970364 RSYSLO  action 'action-1-omprog' suspended (module 'omprog'), retry 0. There should be messages before this one giving the reason for suspension. [v8.2002.0 try https://www.rsyslog.com/e/2007 ] 

If I run rsyslogd in the foreground `rsyslogd -n`,  I don't get the errors and messages are passed to my program as expected.

These errors also go away if I set `forceSingleInstance="off"`

### Steps to reproduce the behavior
1 - configure omprog
module(load="omprog")
action(type="omprog"
           binary="/usr/bin/logoutput"
           forceSingleInstance="on"
           template="output")

2 - start rsyslogd as a daemon
`rsyslogd` on the command line, or
/etc/init.d/syslog start

### Environment
root@zcu102-zynqmp:~# rsyslogd -v
rsyslogd  8.2002.0 (aka 2020.02) compiled with:
	PLATFORM:				aarch64-oe-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	No
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			No
	Config file:				/etc/rsyslog.conf
	PID file:				/var/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64

[syslog_debug.log.txt](https://github.com/rsyslog/rsyslog/files/4479011/syslog_debug.log.txt)
[rsyslog.conf.txt](https://github.com/rsyslog/rsyslog/files/4479009/rsyslog.conf.txt)

**Comment by jsiwrk** [comment] 2020-04-17 20:16
Marking tentatively as a bug.

I think I could have introduced this bug in v8.38, via PR #3009. This PR indeed corrected the behaviour of the forceSingleInstance flag, but it also changed the moment when the external program is started (when this flag is enabled). When forceSingleInstance=on, the external program is started when rsyslog is started (in the `newActInst` module entrypoint), instead when the first message is received. Maybe this interferes with the handling of the pipe file descriptors when rsyslog is started in daemon mode (?). This problem could easily go unnoticed while developing the PR since the tests always run in non-daemon mode.

In the meantime, as a workaround, I suggest disabling this flag. Rsyslog should still launch a single instance of the external program provided that a single [worker thread](https://www.rsyslog.com/doc/v8-stable/rainerscript/queue_parameters.html#queue-workerthreads) is used for the omprog action, and a disk-assisted queue is not used.

**Comment by jsiwrk** [comment] 2020-04-17 20:17
This could be the same problem reported by @jpastuszek in [this comment](https://github.com/rsyslog/rsyslog/issues/3361#issuecomment-481631043).

**Comment by jsiwrk** [comment] 2020-04-19 20:17
I confirm it is a bug in omprog. I have also reproduced it in my environment. By analyzing the debug log and what rsyslog does during startup (something I had never delved into) I have easily spotted the cause. The problem seems to affect not only the `forceSingleInstance` flag but also the `output` setting.

When the `forceSingleInstance` flag is enabled, omprog [starts the external program](https://github.com/rsyslog/rsyslog/blob/v8.2002.0/plugins/omprog/omprog.c#L827-L856) in the [newActInst](https://github.com/rsyslog/rsyslog/blob/v8.2002.0/plugins/omprog/omprog.c#L1102) module entrypoint. Also, if the `output` setting has been specified, the output capture thread is also started at this point. This entrypoint is invoked when rsyslog is [loading/parsing the configuration](https://github.com/rsyslog/rsyslog/blob/v8.2002.0/tools/rsyslogd.c#L1547), which happens to be a very early phase. In fact, at this point the configuration has not even been fully validated or [activated](https://github.com/rsyslog/rsyslog/blob/v8.2002.0/tools/rsyslogd.c#L1629). The simple fact that omprog starts doing things (opening pipes) while the configuration is still being parsed already seems a very bad idea.

When things go really bad is when rsyslog is started in daemon mode (the default). In this mode, after the configuration has been loaded and validated, the parent process [forks](https://github.com/rsyslog/rsyslog/blob/v8.2002.0/tools/rsyslogd.c#L1605) itself to create the background (daemon) process. This involves [closing the file descriptors](https://github.com/rsyslog/rsyslog/blob/v8.2002.0/tools/rsyslogd.c#L386-L393) that the daemon does not (in theory) need, starting with [fd number 3](https://github.com/rsyslog/rsyslog/blob/v8.2002.0/tools/rsyslogd.c#L361). This includes the fds previously opened by omprog (the pipes with the external program, and the pipe used by the output capture thread). Later, this causes omprog to use fds that are no longer valid (hence the "bad file descriptor" error), or (worse) that have been reassigned (thus sometimes producing [other error codes](https://github.com/rsyslog/rsyslog/issues/3361#issuecomment-484968370)).

This problem was not detected by the omprog tests since the testbench always runs rsyslog in non-daemon mode (by design I think).

To fix this bug, I will move [this omprog code](https://github.com/rsyslog/rsyslog/blob/v8.2002.0/plugins/omprog/omprog.c#L842-L851) to an entrypoint invoked later during the startup sequence. The `activateCnf` entrypoint seems a good candidate since it is [invoked](https://github.com/rsyslog/rsyslog/blob/v8.2002.0/tools/rsyslogd.c#L1629) after the fork.

**Comment by jsiwrk** [comment] 2020-04-19 20:19
I will try to submit a corrective PR soon. @rgerhards, when is the next release planned?

**Comment by davidelang** [comment] 2020-04-19 20:36
I believe that the next release would normally happen this tuesday, but due to 
the Wu Flu and the fact that Rainer is involved with dealing with it, the 
website indicates that this release may be delayed into early May.

David Lang

  On Sun, 19 
Apr 2020, Joan Sala Isern wrote:

> Date: Sun, 19 Apr 2020 13:19:46 -0700
> From: Joan Sala Isern <notifications@github.com>
> Reply-To: rsyslog/rsyslog
>     <reply@reply.github.com>
> To: rsyslog/rsyslog <rsyslog@noreply.github.com>
> Cc: Subscribed <subscribed@noreply.github.com>
> Subject: Re: [rsyslog/rsyslog] "bad file descriptor" errors using omprog with
>     rsyslogd in daemon mode (#4247)
> 
> I will try to submit a corrective PR soon. @rgerhards, when is the next release planned?
>
>

**Comment by rgerhards** [comment] 2020-04-20 07:29
As David said, SARS-CoV-2 (Corona) has shaken the schedule a bit. My
current line of thinking is that we will most probably release April, 28th.
This would enable us to preserve 8.2004 version and also avoid a time frame
where people are more busy. Originally, the release was planned Tuesday
before easter, which was definitely not a good time spot.

Raienr

**Closed** 2020-04-28 08:30 UTC
Labels: bug
