### ISSUE TITLE
warnings when forwarding logs to Elastic Search 5

### ISSUE THREAD

**Issue by jostyee** [rsyslog/rsyslog#1642] opened 2017-07-02 08:38 UTC
`rsyslogd 8.27.0/elasticsearch 5.4.2`

my rsyslog.conf snippet as below:
```
# parse json log
*.*    :mmjsonparse:

if ($parsesuccess == "OK") then {
    action(type="mmutf8fix")
    action(type="omelasticsearch"
        template="cee-log"
        server="elasticsearch_server"
        searchIndex="logstash-index"
        dynSearchIndex="on"
        bulkmode="on"
        queue.dequeuebatchsize="100"
        action.resumeretrycount="-1"
        errorfile="/var/log/omelasticsearch.log")
}
```

get warning logs when elasticsearch receives requests:

```log
[2017-07-02T07:46:04,937][WARN ][org.elasticsearch.deprecation.rest.action.admin.indices.RestTypesExistsAction] [HEAD /{index}/{type}] is deprecated! Use [HEAD /{index}/_mapping/{type}] instead.
[2017-07-02T07:46:04,939][WARN ][org.elasticsearch.deprecation.rest.RestController] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.
```

seems es has changed their APis but rsyslog still using the deprecated ones.

**Comment by rgerhards** [comment] 2017-07-02 08:39
duplicate of https://github.com/rsyslog/rsyslog/issues/1546

**Comment by jostyee** [comment] 2017-07-02 08:41
@rgerhards thanks for your QUICK reply, close this now.

**Comment by jostyee** [comment] 2017-07-02 12:59
@rgerhards I'm sorry, #1546 issued the `[HEAD /{index}/_mapping/{type}]` API change, but there is another `[Content-Type]` warning, I'm going to reopen this one.

**Comment by rgerhards** [comment] 2017-07-05 08:35
I see, it just looked similar. Looks like ES is having a pretty unstable API. Do you have a link to doc where the changes can be seen (and ideally how to best query the feature set)?

**Comment by jostyee** [comment] 2017-07-05 09:29
@rgerhards It's been change since 5.3: https://www.elastic.co/guide/en/elasticsearch/reference/5.3/docs-bulk.html

> When sending requests to this endpoint the Content-Type header should be set to application/x-ndjson.

**Comment by jimmypw** [comment] 2017-07-13 15:52
I have just encountered this issue, I believe the fix is simply to change the content type of the requests from text/json to application/json. I have made the change locally, I will test tonight.

**Comment by wdauchy** [comment] 2017-07-26 23:32
I've sent a proposal patch in #1698

**Closed** 2017-08-03 08:44 UTC

**Comment by jostyee** [comment] 2017-08-22 07:09
@wdauchy @rgerhards weird after I upgraded to 8.29.0 the warning messages still keep showing up.

```
[2017-08-22T15:04:27,872][WARN ][org.elasticsearch.deprecation.rest.RestController] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.
[2017-08-22T15:04:27,873][WARN ][org.elasticsearch.deprecation.rest.RestController] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.
[2017-08-22T15:04:27,881][WARN ][org.elasticsearch.deprecation.rest.RestController] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.
...
```

**Comment by mrgleeco** [comment] 2017-08-22 16:13
also confirming- i had the latest & was still seeing the warnings as of last week.

**Comment by wdauchy** [comment] 2017-08-23 18:57
weird, I will have a second look

**Comment by wdauchy** [comment] 2017-08-30 13:47
true it does not work as expected in bulk mode; I will fix that

**Comment by wdauchy** [comment] 2017-08-30 14:45
I created a new pull request #1743

sorry for the inconvenience
