### ISSUE TITLE
Segfault when attempting to run without hostname set

### ISSUE THREAD

**Issue by erikpotterbsx** [rsyslog/rsyslog#1040] opened 2016-05-18 00:27 UTC
This has caught me unawares twice now. Normally I'd have a hostname set but I'm running on a VM and keep forgetting that the image didn't have a hostname set when I snapshotted it.

Running rsyslogd on a machine without its hostname set would segfault with a strange error:
`error reading "fork pipe": No such process`

output of rsyslogd -v:

```
rsyslogd 8.11.0, compiled with:
PLATFORM:                               amd64-portbld-freebsd10.3
PLATFORM (lsb_release -d):
FEATURE_REGEXP:                         Yes
GSSAPI Kerberos 5 support:              No
FEATURE_DEBUG (debug build, slow code): No
32bit Atomic operations supported:      Yes
64bit Atomic operations supported:      Yes
memory allocator:                       system default
 Runtime Instrumentation (slow code):    No
uuid support:                           Yes
Number of Bits in RainerScript integers: 64
```

**Comment by mostolog** [comment] 2016-10-26 07:32
@rgerhards duplicate of #335 ?

**Comment by rgerhards** [comment] 2016-10-26 10:11
@mostolog yup, sounds much so. Could you try to reproduce this?

**Comment by mostolog** [comment] 2016-10-26 12:58
TBH, I don't know how @erikpotterbsx achieved "not having a hostname".

Perhaps deleting /etc/hostname? Maybe deleting /etc/hosts? Perhaps unsetting an environment variable?
If you know the way, just let me know. Otherwise, I'll wait for @erikpotterbsx or a pal telling me how to do it.

**Comment by rgerhards** [comment] 2016-10-26 13:53
@mostolog TBH, that's a very good point. I can only guess either ;-)

**Comment by erikpotterbsx** [comment] 2016-10-26 15:35
It looks like the absence of a `hostname='myhostname'` line in rc.conf will cause the problem. Without such a line, the result of running `/bin/hostname` returns an empty string: ''

`hostname | hexdump`

0000000 000a
0000001

Anyway, to create this environment, just:
`vagrant init freebsd/FreeBSD-10.3-RELEASE`
`vagrant up`

**Comment by rgerhards** [comment] 2016-10-27 07:02
Thanks for the info. With that, I think I can "reproduce" the issue simply by filling the hostname buffer by an empty string except the actual gethostname() API. Then it crashes as well. I'll look at a fix, it would be good if you, @erikpotterbsx , could try it out when it is done.

**Closed** 2016-11-03 11:00 UTC
Labels: bug
