### ISSUE TITLE
Calling rulesets on configuration with lookup_table and no active actions crashes

### ISSUE THREAD

**Issue by StrongestNumber9** [rsyslog/rsyslog#2399] opened 2018-01-16 15:06 UTC
### Expected behavior
Works normally, receives data and runs it through the configuration.

### Actual behavior
Aborted (core dumped) or Segmentation fault (core dumped)

### Steps to reproduce the behavior (Case 1)
By including lookup_table from short path (less than 3 /'s) and calling non existing ruleset, it crashes and leaks memory:

>$LocalHostName collector
> $PreserveFQDN on
> main_queue(queue.type="Direct")
> module(load="imrelp")
> input(type="imrelp" port="601" MaxDataSize="128k")
> lookup_table(name="dummy" file="/dummy.json" reloadOnHup="on")
> call doesnt_exist

Result
>3303.974068725:imrelp.c       : rainerscript.c:     CALL [doesnt_exist, queue:1]
>3303.974083910:imrelp.c       : ruleset.c: CALL: forwarding message to async ruleset 0x736574222c227461
>3303.974090637:imrelp.c       : ruleset.c: ruleset.c:733 ISOBJ assert failure: invalid object type, expected 'ruleset' actual '@▒$▒', cookie: 2D70756F
>ruleset.c:733 ISOBJ assert failure: invalid object type, expected 'ruleset' actual '@▒$▒', cookie: 2D70756F
>rsyslogd: ruleset.c:733: GetRulesetQueue: Assertion `!strcmp((char*)(((obj_t*)pThis)->pObjInfo->pszID), "ruleset")' failed.
>Aborted (core dumped)

### Steps to reproduce the behavior (Case 2)
Including lookup_table on path with more than than 3x / 
>$LocalHostName collector
>$PreserveFQDN on
>main_queue(queue.type="Direct")
>module(load="imrelp")
>input(type="imrelp" port="601" MaxDataSize="128k")
>lookup_table(name="dummy" file="/opt/Fail-Safe/rsyslog/etc/rsyslog.d/dummy.json" reloadOnHup="on")
>call doesnt_exist

Result
>3353.773117034:imrelp.c       : rainerscript.c:     CALL [doesnt_exist, queue:1]
>3353.773131715:imrelp.c       : ruleset.c: CALL: forwarding message to async ruleset (nil)
>Segmentation fault (core dumped)

### Steps to reproduce the behavior (Case 3)
With known rulesets, same happens but have to call it multiple times. This time no memory leak
>$LocalHostName collector
>$PreserveFQDN on
>main_queue(queue.type="Direct")
>module(load="imrelp")
>input(type="imrelp" port="601" MaxDataSize="128k")
>lookup_table(name="dummy" file="/dummy.json" reloadOnHup="on")
>ruleset(name="test") { }
>call test
>call test

Result:
>4643.094900002:imrelp.c       : rainerscript.c:     CALL [test, queue:0]
>4643.094912058:imrelp.c       : rainerscript.c:     CALL [test, queue:1]
>Segmentation fault (core dumped)

### Notes
The configurations are not clean; it will whine about "rsyslogd: CONFIG ERROR: there are no active actions configured. Inputs will run, but no output whatsoever is created.".

Removing either the lookup_table part or adding any action will fix it.

dummy.json must have 1 or more objects inside it, with empty table it will not crash.

### dummy.json
>{
>  "version": 1,
>  "nomatch": "unknown",
>  "type": "string",
>  "table": [
>    {
>      "index": "index",
>      "value": "value"
>    }
>  ]
>}

### Environment
> rsyslogd 8.32.0, compiled with:
> PLATFORM:                               x86_64-pc-linux-gnu
> PLATFORM (lsb_release -d):
> FEATURE_REGEXP:                         Yes
> GSSAPI Kerberos 5 support:              No
> FEATURE_DEBUG (debug build, slow code): Yes
> 32bit Atomic operations supported:      Yes
> 64bit Atomic operations supported:      Yes
> memory allocator:                       system default
> Runtime Instrumentation (slow code):    No
> uuid support:                           Yes
> systemd support:                        No
> Number of Bits in RainerScript integers: 64

> Linux 52cac608f63a 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

> Fedora release 27 (Twenty Seven)

*Note: rsyslog documentation is available here*:
  [pre-release](http://www.rsyslog.com/doc/master/),
  [current stable release](http://www.rsyslog.com/doc/v8-stable/)

**Comment by rgerhards** [comment] 2018-01-17 07:58
Thanks for the bug report. I'll take care of it ASAP, but am currently pretty busy. Bear with me if it takes a couple of days.

**Comment by rgerhards** [comment] 2018-01-19 10:17
I can unfortunately not reproduce this in my lab. All I get is the correct message that the ruleset does not exists. Can you run the test under valgrind in your lab? It's simple:
```
$ valgrind rsyslogd ...regular options...
```
Also, access to the full debug log (github gist?) would be useful.

**Comment by StrongestNumber9** [comment] 2018-01-19 12:37
I am so sorry for not including a note about it having to receive a message in order to crash. Tested with only imrelp this far.

Here is valgrind for case 1 configuration using command `valgrind /opt/Fail-Safe/rsyslog/rsyslog/sbin/rsyslogd -f /opt/Fail-Safe/rsyslog/etc/rsyslog.conf -dn`
https://gist.github.com/anonymous/bbb69870fb14b620a65377c643705853

And snippet with -n only, doesn't seem to crash when using valgrind.
>rsyslogd: CONFIG ERROR: there are no active actions configured. Inputs will run, but no output whatsoever is created. [v8.32.0 try http://www.rsyslog.com/e/2103 ]
>--204-- REDIR: 0x696fd50 (libc.so.6:__strncpy_sse2_unaligned) redirected to 0x4c33170 (__strncpy_sse2_unaligned)
>--204-- Reading syms from /usr/lib64/libnss_dns-2.26.so
>==204== Thread 3 in:imrelp:
>==204== Conditional jump or move depends on uninitialised value(s)
>==204==    at 0x18AD8B: execCall (ruleset.c:288)
>==204==    by 0x18BB52: scriptExec (ruleset.c:606)
>==204==    by 0x18BD9D: processBatch (ruleset.c:658)
>==204==    by 0x11E1CB: msgConsumer (rsyslogd.c:709)
>==204==    by 0x18296E: qAddDirectWithWti (queue.c:1040)
>==204==    by 0x1829C9: qAddDirect (queue.c:1058)
>==204==    by 0x182A73: qqueueAdd (queue.c:1090)
>==204==    by 0x188A46: doEnqSingleObj (queue.c:2941)
>==204==    by 0x188FF4: qqueueEnqMsg (queue.c:3042)
>==204==    by 0x11F16C: submitMsg2 (rsyslogd.c:1015)
>==204==    by 0xC4D6180: onSyslogRcv (imrelp.c:248)
>==204==    by 0x590829C: relpSCSyslog (scsyslog.c:56)
>==204==
>==204== Conditional jump or move depends on uninitialised value(s)
>==204==    at 0x18BC90: scriptExec (ruleset.c:581)
>==204==    by 0x18ADA7: execCall (ruleset.c:289)
>==204==    by 0x18BB52: scriptExec (ruleset.c:606)
>==204==    by 0x18BD9D: processBatch (ruleset.c:658)
>==204==    by 0x11E1CB: msgConsumer (rsyslogd.c:709)
>==204==    by 0x18296E: qAddDirectWithWti (queue.c:1040)
>==204==    by 0x1829C9: qAddDirect (queue.c:1058)
>==204==    by 0x182A73: qqueueAdd (queue.c:1090)
>==204==    by 0x188A46: doEnqSingleObj (queue.c:2941)
>==204==    by 0x188FF4: qqueueEnqMsg (queue.c:3042)
>==204==    by 0x11F16C: submitMsg2 (rsyslogd.c:1015)
>==204==    by 0xC4D6180: onSyslogRcv (imrelp.c:248)
>==204==

**Comment by rgerhards** [comment] 2018-01-19 13:00
thx, this looks useful!

**Comment by rgerhards** [comment] 2018-01-19 13:01
I should add that I also sent messages to it (using standard testbench tooling). I still was not able to reproduce.

**Comment by StrongestNumber9** [comment] 2018-01-19 13:31
Seems like docker-compose wants to put underscore in network name, making it non-compliant with most of the RFCs. Will update testing environment and see if fixing it to valid hostname/network has any change.

>4801.939119434:imrelp.c : imrelp.c: remote host is 'perftest_logcreator.perftest_rsyslog-perftest', ip '192.168.10.103'

**Comment by rgerhards** [comment] 2018-01-19 13:34
do you have a docker container you could share?

**Comment by StrongestNumber9** [comment] 2018-01-19 14:09
I can share the containers if this still can be reproduced once I have updated the testing environment and checked that it is not caused by mistake on our end.

**Comment by StrongestNumber9** [comment] 2018-01-29 12:21
I can still reproduce the problem and I made special docker container that has configurations for all the three cases, automatically starts with case 1. 

> \# docker-compose build && docker-compose up
<snip..>
Successfully built 515b6dfd4551
Successfully tagged crashtest_collector:latest
Creating network "crashtest_default" with the default driver
Creating crashtest-collector ...
Creating crashtest-collector ... done
Attaching to crashtest-collector
crashtest-collector | Starting rsyslog collector
crashtest-collector | rsyslogd: CONFIG ERROR: there are no active actions configured. Inputs will run, but no output whatsoever is created. [v8.32.0 try http://www.rsyslog.com/e/2103 ]
crashtest-collector | starting run 1
crashtest-collector | Sending 1 messages.
00000001 messages sent
crashtest-collector | ruleset.c:733 ISOBJ assert failure: invalid object type, expected 'ruleset' actual 'B\`�', cookie: BB604C00
crashtest-collector | rsyslogd: ruleset.c:733: GetRulesetQueue: Assertion `!strcmp((char*)(((obj_t*)pThis)->pObjInfo->pszID), "ruleset")' failed.
crashtest-collector | runtime: 0.013
crashtest-collector | End of tcpflood Run
crashtest-collector | Sleeping for debugging purposes..

Preferably not sharing the containers publicly, how should we deliver Dockerfiles and/or built image so everyone involved stays up-to-date?
Pinging @kortemik ^

**Comment by StrongestNumber9** [comment] 2018-01-29 13:35
https://gist.github.com/StrongestNumber9/322ec6a3324e6d80b2bb57a53b97b7be
gdb bt full output

**Comment by kortemik** [comment] 2018-02-13 14:19
@rgerhards we can arrange access to our dev systems so it's easy to reproduce.

**Comment by rgerhards** [comment] 2018-02-14 16:13
I am on the road right now. Hadn't seen the github issue as I was working on other stuff. Will try to sneak this in, but I will also ask @alorbach as I am most probably away full next week.

**Comment by rgerhards** [comment] 2018-02-14 16:22
@StrongestNumber9 @kortemik would it be possible to mail me privately the Dockerfile and what else is needed to build the container?

**Comment by alorbach** [comment] 2018-04-26 13:43
I got it reproduced with the dockerfile, but it's running based on rsyslog 8.32. 
I create a test based on the docker environment but I was not able to produce a crash. I am waiting for a more recent rsyslog version for the docker environment in order to see if this is an already fixed issue.

**Comment by rgerhards** [comment] 2018-04-26 14:48
@alorbach as far as I know, @StrongestNumber9 builds his own packages, so he would need to provide that version. To double-check, could you checkout v8.32.0 and check if the test fails with that version?

It's likely that 8.34 fixes the issue, as a lot of work has been done on "small nits" which could have caused that.

**Comment by alorbach** [comment] 2018-04-27 06:59
I will wait for a 8.34 package to reproduce the problem with the docker environment.

**Comment by alorbach** [comment] 2018-04-27 07:36
Still could not reproduce a crash, only some debug print issues in debug mode only. Here is valgrind output from the testoutput: 

`==75454== Memcheck, a memory error detector
==75454== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==75454== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==75454== Command: ../tools/rsyslogd -C -n -irsyslog.pid -M../runtime/.libs:../.libs -ftestconf.conf
==75454== 
==75454== Conditional jump or move depends on uninitialised value(s)
==75454==    at 0x5CDEB83: vfprintf (vfprintf.c:1631)
==75454==    by 0x5D07A48: vsnprintf (vsnprintf.c:114)
==75454==    by 0x45A6F8: r_dbgprintf (debug.c:1018)
==75454==    by 0x432650: cnfstmtPrintOnly (rainerscript.c:3928)
==75454==    by 0x432C6F: cnfstmtPrint (rainerscript.c:4026)
==75454==    by 0x481386: rulesetDebugPrint (ruleset.c:895)
==75454==    by 0x481491: rulesetOptimize (ruleset.c:925)
==75454==    by 0x481507: doRulesetOptimizeAll (ruleset.c:938)
==75454==    by 0x45184D: llExecFunc (linkedlist.c:392)
==75454==    by 0x481557: rulesetOptimizeAll (ruleset.c:948)
==75454==    by 0x440C0D: load (rsconf.c:1348)
==75454==    by 0x410E52: initAll (rsyslogd.c:1454)
==75454== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:vfprintf
   fun:vsnprintf
   fun:r_dbgprintf
   fun:cnfstmtPrintOnly
   fun:cnfstmtPrint
   fun:rulesetDebugPrint
   fun:rulesetOptimize
   fun:doRulesetOptimizeAll
   fun:llExecFunc
   fun:rulesetOptimizeAll
   fun:load
   fun:initAll
}
==75454== Use of uninitialised value of size 8
==75454==    at 0x5CDB76B: _itoa_word (_itoa.c:179)
==75454==    by 0x5CDF12C: vfprintf (vfprintf.c:1631)
==75454==    by 0x5D07A48: vsnprintf (vsnprintf.c:114)
==75454==    by 0x45A6F8: r_dbgprintf (debug.c:1018)
==75454==    by 0x432650: cnfstmtPrintOnly (rainerscript.c:3928)
==75454==    by 0x432C6F: cnfstmtPrint (rainerscript.c:4026)
==75454==    by 0x481386: rulesetDebugPrint (ruleset.c:895)
==75454==    by 0x481491: rulesetOptimize (ruleset.c:925)
==75454==    by 0x481507: doRulesetOptimizeAll (ruleset.c:938)
==75454==    by 0x45184D: llExecFunc (linkedlist.c:392)
==75454==    by 0x481557: rulesetOptimizeAll (ruleset.c:948)
==75454==    by 0x440C0D: load (rsconf.c:1348)
==75454== 
{
   <insert_a_suppression_name_here>
   Memcheck:Value8
   fun:_itoa_word
   fun:vfprintf
   fun:vsnprintf
   fun:r_dbgprintf
   fun:cnfstmtPrintOnly
   fun:cnfstmtPrint
   fun:rulesetDebugPrint
   fun:rulesetOptimize
   fun:doRulesetOptimizeAll
   fun:llExecFunc
   fun:rulesetOptimizeAll
   fun:load
}
==75454== Conditional jump or move depends on uninitialised value(s)
==75454==    at 0x5CDB775: _itoa_word (_itoa.c:179)
==75454==    by 0x5CDF12C: vfprintf (vfprintf.c:1631)
==75454==    by 0x5D07A48: vsnprintf (vsnprintf.c:114)
==75454==    by 0x45A6F8: r_dbgprintf (debug.c:1018)
==75454==    by 0x432650: cnfstmtPrintOnly (rainerscript.c:3928)
==75454==    by 0x432C6F: cnfstmtPrint (rainerscript.c:4026)
==75454==    by 0x481386: rulesetDebugPrint (ruleset.c:895)
==75454==    by 0x481491: rulesetOptimize (ruleset.c:925)
==75454==    by 0x481507: doRulesetOptimizeAll (ruleset.c:938)
==75454==    by 0x45184D: llExecFunc (linkedlist.c:392)
==75454==    by 0x481557: rulesetOptimizeAll (ruleset.c:948)
==75454==    by 0x440C0D: load (rsconf.c:1348)
==75454== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:_itoa_word
   fun:vfprintf
   fun:vsnprintf
   fun:r_dbgprintf
   fun:cnfstmtPrintOnly
   fun:cnfstmtPrint
   fun:rulesetDebugPrint
   fun:rulesetOptimize
   fun:doRulesetOptimizeAll
   fun:llExecFunc
   fun:rulesetOptimizeAll
   fun:load
}
==75454== Conditional jump or move depends on uninitialised value(s)
==75454==    at 0x5CDF1AF: vfprintf (vfprintf.c:1631)
==75454==    by 0x5D07A48: vsnprintf (vsnprintf.c:114)
==75454==    by 0x45A6F8: r_dbgprintf (debug.c:1018)
==75454==    by 0x432650: cnfstmtPrintOnly (rainerscript.c:3928)
==75454==    by 0x432C6F: cnfstmtPrint (rainerscript.c:4026)
==75454==    by 0x481386: rulesetDebugPrint (ruleset.c:895)
==75454==    by 0x481491: rulesetOptimize (ruleset.c:925)
==75454==    by 0x481507: doRulesetOptimizeAll (ruleset.c:938)
==75454==    by 0x45184D: llExecFunc (linkedlist.c:392)
==75454==    by 0x481557: rulesetOptimizeAll (ruleset.c:948)
==75454==    by 0x440C0D: load (rsconf.c:1348)
==75454==    by 0x410E52: initAll (rsyslogd.c:1454)
==75454== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:vfprintf
   fun:vsnprintf
   fun:r_dbgprintf
   fun:cnfstmtPrintOnly
   fun:cnfstmtPrint
   fun:rulesetDebugPrint
   fun:rulesetOptimize
   fun:doRulesetOptimizeAll
   fun:llExecFunc
   fun:rulesetOptimizeAll
   fun:load
   fun:initAll
}
==75454== Conditional jump or move depends on uninitialised value(s)
==75454==    at 0x5CDEC59: vfprintf (vfprintf.c:1631)
==75454==    by 0x5D07A48: vsnprintf (vsnprintf.c:114)
==75454==    by 0x45A6F8: r_dbgprintf (debug.c:1018)
==75454==    by 0x432650: cnfstmtPrintOnly (rainerscript.c:3928)
==75454==    by 0x432C6F: cnfstmtPrint (rainerscript.c:4026)
==75454==    by 0x481386: rulesetDebugPrint (ruleset.c:895)
==75454==    by 0x481491: rulesetOptimize (ruleset.c:925)
==75454==    by 0x481507: doRulesetOptimizeAll (ruleset.c:938)
==75454==    by 0x45184D: llExecFunc (linkedlist.c:392)
==75454==    by 0x481557: rulesetOptimizeAll (ruleset.c:948)
==75454==    by 0x440C0D: load (rsconf.c:1348)
==75454==    by 0x410E52: initAll (rsyslogd.c:1454)
==75454== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:vfprintf
   fun:vsnprintf
   fun:r_dbgprintf
   fun:cnfstmtPrintOnly
   fun:cnfstmtPrint
   fun:rulesetDebugPrint
   fun:rulesetOptimize
   fun:doRulesetOptimizeAll
   fun:llExecFunc
   fun:rulesetOptimizeAll
   fun:load
   fun:initAll
}
==75454== Conditional jump or move depends on uninitialised value(s)
==75454==    at 0x5CDECE2: vfprintf (vfprintf.c:1631)
==75454==    by 0x5D07A48: vsnprintf (vsnprintf.c:114)
==75454==    by 0x45A6F8: r_dbgprintf (debug.c:1018)
==75454==    by 0x432650: cnfstmtPrintOnly (rainerscript.c:3928)
==75454==    by 0x432C6F: cnfstmtPrint (rainerscript.c:4026)
==75454==    by 0x481386: rulesetDebugPrint (ruleset.c:895)
==75454==    by 0x481491: rulesetOptimize (ruleset.c:925)
==75454==    by 0x481507: doRulesetOptimizeAll (ruleset.c:938)
==75454==    by 0x45184D: llExecFunc (linkedlist.c:392)
==75454==    by 0x481557: rulesetOptimizeAll (ruleset.c:948)
==75454==    by 0x440C0D: load (rsconf.c:1348)
==75454==    by 0x410E52: initAll (rsyslogd.c:1454)
==75454== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:vfprintf
   fun:vsnprintf
   fun:r_dbgprintf
   fun:cnfstmtPrintOnly
   fun:cnfstmtPrint
   fun:rulesetDebugPrint
   fun:rulesetOptimize
   fun:doRulesetOptimizeAll
   fun:llExecFunc
   fun:rulesetOptimizeAll
   fun:load
   fun:initAll
}
rsyslogd started, start msg not yet seen, pid  75454
rsyslogd started, start msg not yet seen, pid  75454
rsyslogd startup msg seen, pid  75454
startup-vg still running
starting run 1
Sending 1000 messages.

00001000 messages sent
runtime: 1.286
End of tcpflood Run
imdiag[13500]: mainqueue empty
DoDie called.
==75454== 
==75454== HEAP SUMMARY:
==75454==     in use at exit: 33,308 bytes in 96 blocks
==75454==   total heap usage: 11,118 allocs, 11,022 frees, 1,363,759 bytes allocated
==75454== 
==75454== 280 (168 direct, 112 indirect) bytes in 1 blocks are definitely lost in loss record 40 of 50
==75454==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==75454==    by 0x47217C: wtiConstruct (wti.c:222)
==75454==    by 0x4730B6: wtiGetDummy (wti.c:478)
==75454==    by 0x476B18: qAddDirect (queue.c:1056)
==75454==    by 0x476BED: qqueueAdd (queue.c:1090)
==75454==    by 0x47CF57: doEnqSingleObj (queue.c:2941)
==75454==    by 0x47D548: qqueueEnqMsg (queue.c:3042)
==75454==    by 0x41025C: submitMsg2 (rsyslogd.c:1008)
==75454==    by 0x7A3F161: onSyslogRcv (imrelp.c:248)
==75454==    by 0x7C4FA02: relpSCSyslog (in /usr/lib/librelp.so.0.3.0)
==75454==    by 0x7C4914A: relpEngineDispatchFrame (in /usr/lib/librelp.so.0.3.0)
==75454==    by 0x7C4AE8E: relpFrameProcessOctetRcvd (in /usr/lib/librelp.so.0.3.0)
==75454== 
{
   <insert_a_suppression_name_here>
   Memcheck:Leak
   match-leak-kinds: definite
   fun:calloc
   fun:wtiConstruct
   fun:wtiGetDummy
   fun:qAddDirect
   fun:qqueueAdd
   fun:doEnqSingleObj
   fun:qqueueEnqMsg
   fun:submitMsg2
   fun:onSyslogRcv
   fun:relpSCSyslog
   fun:relpEngineDispatchFrame
   fun:relpFrameProcessOctetRcvd
}
==75454== LEAK SUMMARY:
==75454==    definitely lost: 168 bytes in 1 blocks
==75454==    indirectly lost: 112 bytes in 1 blocks
==75454==      possibly lost: 0 bytes in 0 blocks
==75454==    still reachable: 33,028 bytes in 94 blocks
==75454==         suppressed: 0 bytes in 0 blocks
==75454== Reachable blocks (those to which a pointer was found) are not shown.
==75454== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==75454== 
==75454== For counts of detected and suppressed errors, rerun with: -v
==75454== Use --track-origins=yes to see where uninitialised values come from
==75454== ERROR SUMMARY: 7 errors from 7 contexts (suppressed: 0 from 0)
rsyslogd run exited with 10`

**Comment by rgerhards** [comment] 2018-04-27 11:03
I should add that @alorbach did this test with 8.32.0, so the environment is the same. I have seen that valgrind errors, and these are definitely pointing to something wrong. It's the non-existing ruleset, and I'll craft a patch for that.

@StrongestNumber9 how exactly do you build your packages? I mean which compiler, CFLAGS, options, etc...

**Comment by StrongestNumber9** [comment] 2018-04-27 11:05
Pinging @kortemik for more details

**Comment by rgerhards** [comment] 2018-04-27 11:12
some background: I ask as we are still unable to reproduce outside of the docker container -- the only difference most probably now is how the binary is being created. The fix I crafted does not cause an abort, it's really cosmetic.

**Comment by rgerhards** [comment] 2018-04-27 12:48
@StrongestNumber9 @kortemik this is very strange - are your sure this really is rsyslog 8.32? If I enable debug logging inside the container, I see that parts of the processing flow do now happen, namely the script optimizer is not called. That is also the cause of the abort.

Have you patched part of the code out? This is definitely not what we know as 8.32.

**Comment by rgerhards** [comment] 2018-04-27 12:52
This, for example, is completely missing in the debug log:
```
3146.064008431:main thread    : ruleset.c: begin ruleset optimization phase
3146.064014330:main thread    : ruleset.c: ruleset 'RSYSLOG_DefaultRuleset' before optimization:
3146.064020620:main thread    : ruleset 0x1ad3da0: ruleset.c: rsyslog ruleset RSYSLOG_DefaultRuleset:
3146.064024495:main thread    : rainerscript.c: PROPFILT
3146.064027920:main thread    : rainerscript.c: 	Property.: 'syslogtag'
3146.064030299:main thread    : rainerscript.c: 	Operation: 'contains'
3146.064035585:main thread    : rainerscript.c: 	Value....: 'rsyslogd'
3146.064038112:main thread    : rainerscript.c: THEN
3146.064041247:main thread    : rainerscript.c:   ACTION 0 [builtin:omfile:?startupfile]
3146.064046559:main thread    : rainerscript.c: END PROPFILT
3146.064049974:main thread    : rainerscript.c: CALL [doesnt_exist, queue:0]
3146.064052630:main thread    : ruleset 0x1ad3da0: ruleset.c: ruleset RSYSLOG_DefaultRuleset assigned parser list:
3146.064060833:main thread    : errmsg.c: Called LogMsg, msg: error during config processing: ruleset 'doesnt_exist' cannot be found
```

**Comment by kortemik** [comment] 2018-04-27 13:34
We have 393bb03de47a625751534f425164d53dbb2259ba (tag v8.32.0) plus omfile-hardened and very minimal changes back-ported from development of 8.33.0 (the issues we created back then).

**Comment by rgerhards** [comment] 2018-04-27 13:41
well... all I can say is that your binary works quite different from regular rsyslog. How can we go forward? Maybe you should build a package from plain v8.32.0 tag or v8.34.0 tag. I really can't debug this further, as the code is for some reason different and I also cannot add additional instrumentation. If I use our versions, everything works differently (and works).

**Comment by kortemik** [comment] 2018-04-27 13:52
i hope we can find the reason why recompiling does cause such issues, i sent the source via a drive link to email. however there is nothing big there, just fixes that got merged with 8.33.0 and the omfile-hardened patch as were in the pull request back then

**Comment by rgerhards** [comment] 2018-04-27 14:04
It's very strange. It would still be helpful if you just could use normal 8.34, package it and see what happens. If it then still fails, we could outrule a number of possibilities and so we would not need to explore them.

**Comment by rgerhards** [comment] 2018-04-28 06:28
ahhhh! Things begin to clear up a little. The test instrumentation seems to play a role here and changes behavior. I am now able to reproduce the missing optimizer call if I remove the instrumentation. Will keep you posted.

**Comment by rgerhards** [comment] 2018-04-28 06:33
I now see - if there are no actions at all in the config, the optimizer is not called. Test instrumentation adds a test and so everything works. Let me see what is the best way forward: possibly make rsyslog terminate if no actions exist, as it really cannot do anything useful in that case...

**Comment by rgerhards** [comment] 2018-04-28 06:42
yes - if I add an action to your container's rsyslog.conf, it also works.

**Comment by kortemik** [comment] 2018-04-28 08:30
termination would be possibly the best case, although someone might want to have a /dev/null kind of a target for performance testing or so

**Comment by rgerhards** [comment] 2018-04-28 09:34
well, if you want to write to /dev/null, than you need an action and so the condition is satisfied. But, granted, it might be handy for extreme tests to permit this, so I'll probably add a non-user option to let it keep running. Nevertheless, in such cases it can possibly segfault, it's no use case that we really support (aka "do not turn on this option and complain").

**Closed** 2018-04-28 12:01 UTC
Labels: bug, sponsored

**Comment by davidelang** [comment] 2018-04-29 04:52
I agree,

I was thinking that the ability to have a config with no outputs could be 
usefule for benchmarking purposes.

**Comment by rgerhards** [comment] 2018-05-01 10:41
> I was thinking that the ability to have a config with no outputs could be
> usefule for benchmarking purposes.

OK. I am still tempted to say that in almost all cases, this should be treated as a fatal startup error. Do you agree on this?

If so, we could add an option specifically to permit actionless configs. But that would explicitly need to be set.

Note: up until now, this was accepted with just a warning message, but I really think that behavior is not appropriate - especially given the fact that most distros by default simply drop rsyslog error messages.

**Comment by davidelang** [comment] 2018-05-01 17:32
On Tue, 1 May 2018, Rainer Gerhards wrote:

> OK. I am still tempted to say that in almost all cases, this should be treated as a fatal startup error. Do you agree on this?
>
> If so, we could add an option specifically to permit actionless configs. But that would explicitly need to be set.

I think it is very reasonable to have a "I'm doing very wierd stuff, skip sanity 
checks" switch to enable things that make no sense in a normal config, but are 
useful for testing or very odd situations like this.

That would allow us to add more sanity checks for bad conditions, beyond this 
one (nothing in the default ruleset, etc)

> Note: up until now, this was accepted with just a warning message, but I 
> really think that behavior is not appropriate - especially given the fact that 
> most distros by default simply drop rsyslog error messages.
