### ISSUE TITLE
rsyslog cannot pick up all messages sent by a very fast sender with non-blocking IO on system log socket

### ISSUE THREAD

**Issue by shejby** [rsyslog/rsyslog#1348] opened 2016-12-29 15:10 UTC
I have this configuration:

```
input(type="imuxsock"
      Socket="/var/log/example_stats.sock" UseSysTimeStamp="off" useSpecialParser="off" parseHostname="on")

if $syslogtag == 'examplestats:' then {

action(type="omfwd"
       Target="10.0.0.1"
       Port="514"
       Protocol="tcp"
       action.resumeRetryCount = "-1"
       queue.type="LinkedList"
       queue.size="25000000"
       queue.highwatermark="1500000"
       queue.lowwatermark="200000"
       queue.workerThreads="2"
       queue.SaveOnShutdown="on"
       queue.FileName="fwdExampleStats"
       queue.maxdiskspace="10g"
       template="examplestats"
      )

action(type="omfile" dynaFile="stats_filename" dirCreateMode="0744" fileCreateMode="0644" fileOwner="nobody" fileGroup="nogroup" dirOwner="nobody" dirGroup="nogroup" zipLevel="6" template="examplestatsFile")

stop
}
```

and when running this simple testing example script:
``` 
import socket

s = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
s.setblocking(0)
s.connect("/var/log/example_stats.sock")
count = 0
while count < 1000:
  count = count + 1
  s.send("TESTING MESSAGE")
  print count
```
i am getting these errors while running rsyslog without systemd:
```
python2 /tmp/test_socket.py       
1
2
3
...
Traceback (most recent call last):
  File "/tmp/test_socket.py", line 9, in <module>
    s.send("TESTING MESSAGE")
socket.error: [Errno 11] Resource temporarily unavailable
```
I am running debian jessie `4.7.0-0.bpo.1-amd64 #1 SMP Debian 4.7.8-1~bpo8+1 (2016-10-19) x86_64 GNU/Linux `
with these packages removed : 
`bsdmainutils* bsdutils* ca-certificates-java* colord* dbus* debhelper* default-jre-headless* dh-strip-nondeterminism* libpam-systemd*
  libpolkit-agent-1-0* libpolkit-backend-1-0* libpolkit-gobject-1-0* libpulse0* libsystemd0* libvirt0* man-db* openjdk-7-jre-headless*
  policykit-1* rsyslog* salt-minion* sane-utils* systemd* systemd-sysv*`

i tried it on following  rsyslog versions 8.4.2-1+deb8u2  8.15.0  8.23.0-2 and I've also tried to compile it from source mainly v 8.15.0. When i try the same with systemd running there is no such a problem. 

Can you please look at it, thanks in advance.

**Comment by davidelang** [comment] 2016-12-29 20:08
what version of rsyslog are you running.

is it possible that rate limiting is triggering and causing your problem?

David Lang

**Comment by shejby** [comment] 2017-01-02 09:46
As I wrote in first message:
> i tried it on following rsyslog versions 8.4.2-1+deb8u2 8.15.0 8.23.0-2 and I've also tried to compile it from source mainly v 8.15.0. When i try the same with systemd running there is no such a problem.

Today i've also tried to explicitly disable rate limiting with these options:
```
$SystemLogRateLimitInterval 0
$SystemLogRateLimitBurst 0
```
but the problem when running without systemd remain the same.

**Comment by ondrejkopka** [comment] 2017-01-16 13:58
Hi guys,
exactly same problem here, no luck after disabling rate limiting too. Do you have any news about this issue?

Im receiving same errors when running that testing script.

Thanks

**Comment by davidelang** [comment] 2017-01-17 03:08
Given that rsyslog has mostly been used without systemd, I have trouble 
believing that it's at fault here. I'm pretty sure something's wrong with the 
test.

Have you tried delivering the logs via a tool like logger instead of this 
script?

David Lang

**Comment by nzt4567** [comment] 2017-01-17 10:25
@davidelang I do not think this is actually related to the testing script at all (well, it is, but it's not its fault). We were seeing similar issue after ripping systemd off our web servers running nginx, while nginx was basically the only thing using rsyslog (through unix sockets). 

The thing is that both nginx and this testing script mark the socket as non-blocking. After stracing nginx we've found out that many `write()` calls return with `EAGAIN` and thus the logging fails. With systemd present this just doesn't happen.

Hotfix was obviously to return to systemd 👎

**Comment by davidelang** [comment] 2017-01-17 10:46
On Tue, 17 Jan 2017, Tomas Kvasnicka wrote:

> @davidelang I do not think this is actually related to the testing script at 
> all (well, it is, but it's not its fault). We were seeing similar issue after 
> ripping systemd off our web servers running nginx, while nginx was basically 
> the only thing using rsyslog (through unix sockets).
>
> The thing is that both nginx and this testing script mark the socket as 
> non-blocking. After stracing nginx we've found out that many `write()` calls 
> return with `EAGAIN` and thus the logging fails. With systemd present this 
> just doesn't happen.
>
> Hotfix was obviously to return to systemd 👎

The thing is that rsyslog has been known to handle a million logs/sec (with a 
simple config), so if you are failing in just a few messages, you are doing 
something wrong.

The syslog spec says that the socket should block until the message is 
processed. On the original syslog, this meant written to disk. On Rsyslog, this 
means accepted into the queue. This is a very fast operation, so you should not 
be running into any issues at such a slow rate.

what are you doing differently in your script compared to using your scripting 
languages syslog() functionality? (or compared to what logger does)

I've done tests with millions of logs at a shot dumped to rsyslog at very high 
speeds (wire speed gig-E to imudp and imtcp, and logger to write to /dev/log 
even faster), without running into any sort of problems. These reports are 
indicating that you are running into grief with just a few messages, so what are 
you doing differently?

David Lang

**Comment by rgerhards** [comment] 2017-02-23 16:32
I think this has to do with scheduler decisions: it looks like the python script's time slice is long enough to overrun the internal buffer, and rsyslog does not get activated during that period (or not activated quickly enough). The only cure I can think about is to run the imuxsock thread on an higher priority, as can also be done with imudp. Other than that, I think we have no options.

**Comment by nzt4567** [comment] 2017-02-23 17:12
@rgerhards That's possible... I've been playing with the script a little bit more and found out that this happens with systemd as well - it's just much less frequent. Same goes for nginx.

**Comment by rgerhards** [comment] 2017-02-23 17:18
Still investigating, but even if I set the thread to highest real time priority, message loss happens. I do not know if we can really do anything against that (but give me a bit more to think about it).

May I assume that the script experiences the problem more often than nginx? I ask because it really runs a **very** tight loop...

**Comment by nzt4567** [comment] 2017-02-23 17:28
From what I've seen during some tests with the script and nginx this can be safely assumed. The frequency of `EAGAIN` in nginx is less then the frequency of `socket.error` exceptions in python (which are actually caused by `EAGAIN` from underlying `write()`s I guess) - do not have any numbers by me right now but I can dig them out of somewhere if that might help you in any way.

**Comment by rgerhards** [comment] 2017-02-23 17:37
error 11 is EAGAIN, so the socket buffer is full. I have now also tested with reading the socket as quickly as possible, without any intervening polling of fds and so on (IAW: made imuxsock defunct except for this one socket). I still get socket buffer overrun with that script at more or less the same location (always between 281 and 284 messages on my system).

If it weren't for nginx, I'd say that's just how it is. With that on my mind, I'd say I can see if we can improve performance during peak bursts. There are some ways to gain some improvement, but it's limited.

It must be noted that ```useSpecialParser="off"``` probably causes more performance loss than what I can do to improve the reader, so I am not sure it really is well spent time.

**Comment by rgerhards** [comment] 2017-02-23 17:42
I should add that I also tried with disabling **all** processing, just reading the socket and not doing anything with the message. Same loss at same location...

**Comment by nzt4567** [comment] 2017-02-23 17:58
Yeah, that loop is **really** tight ;) Let me know if an average time between two successive `write()s` could help chasing this - I guess I might just patch nginx to calculate that time for us and let it run for a while in the wild :)

**Comment by rgerhards** [comment] 2017-02-23 18:11
> - I guess I might just patch nginx to calculate that time for us and let it run for a while in the wild :)

That might be a good plan!

I assume that if I craft an enhancement patch, you could also run that and see what ngnix does with the new code?

**Comment by rgerhards** [comment] 2017-02-23 18:20
With ```time.sleep(0.000001)``` inside the loop it works for me, if I add another 0, it does not.

**Comment by nzt4567** [comment] 2017-02-23 18:33
So hundreds of nanoseconds break it? Thats pretty impressive speed... And yes, your assumption is again correct

**Comment by nzt4567** [comment] 2017-02-28 17:15
Okay so we have approximately 24 nginx workers on a single server trying to write to rsyslog's socket -> minimum times between two successive writes are actually nanoseconds (using `clock_gettime()`). That's much faster than I expected, but I guess it's possible given that there are much more nginx workers then rsyslog processes and that all the workers might finish a request at basically the same time (requests get logged when they are finished).

**Comment by rgerhards** [comment] 2017-12-16 10:19
Sorry for not coming back earlier. I was unfortunately more than hyper-busy over the past couple of months, just been able to recover. Reviewing this, I think we can close it as inherently unsolvable?

**Closed** 2018-02-15 17:10 UTC
