### ISSUE TITLE
imfile doesn't work with ReadMode 2

### ISSUE THREAD

**Issue by radu-gheorghe** [rsyslog/rsyslog#144] opened 2014-10-29 09:32 UTC
Complete description here: http://rsyslog-users.1305293.n2.nabble.com/not-forwarding-when-imfile-has-readmode-2-td7586637.html

Basically, something like this doesn't forward anything:
```
module(load="imfile")

input(type="imfile"
      File="/var/log/cassandra/system.log"
      Tag="cassandra-system:"
      ReadMode="2")

*.* @@logsene-receiver-syslog.sematext.com;RSYSLOG_SyslogProtocol23Format 
```

But changing ReadMode to 0 or setting imfile to polling mode "unlocks" imfile and messages get forwarded.

**Comment by otisg** [comment] 2015-01-20 16:56
Wondering if this has maybe been fixed in the recent 8.7 release, or maybe in the upcoming 8.8 release?

**Comment by radu-gheorghe** [comment] 2015-03-20 11:43
@rgerhards I finally managed to add tests that should make testing things easier. There were some bumps in the road, it looks like everything works fine if the file is there before rsyslog is started (like it is with other imfile tests). But it doesn't see new lines being added to the file while in ReadMode 2.

That, plus I forgot to properly use imdiag in the conf :)

Please let me know if I can help with anything. I wanted to write a blog post about using imfile  - and inotify is defintely the way to go - but this issue is in the way :(

**Comment by rgerhards** [comment] 2015-03-20 17:51
2015-03-20 12:43 GMT+01:00 Radu Gheorghe <notifications@github.com>:

> @rgerhards <https://github.com/rgerhards> I finally managed to add tests
> that should make testing things easier. There were some bumps in the road,
> it looks like everything works fine if the file is there before rsyslog is
> started (like it is with other imfile tests). But it doesn't see new lines
> being added to the file while in ReadMode 2.
>
> That, plus I forgot to properly use imdiag in the conf :)
>
> Please let me know if I can help with anything. I wanted to write a blog
> post about using imfile - and inotify is defintely the way to go - but this
> issue is in the way :(
>
>
>
Thanks, I'll give the patch a try in a separate branch and hope that it
will help me understand what's going on :-)

Rainer

**Comment by radu-gheorghe** [comment] 2015-03-23 11:07
Thanks, Rainer. I've just done some more tests on 8.8 and it looks like ReadMode 2 doesn't do anything with polling mode either. It just sees that the file has changed and doesn't do anything. Here are the debug logs:

polling:
```
7740.186383856:imfile.c       : strm 0x24b7b80: file 4 read 6 bytes
7740.186414886:imfile.c       : strm 0x24b7b80: file 4 read 0 bytes
7740.186437592:imfile.c       : stream checking for file change on '/tmp/testing', inode 111359/111359
```
inotify
```
7817.585085758:imfile.c       : DDDD: imfile event notification: rd 16[0], wd (2, mask 00000002, cookie 0000, len 0)
7817.585112690:imfile.c       : watch was MODIFID
7817.585121221:imfile.c       : DDDD: imfile: wd 2 got file 0x173aa40, dir -1
7817.585143658:imfile.c       : strm 0x1703e40: file 5 read 9 bytes
7817.585155810:imfile.c       : strm 0x1703e40: file 5 read 0 bytes
7817.585175610:imfile.c       : stream checking for file change on '/tmp/testing', inode 111359/111359
```

Looking at imfile.c, I don't see anything relevant related to ReadMode (other than setting the defaults, really). I might be missing something essential, but maybe the code that's supposed to handle ReadMode got wiped out at some point?

Either way, it looks like ReadMode 2 doesn't work in either polling or inotify modes in 8.8. So I'm changing the subject of the bug because it's not specific to inotify.

**Comment by rgerhards** [comment] 2015-03-23 11:12
2015-03-23 12:07 GMT+01:00 Radu Gheorghe <notifications@github.com>:

> Thanks, Rainer. I've just done some more tests on 8.8 and it looks like
> ReadMode 2 doesn't do anything with polling mode either. It just sees that
> the file has changed and doesn't do anything. Here are the debug logs:
>
> polling:
>
> 7740.186383856:imfile.c       : strm 0x24b7b80: file 4 read 6 bytes
> 7740.186414886:imfile.c       : strm 0x24b7b80: file 4 read 0 bytes
> 7740.186437592:imfile.c       : stream checking for file change on '/tmp/testing', inode 111359/111359
>
> inotify
>
> 7817.585085758:imfile.c       : DDDD: imfile event notification: rd 16[0], wd (2, mask 00000002, cookie 0000, len 0)
> 7817.585112690:imfile.c       : watch was MODIFID
> 7817.585121221:imfile.c       : DDDD: imfile: wd 2 got file 0x173aa40, dir -1
> 7817.585143658:imfile.c       : strm 0x1703e40: file 5 read 9 bytes
> 7817.585155810:imfile.c       : strm 0x1703e40: file 5 read 0 bytes
> 7817.585175610:imfile.c       : stream checking for file change on '/tmp/testing', inode 111359/111359
>
> Looking at imfile.c, I don't see anything relevant related to ReadMode
> (other than setting the defaults, really). I might be missing something
> essential, but maybe the code that's supposed to handle ReadMode got wiped
> out at some point?
>

It's in runtime/stream.c, function strmReadLine. I am currently looking at
it. It looks like the problem was there all the time, but didn't show up in
polling mode because it was much more unlikely that a partial record was
present -- and if so, it would probably much harder to notice that a single
one was missing.

The new test is now manufactured to show exactly this issue and it now
shows up. Remember that I wasn't able to reproduce in either mode.

I now know that strmReadLine() does not handle incomplete records, but I am
thinking about what the best was to fix this might be... To do it cleanly,
a lot of refactoring would be needed, so I hope to find a simpler interim
solution.

Rainer

**Comment by rgerhards** [comment] 2015-03-23 11:28
@radu-gheorghe it would also be great if you could amend the polling mode test to your PR.

**Comment by radu-gheorghe** [comment] 2015-03-23 13:11
Thanks, Rainer, we were looking at the same function and tried to understand what's trying to do :)

Regarding the PR, you mean to add a second test with ReadMode=2 but with polling mode?

**Comment by rgerhards** [comment] 2015-03-23 13:12
PR: yes, exactly.

I guess I can have a patch soon.

**Comment by radu-gheorghe** [comment] 2015-03-23 14:13
I've added a second test for polling mode (not sure how to do it all in a single test without doing some dirty hacks that will allow me to put variables in confs). I'm such a git noob, I did git commit --amend, but it shows a different commit in the PR. All files are there, nevertheless.

Regarding the patch - I was just looking at my regular stacktraces and they look a bit like this:
```
2015-03-23 10:29:58,666 ERROR AbstractReceiverController:162 - Processing request failed
kafka.common.FailedToSendMessageException: Failed to send messages after 3 tries.
	at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:90)
	at kafka.producer.Producer.send(Producer.scala:77)
```

Basically, there's a first line with the date, severity, etc. and then comes the stacktrace itself from the beginning of the second line. ReadMode=2 alone won't cut it, as I would get the first line and the rest of the stacktrace as separate events.

Though it has nothing to do with the initial bug report, I believe it's a common problem. One that seems to be solved by Logstash and syslog-ng by reading line by line and allowing you to specify a regexp in the config. For example, anything that doesn't look like a date belongs to the previous line's event.

I'm thinking if it's not a good occasion to change strmReadLine() to take entire lines and compare them to configurable regexes. This would contrast with the current approach of taking each character and comparing them to hardcoded spaces and tabs.

Even if you don't have the time to apply such a change, would you agree with it? I mean, would you accept a patch that will do it? Of course, I don't know if we're actually able to contribute it, but one can try :)

Another question - again besides this bug but in the same context - is whether we can parse such stacktraces with mmnormalize. I know that I would be able to parse metadata from the first line into some custom fields like date, severity, class, etc. But can I tell it to put everything else (from Processing failed and including all the lines from the stacktrace) into a message field? Or will mmnormalize stop at the end of the first line?

**Comment by rgerhards** [comment] 2015-03-23 14:52
We need to make sure we keep this bug tracker focussed. So I answer to all, but it would be great if you could break out the unrelated issues from now on and create a separate tracker for them or move them to the ML -- but maybe for some I have a "semi-final" answer...

amended PR: I used bad wording and I'll see that I get this merged. Should not be a biggi. I general, you can just add commits and push, github will add to the PR as long as it is the same branch and I haven't alraedy merged it.

Stacktraces: I am actively searching for a larger set of them: http://blog.gerhards.net/2015/02/looking-for-java-stacktrace-samples.html
In essence, stack trace handling is on my todo list, even on a high spot, but I have not yet received any useful sample. So it moved a bit down the list, but I still plan to work on it within the next couple of month (as part of log normalization). So native support is probably not within reach of 8.9 or 8.10 but I am focused on getting there.

The same is true for input parsing of imfile. I have big plans to change things here, probably some small steps in the 8.10 timeframe. Again, big problem is that I don't get logs to train the system.

I intend to do all of this in the context of the log normalization effort, but it is extremely hard to get started due to missing samples. The approach to identfiy what is needed is based on structure data mining, thus statistics, and statistics requires a decent set of sample to work ;) And it would be even better to have samples that can be freely published, so that others can independently verify.

In a nutshell, I currently prefer **not** to receive patches for imfile and the subsystem, as I intend to do a mayor rewrite of the ingestion part. If we add an interim solution, we need to support it for years to come and I would like to avoid that.

Now that you have the big picture: mmnormalize and stacktraces is exactly what I am after at, but again this is suffering from lack of samples. Right now, I've pushed that idea back because I got some old PIX logs we had at Adiscon and I got a set of Linux messages (under NDA) that I can actually work with. And mmnormalize works on messages, not lines. So when imfile (e.g.) turns multiple lines into a single message, mmnormalize can work on it. But in the concrete example if the stacktrace is not detected as a multiline message, this will not work.

Finally, I would appreciate if you could apply the commit I just made and see if it works for real cases as well. It needs at least some finishing touches, but the test at least passes.

**Comment by rgerhards** [comment] 2015-03-23 14:55
Some important thing I missed: I can of course manufacture stack traces and other logs. But only if you look at real-world sample you'll see all those surprises that break your algorithms. I've already proven that expectation with the samples I have at hand...

**Comment by rgerhards** [comment] 2015-03-24 10:39
@radu-gheorghe I have updated my patches and also added more tests for the "exotic" cases. I would appreciate if you could give the patch set a try in practice and report back. It would be great if we could release this as part of 8.9.0.

**Comment by radu-gheorghe** [comment] 2015-03-25 16:51
Thanks, Rainer! I just tested the branch with your recent commits and it works fine for me. I tried both single and multiline logs, created the file before and after starting rsyslog, looks good now.

I'm closing this one (feel free to reopen if you disagree), I'll open another issue for the stacktraces I mentioned in an earlier comment.

**Comment by rgerhards** [comment] 2015-03-29 13:12
I'll re-open because the testbench did find an issue which currently prevents me from merging into the "official" version. Hope to have this sorted out soon.

**Comment by rgerhards** [comment] 2015-03-30 10:38
ok, that was no real error, just a dumb testing aid remains. Now fixed and finally merged! thx for all the help.

**Closed by rgerhards** 2015-03-30 10:38 UTC
Labels: bug

**Comment by radu-gheorghe** [comment] 2015-03-30 11:41
You're welcome! And thank YOU for all the help!
