### ISSUE TITLE
Question: queue.saveonshutdown parameter doesn't work with omkafka module

### ISSUE THREAD

**Issue by maximeguillet** [rsyslog/rsyslog#2458] opened 2018-02-05 17:59 UTC
Hello,

I have the following configuration:
- /etc/rsyslog.conf
```
$MaxMessageSize 32k
$ModLoad imuxsock
$ModLoad imklog
$FileOwner root
$FileGroup adm
$WorkDirectory /var/spool/rsyslog
$IncludeConfig /etc/rsyslog.d/*.conf
```
- /etc/rsyslog.d/50-kafka.conf
```
module(load="omkafka")
module(load="mmjsonparse")
template(name="json_log" type="list") {
  constant(value="{")
    constant(value="\"@timestamp\":\"")  property(name="timereported" dateFormat="rfc3339")
    constant(value=",")
    property(name="$!all-json" position.from="2")
}

if $syslogfacility-text == 'local4' then {
    if $syslogtag startswith 'prog' then {
        action(type="mmjsonparse" cookie="")
        action(type="omkafka"
            topic="logmessage"
            broker=["kafka.service.consul:9092"]
            partitions.auto="on"
            template="json_log"
            confParam=["message.send.max.retries=100000",
                "queue.buffering.max.messages=5000",
                "queue.buffering.max.ms=1000",
                "api.version.request=true"]
            action.resumeRetryCount="-1"
            action.resumeInterval="5"
            queue.type="LinkedList"
            queue.spoolDirectory="/var/spool/rsyslog"
            queue.filename="kafka_local4_prog.queue"
            queue.size="300000"
            queue.saveonshutdown="on"
            queue.dequeuebatchsize="1024"
            resubmitOnFailure="on"
            keepFailedMessages="on"
            failedMsgFile="/var/spool/rsyslog/kafka_local4_prog.failed"
            errorFile="/var/spool/rsyslog/kafka_local4_prog.error"
        )
        stop
    }
}
```

### Expected behavior

Log messages still in queue at rsyslog shutdown should be saved in disk and retried at restart thanks to the parameters `queue.saveonshutdown`.

### Actual behavior

Log messages still in queue when rsyslog stops are lost and no queue file is created in disk.

I reproduce with the following steps:

 * deny access to Kakfa port with `iptables -A OUTPUT -p tcp --dport 9092 -j DROP`
 * sending some logs
 * stopping rsyslog with `service rsyslog stop` (The folder `/var/spool/rsyslog` remains empty and no permissions issue has been spotted in debug)
 * flushing iptables rules with `iptables -F`
 * starting rsyslog with `service rsyslog start`

No messages sent during the kafka unavailabilty have been processed.

In debug logs, I have:
```
1159.712464550:main thread    : action 1 queue: queue.c: checking to see if main queue DA worker pool needs to be cancelled
1159.712477862:main thread    : action 1 queue: queue.c: worker threads terminated, remaining queue size log 0, phys 0.
1159.712484922:main thread    : action 1 queue[DA]: queue.c: shutdown: begin to destruct queue
1159.712489780:main thread    : action 1 queue[DA]: queue.c: persisting queue to disk, 0 entries...
1159.712496226:main thread    : strm 0x55b748dd3330: stream.c: file -1(kafka_local4_prog.queue) closing, bDeleteOnClose 1
1159.712499850:main thread    : strm 0x55b748dd3330: stream.c: strmFlushinternal: file -1(kafka_local4_prog.queue) flush, buflen 0 (no need to flush)
1159.712503822:main thread    : stream.c: strmCloseFile: deleting '/var/spool/rsyslog/kafka_local4_prog.queue.00000001'
1159.712534822:main thread    : stream.c: error 2 unlinking '/var/spool/rsyslog/kafka_local4_prog.queue.00000001' - ignored: No such file or directory
1159.712540501:main thread    : strm 0x55b748dd45e0: stream.c: file -1(kafka_local4_prog.queue) closing, bDeleteOnClose 0
1159.712544237:main thread    : strm 0x55b748dd5890: stream.c: file -1(kafka_local4_prog.queue) closing, bDeleteOnClose 1
1159.712547466:main thread    : stream.c: strmCloseFile: deleting '/var/spool/rsyslog/kafka_local4_prog.queue.00000001'
1159.712565894:main thread    : stream.c: error 2 unlinking '/var/spool/rsyslog/kafka_local4_prog.queue.00000001' - ignored: No such file or directory
1159.712572139:main thread    : action 1 queue: queue.c: queue (type 1) will lose 0 messages, destroying...
1159.712579176:main thread    : omkafka.c: omkafka: onDestroy closing - items left in outqueue: 10
1164.711926896:main thread    : errmsg.c: Called LogMsg, msg: omkafka: onDestroy Failed to send remaing '10' messages to topic 'logmessage' on shutdown with error: 'Local: Timed out'
1164.711993072:main thread    : errmsg.c: Called LogMsg, msg: omkafka: queue-drain for close timed-out took too long, items left in outqueue: 10 -- this may indicate data loss
1164.712002441:main thread    : omkafka.c: omkafka: closing topic logmessage
1164.712012121:main thread    : omkafka.c: omkafka: kafka log message [7,DESTROY]: [thrd:app]: Terminating instance
```

I also have this message:
```
1512.409929128:main thread    : omkafka.c: omkafka: persistFailedMsgs: We do not need to persist failed messages.
```
while the parameters `keepFailedMessages` and `failedMsgFile` are defined.

Do I misunderstood something or do I have something wrong in the configuration ?

Thanks for your help,
Regards

### Environment
- rsyslog version:
```
rsyslogd 8.32.0, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Number of Bits in RainerScript integers: 64
```
- platform: Debian GNU/Linux 9.3 (stretch)

**Comment by arsiesys** [comment] 2019-05-29 23:11
Hello @maximeguillet, I am testing and experimenting the same issue while trying to restart rsyslog.
It seems that when rsyslog shutdown, the "librdkafka" is going to make a lot of retry of connections to the broker before "failing" and then allow the "messages" being considered as "failed" by rsyslog and then save them... 

It seesm that I need to increase the omkafka parameter closetimeout to a very high value (like 300s) to let enough time for the messages to be really considered as failed.
I guess maybe there is a librdkafka configuration to avoid so many retries..

There is the configuration I am trying with (I am trying many options of librdkafka..).
```
module(load="omkafka")
action(
        type="omkafka"
        action.reportsuspension="on"
        action.reportSuspensionContinuation="on"
        action.resumeRetryCount="-1"
        broker=["kafka-1.xxx:31090,kafka-2.xxx:31090,kafka-3.xxx:31090"]
        topic="test"
        Template="RSYSLOG_SyslogProtocol23Format"
        errorFile="/tmp/52-rsyslog-kafka-errors.log"
        resubmitOnFailure="on"
        keepFailedMessages="on"
        failedMsgFile="/var/spool/rsyslog/52-kafka.log"
        closeTimeout="300000"
        queue.type="LinkedList"
        queue.maxDiskSpace="1g"
        queue.spoolDirectory="/var/spool/rsyslog"
        queue.filename="52-kafka.queue"
        queue.size="10000"
        queue.saveonshutdown="on"
        confParam=["security.protocol=ssl",
                "debug=all",
                "ssl.key.location=/etc/pki/tls/certs/xxx.key",
                "ssl.certificate.location=/etc/pki/tls/certs/xxx.crt",
                "ssl.ca.location=/etc/ssl/certs/xxxx.pem",
                "socket.timeout.ms=2000",
                "socket.keepalive.enable=true",
                "socket.max.fails=1",
                "request.timeout.ms=5000",
                "session.timeout.ms=5000",
                "message.timeout.ms=5000",
                "metadata.request.timeout.ms=5000",
                "socket.max.fails=1",
                "topic.metadata.refresh.interval.ms=5000"]
)

```

If I am looking in the wrong area, please let me know :D. 

Little snap of the messages I can see in loop for a long while before the failed messages got saved:
```
1038.123026140:7f7e91ffb700: omkafka.c: omkafka: kafka log message [7,BROADCAST]: [thrd:ssl://kafka-3.xxx:31090/bootstrap]: Broadcasting state change
1038.123032880:7f7e91ffb700: omkafka.c: omkafka: kafka log message [7,BUFQ]: [thrd:ssl://kafka-3.xxx:31090/bootstrap]: ssl://kafka-3.xxx:31090/bootstrap: Purging bufq with 0 buffers
1038.123037021:7f7e91ffb700: omkafka.c: omkafka: kafka log message [7,BUFQ]: [thrd:ssl://kafka-3.xxx:31090/bootstrap]: ssl://kafka-3.xxx:31090/bootstrap: Updating 0 buffers on connection reset
1038.155036684:7f7e92ffd700: omkafka.c: omkafka: kafka log message [7,BROKERFAIL]: [thrd:ssl://kafka-1.xxx:31090/bootstrap]: ssl://kafka-1.xxx:31090/bootstrap: failed: err: Local: Broker transport failure: (errno: Connection refused)
1038.155091102:7f7e92ffd700: omkafka.c: omkafka: kafka log message [7,FAIL]: [thrd:ssl://kafka-1.xxx:31090/bootstrap]: ssl://kafka-1.xxx:31090/bootstrap: Connect to ipv4#xxx:31090 failed: Connection refused
1038.155101245:7f7e92ffd700: omkafka.c: omkafka: kafka log message [7,STATE]: [thrd:ssl://kafka-1.xxx:31090/bootstrap]: ssl://kafka-1.xxx:31090/bootstrap: Broker changed state CONNECT -> DOWN
1038.155120937:7f7e92ffd700: omkafka.c: omkafka: kafka log message [7,BROADCAST]: [thrd:ssl://kafka-1.xxx:31090/bootstrap]: Broadcasting state change
1038.155133388:7f7e92ffd700: omkafka.c: omkafka: kafka log message [7,BUFQ]: [thrd:ssl://kafka-1.xxx:31090/bootstrap]: ssl://kafka-1.xxx:31090/bootstrap: Purging bufq with 0 buffers
1038.155146076:7f7e92ffd700: omkafka.c: omkafka: kafka log message [7,BUFQ]: [thrd:ssl://kafka-1.xxx:31090/bootstrap]: ssl://kafka-1.xxx:31090/bootstrap: Updating 0 buffers on connection reset
1038.680389346:7f7e93fff700: omkafka.c: omkafka: kafka log message [7,NOINFO]: [thrd:main]: Topic test partition count is zero: should refresh metadata
1038.680425839:7f7e93fff700: omkafka.c: omkafka: kafka log message [7,METADATA]: [thrd:main]: Skipping metadata refresh of 1 topic(s): no usable brokers
1039.090343942:7f7e927fc700: omkafka.c: omkafka: kafka log message [7,CONNECT]: [thrd:ssl://kafka-2.xxx:31090/bootstrap]: ssl://kafka-2.xxx:31090/bootstrap: broker in state DOWN connecting
1039.090873749:7f7e927fc700: omkafka.c: omkafka: kafka log message [7,CONNECT]: [thrd:ssl://kafka-2.xxx:31090/bootstrap]: ssl://kafka-2.xxx:31090/bootstrap: Connecting to ipv4#xxx:31090 (ssl) with socket 4
1039.090954935:7f7e927fc700: omkafka.c: omkafka: kafka log message [7,STATE]: [thrd:ssl://kafka-2.xxx:31090/bootstrap]: ssl://kafka-2.xxx:31090/bootstrap: Broker changed state DOWN -> CONNECT
```

To finally get : 
omkafka.c: omkafka: persistFailedMsgs successfully written loaded msg

**Comment by yq1320** [comment] 2019-12-24 05:46
How to configure rsyslog.conf with  sasl_plaintext kerberos

**Comment by rgerhards** [comment] 2019-12-24 09:01
This looks like the issue is resolved in current versions. Thus closing. Please open new issue if the problem persists with 8.1911.0 or above.

**Closed by rgerhards** 2019-12-24 09:01 UTC
