### ISSUE TITLE
Omrelp still loses messages

### ISSUE THREAD

**Issue by ondrap** [rsyslog/rsyslog#841] opened 2016-03-03 16:09 UTC
I did a test of omrelp with rsyslog from RPM:
```
# rsyslogd -v
rsyslogd 8.16.0, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64
# cat /etc/rsyslog.d/test.conf
module(load="omrelp")
*.*  action(type="omrelp" target="127.0.0.1" port="20514")
```
I am running a custom receiver for the RELP protocol while testing error codes sent by the custom receiver. This issue was supposed to be fixed in #247, but it still persists. The following is from tcpflow dumps:

First the server starts sending messages. 'a0' messages are OK, than a failure is simulated, 'xFAIL' messages are replied to with error:
```
Sending side:
230 syslog 62 <13>2016-03-03T16:57:31.721851+01:00 milanv-centos7 root: a0:7
231 syslog 62 <13>2016-03-03T16:57:31.723148+01:00 milanv-centos7 root: a0:8
232 syslog 62 <13>2016-03-03T16:57:31.724499+01:00 milanv-centos7 root: a0:9
233 syslog 66 <13>2016-03-03T16:57:46.446897+01:00 milanv-centos7 root: xFAIL:00
234 syslog 66 <13>2016-03-03T16:57:46.448679+01:00 milanv-centos7 root: xFAIL:01
235 syslog 66 <13>2016-03-03T16:57:46.450449+01:00 milanv-centos7 root: xFAIL:02
236 syslog 66 <13>2016-03-03T16:57:46.451803+01:00 milanv-centos7 root: xFAIL:03
Reply:
230 rsp 6 200 OK
231 rsp 6 200 OK
232 rsp 6 200 OK
233 rsp 9 500 Error
234 rsp 9 500 Error
235 rsp 9 500 Error
236 rsp 9 500 Error
```
As you can see, the `233` message is not acknowledged. Then rsyslog tries again with new TCP connection:
```
1 open 85 relp_version=0
relp_software=librelp,1.2.9,http://librelp.adiscon.com
commands=syslog
2 syslog 66 <13>2016-03-03T16:57:46.448679+01:00 milanv-centos7 root: xFAIL:01
3 syslog 66 <13>2016-03-03T16:57:46.450449+01:00 milanv-centos7 root: xFAIL:02
4 syslog 66 <13>2016-03-03T16:57:46.451803+01:00 milanv-centos7 root: xFAIL:03
5 syslog 66 <13>2016-03-03T16:57:46.453084+01:00 milanv-centos7 root: xFAIL:04
```

Then the failure is resolved, more syslog messages are generated, new TCP connection appears and this is the content of the TCP connection:
```
1 open 85 relp_version=0
relp_software=librelp,1.2.9,http://librelp.adiscon.com
commands=syslog
2 syslog 66 <13>2016-03-03T16:57:46.450449+01:00 milanv-centos7 root: xFAIL:02
3 syslog 66 <13>2016-03-03T16:57:46.451803+01:00 milanv-centos7 root: xFAIL:03
4 syslog 66 <13>2016-03-03T16:57:46.453084+01:00 milanv-centos7 root: xFAIL:04
```

The omrelp module loses 1 message every run.

**Comment by rgerhards** [comment] 2016-03-03 16:17
This is fixed in current git master, which will become 8.17.0. next Tuesday. The root cause was inside the queue subsystem. Feel free to re-open if that still doesn't address your issue.

**Closed by rgerhards** 2016-03-03 16:17 UTC
