### ISSUE TITLE
rsyslog is replaying log messages from the past

### ISSUE THREAD

**Issue by lkslawek** [rsyslog/rsyslog#315] opened 2015-04-28 17:47 UTC
_System:_ Ubuntu 14.04.1
_rsyslog:_ 7.4.4-1ubuntu2.3
### Background story

The problematic `rsyslogd` is running since January 26th 2015. Some time in February `nullmailer` daemon that is supporting sending e-mails by a web service on the machine has been logging lots of errors regarding e-mails rejected by destination SMTP server. The issue has been fixed then and `nullmailer` no longer logs such messages.

On April 27th I've noticed weird things happening in `/var/log/syslog`:

```
Feb 15 06:47:16 rt nullmailer[10581]: message repeated 2 times: [ smtp: Failed: 501 <<>@rt.domain>: missing or malformed local part]
Feb 15 06:48:16 rt nullmailer[10582]: message repeated 2 times: [ smtp: Failed: 501 <<>@rt.domain>: missing or malformed local part]
Apr 27 07:30:01 rt CRON[10582]: (rt) CMD (/srv/rt/sbin/rt-email-dashboards)
Feb 15 06:50:16 rt nullmailer[10586]: message repeated 2 times: [ smtp: Failed: 501 <<>@rt.domain>: missing or malformed local part]
Feb 15 06:50:16 rt nullmailer[10587]: message repeated 2 times: [ smtp: Failed: 501 <<>@rt.domain>: missing or malformed local part]
Apr 27 07:40:01 rt CRON[10587]: (rt) CMD (/srv/rt/sbin/rt-clean-sessions --skip-user --older 7H)
Feb 15 06:51:17 rt nullmailer[10588]: message repeated 2 times: [ smtp: Failed: 501 <<>@rt.domain>: missing or malformed local part]
Apr 27 07:40:02 rt RT: [10588] successfully deleted 1 sessions
Feb 15 06:52:17 rt nullmailer[10590]: message repeated 2 times: [ smtp: Failed: 501 <<>@rt.domain>: missing or malformed local part]
Feb 15 06:52:17 rt nullmailer[10591]: message repeated 2 times: [ smtp: Failed: 501 <<>@rt.domain>: missing or malformed local part]
Apr 27 08:17:01 rt CRON[10591]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
```

`/var/log/auth.log` for the same time span shows:

```
Apr 27 07:30:01 rt CRON[10581]: pam_unix(cron:session): session opened for user rt by (uid=0)
Apr 27 07:30:02 rt CRON[10581]: pam_unix(cron:session): session closed for user rt
Apr 27 07:40:01 rt CRON[10586]: pam_unix(cron:session): session opened for user rt by (uid=0)
Apr 27 07:40:02 rt CRON[10586]: pam_unix(cron:session): session closed for user rt
Apr 27 08:17:01 rt CRON[10590]: pam_unix(cron:session): session opened for user root by (uid=0)
Apr 27 08:17:01 rt CRON[10590]: pam_unix(cron:session): session closed for user root
```

Current messages in `syslog` were interleaved with messages with past timestamp. Additionally as you can see there is no constant difference between current time and past time, so it would seem that past messages are actually replayed from some buffer with their original dates, unfortunately log rotation on the machine already deleted the originals so no source to compare with. Also the PIDs of past messages are the same as PIDs logged by `cron`.
### Some analysis

The past messages were appearing on many other events arriving to `rsyslog`. What I've noticed first is that they appear whenever something logs a message to the `auth` facility (on each new `ssh` session or running command with `sudo`). Now after looking again at above log fragments regarding `cron`, which I've actually selected after running following tests, it seems more likely the behaviour might be related to the level instead. `nullmailer` has been killed during the tests.

After running two test commands:

```
$ logger -si -t xxx message one
xxx[11817]: message one
$ logger -sip auth.info -t xxx message two
xxx[11818]: message two
```

My log files were modified as follows:

```
$ tail -2 /var/log/syslog
Apr 27 14:10:37 rt xxx[11817]: message one
Feb 15 16:13:23 rt nullmailer[11818]: message repeated 2 times: [ smtp: Failed: 501 <<>@rt.domain>: missing or malformed local part]
$ tail -1 /var/log/auth.log
Apr 27 14:10:42 rt xxx[11818]: message two
```

Note the PIDs. The second invocation of `logger` was running with PID 11818. The message was correctly logged in `auth.log` but in some mysterious way additional line with the same PID tagged `nullmailer` and having the same PID appeared in `syslog`.

A bit later I've also straced rsyslog on `logger` invocation exactly the same as the second one above.

```
$ strace -p$(pidof rsyslogd) -s512 -fqt
[pid   247] 15:13:25 read(3,  <unfinished ...>
[pid   248] 15:13:25 futex(0x1c4bed4, FUTEX_WAIT_PRIVATE, 446431, NULL <unfinished ...>
[pid   246] 15:13:25 select(1, [0], NULL, NULL, NULL <unfinished ...>
[pid   241] 15:13:25 select(1, NULL, NULL, NULL, {54696, 135825} <unfinished ...>
[pid   246] 15:13:29 <... select resumed> ) = 1 (in [0])
[pid   246] 15:13:29 recvmsg(0, {msg_name(0)=NULL, msg_iov(1)=[{"<38>Apr 27 15:13:29 xxx[12692]: message two", 8096}], msg_controllen=64, {cmsg_len=32, cmsg_level=SOL_SOCKET, cmsg_type=0x1d /* SCM_??? */, ...}, msg_flags=0}, MSG_DONTWAIT) = 43
[pid   246] 15:13:29 futex(0x1c4bed4, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x1c4bed0, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1} <unfinished ...>
[pid   248] 15:13:29 <... futex resumed> ) = 0
[pid   246] 15:13:29 <... futex resumed> ) = 1
[pid   248] 15:13:29 futex(0x1c4c0c0, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid   246] 15:13:29 futex(0x1c4c0c0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid   248] 15:13:29 <... futex resumed> ) = -1 EAGAIN (Resource temporarily unavailable)
[pid   246] 15:13:29 <... futex resumed> ) = 0
[pid   248] 15:13:29 futex(0x1c4c0c0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid   246] 15:13:29 select(1, [0], NULL, NULL, NULL <unfinished ...>
[pid   248] 15:13:29 <... futex resumed> ) = 0
[pid   248] 15:13:29 write(1, "Apr 27 15:13:29 rt xxx[12692]: message two\n", 43) = 43
[pid   248] 15:13:29 write(2, "Feb 15 22:49:18 rt nullmailer[12692]: message repeated 2 times: [ smtp: Failed: 501 <<>@rt.domain>: missing or malformed local part]\n", 133) = 133
[pid   248] 15:13:29 write(4, "Feb 15 22:49:18 rt nullmailer[12692]: message repeated 2 times: [ smtp: Failed: 501 <<>@rt.domain>: missing or malformed local part]\n", 133) = 133
[pid   248] 15:13:29 write(5, "Feb 15 22:49:18 rt nullmailer[12692]: message repeated 2 times: [ smtp: Failed: 501 <<>@rt.domain>: missing or malformed local part]\n", 133) = 133
[pid   248] 15:13:29 open("/dev/xconsole", O_RDWR|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   248] 15:13:29 open("/dev/xconsole", O_RDWR|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   248] 15:13:29 open("/dev/xconsole", O_RDWR|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   248] 15:13:29 open("/dev/xconsole", O_RDWR|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   248] 15:13:29 open("/dev/xconsole", O_RDWR|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   248] 15:13:29 open("/dev/xconsole", O_RDWR|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   248] 15:13:29 open("/dev/xconsole", O_RDWR|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   248] 15:13:29 open("/dev/xconsole", O_RDWR|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   248] 15:13:29 open("/dev/xconsole", O_RDWR|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   248] 15:13:29 open("/dev/xconsole", O_RDWR|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   248] 15:13:29 futex(0x1c4bed4, FUTEX_WAIT_PRIVATE, 446433, NULL
```

Handles of files open by `rsyslogd`, for the reference:

```
$ lsof -p$(pidof rsyslogd) -a /
COMMAND  PID   USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
rsyslogd 241 syslog  cwd    DIR   0,38      132    256 /
rsyslogd 241 syslog  rtd    DIR   0,38      132    256 /
rsyslogd 241 syslog  txt    REG   0,38   521824   5522 /usr/sbin/rsyslogd
rsyslogd 241 syslog    1w   REG   0,38    38912 203519 /var/log/auth.log
rsyslogd 241 syslog    2w   REG   0,38    34883 204394 /var/log/syslog
rsyslogd 241 syslog    4w   REG   0,38    42472 203518 /var/log/mail.log
rsyslogd 241 syslog    5w   REG   0,38    37622 203517 /var/log/mail.err
```

As you can see the past contents were actually written by `rsyslogd`.
### Further attempts

Unfortunately I didn't have debugging symbols for `rsyslogd` to look into the problem with `gdb`. What I wanted to try additionally was tracing the process with `ltrace` and maybe looking at memory regions pointed by traced calls with `gdb`. Strangely enough today (April 28th) after few more tests the behaviour suddenly stopped. Now `strace` shows exactly one proper write after receiving previously problematic input. And still the same instance of `rsyslogd` is up and running...

**Comment by lkslawek** [comment] 2015-04-29 09:02
I've looked into the logs again and the assumption to facility or level is wrong. I've only looked on the messages written after the message I've sent (as result of misleading timestamps), so actually for those two `logger` calls the past message appeared in both cases, so the relevant part of `syslog` was:

```
Feb 15 16:12:23 rt nullmailer[11817]: message repeated 2 times: [ smtp: Failed: 501 <<>@rt.domain>: missing or malformed local part]
Apr 27 14:10:37 rt xxx[11817]: message one
Feb 15 16:13:23 rt nullmailer[11818]: message repeated 2 times: [ smtp: Failed: 501 <<>@rt.domain>: missing or malformed local part]
```

Also I know the version is a bit old and patched by Ubuntu, but as I do not know how to reproduce this behaviour I'm unable to test it against current vanilla version. Maybe someone will be able to deduce what could have caused this and whether it can still happen.

**Comment by rgerhards** [comment] 2015-04-29 09:15
Could you install the current project supported version (8.9.0) and check if the problem reappears? Without any way to reproduce the problem, we cannot look into it. And looking into v7 doesn't make any sense for the project, because there are huge differences in the engine compared to the current one.

**Comment by rgerhards** [comment] 2015-04-30 09:48
duplicate of https://github.com/rsyslog/rsyslog/issues/301

**Comment by dangpf** [comment] 2017-06-05 03:15
rsyslogd 8.27.0
Use rsyslog to send the log, configure the parameters：
$RepeatedMsgReduction on
$RepeatedMsgContainsOrigionalMsg on
At the receiving end, a duplicate log appears，“...message repeated 2 times:...”
What is the reason?

**Comment by davidelang** [comment] 2017-06-05 03:27
That's what repeatedmegreduction does, it detects when there is a string of 
identical messages and replaces the 'extra' copies with the 'message repeated' 
message

The current recommendation is to disable this feature. It makes sense if you 
have logs from a single machine and are reviewing them manually. It really makes 
things confusing when you have logs from multiple machines and try to automate 
the log analysis.

**Closed** 2017-10-01 08:50 UTC
