### ISSUE TITLE
Help with getting imuxsock to read kernel messages

### ISSUE THREAD

**Issue by ebsf1** [rsyslog/rsyslog#4344] opened 2020-07-03 18:07 UTC
We have been having trouble getting any rule in an imuxsock ruleset to read kernel messages, in particular those from iptables, and would be especially grateful to receive any guidance about how to get this working.  Without this, we have no access to ruleset functionality.

A possible source of the problem is that imkmsg is absent from our systems and from the 8.2006.0 .deb package available from the Adiscon ppa repository.  No obvious means exists to obtain or install this module.

We can configure imklog such that a standalone rule (i.e., a rule outside a ruleset) can capture these messages, so at least they are not necessarily lost.

We have attempted any number of configurations spanning rsyslog.conf, journald.conf, and sysctl.conf, including creating listeners specifically for /dev/kmsg, /proc/kmsg, /dev/log, and /run/systemd/journal/syslog, all without success.

Again, many thanks for any advice or suggestions.

### Environment
- rsyslog version: 8.2006.0; Ubuntu 16.04; 18.04

**Comment by ebsf1** [comment] 2020-07-08 15:20
I experimented with a great number of alternative configurations before I thought to try substituting imkmsg for imklog, only to discover that imkmsg was/is missing.

No matter what we do, no rule in an imuxsock ruleset (even *.*) reads iptables log messages.

We know the messages exist, both from running dmesg and because standalone rules (outside an imuxsock ruleset) read the messages.

I experimented with all varieties of syntax, filter, filter text, operator, and property. None had any effect. I experimented with imuxsock listeners on all obvious sockets, and all failed.

I also experimented with both means of interfacing with systemd-journald (i.e., configuring journald.conf with the "ForwardToSyslog=yes" directive, and via imjournal), with no effect.

All that seems to be left (besides giving imkmsg a try) is something to do with the imuxsock module and how it handles kernel messages, and we can't figure it out.

Having ruleset capability for iptables messages would be a big help, and this seems to depend on imuxsock.

The experimental configuration file, with the above A/B tests, is attached.

[rsyslog.conf.test.txt](https://github.com/rsyslog/rsyslog/files/4891529/rsyslog.conf.test.txt)

Many thanks

**Comment by davidelang** [comment] 2020-07-08 19:20
it is not at all clear what you mean about rules not finding logs vs 
'standalone' rules finding them.

Please post configs showing what you are trying

either rsyslog has the logs or it doesn't

now, there are some modules that don't allow you to specify a ruleset, but that 
should show up in a syntax check

David Lang

**Comment by ebsf1** [comment] 2020-07-09 01:07
@davidelang thanks.

I uploaded the config file (rsyslog.conf.test.txt) in my prior post and the link downloads, at least for me.  Please advise if you can't see or access it and I'll re-upload it or post the text in a comment here.

It isn't a question of finding logs or having the logs.  It's a question of which rules (or modules) read messages from a socket and write them to logs.  Actually, it seems to reduce to simply reading messages.

To clarify:

- The module in question is imuxsock, which expressly allows specification of a ruleset.
- The comparison is between (a) rules in a ruleset specified by an imuxsock configuration object (which I refer to as an "imuxsock ruleset"), so:

```
input(
	type="imuxsock"
	ruleset="rst.local"
	socket="/run/systemd/journal/syslog"
)
```

- and (b) identical rules cloned outside a ruleset (which I refer to as "standalone" rules).

- The behavior I am observing, and about which I am seeking advice, is that rules in an imuxsock ruleset do not write kernel log messages, specifically log messages sent by iptables, to the configured/specified file.  In the meantime, standalone clones of the failing rules operate, which is to say they write the messages to the configured files.

I have done extensive and rigorous testing/experimentation to isolate the problem.  The config file I previously uploaded has the A/B tests and is commented for clarity and with results.  I have found:

- dmesg reveals that the messages exist.  This excludes iptables and the kernel log buffer as the source of the failure.
- The first experiment was to clone the failing rules outside the ruleset.  This gives us the "standalone" rules, which operate.  This also confirms that the iptables messages exist because the standalone rules write the messages to the configured/specified file.  This establishes that the issue is the operation of rules in an imuxsock ruleset, and tentatively excludes systemd-journald and socket specification as sources of the failure.
- Further experiments tested all varieties of syntax, filter, filter text, operator, and property.  None had any effect, which is to say none operated in the ruleset, and all operated standalone.  This excludes these factors as sources of the failure.
- Additional experiments varied socket (i.e., by creating listeners on all obvious sockets) and the means of interfacing with systemd-journald, without effect.  That is, imuxsock rules continued failing to write kernel & iptables messages to the configured files.  This excludes socket and systemd-journald interface as sources of the failure.
- In the meantime, other rules in the same ruleset (meaning rules not involving kernel/iptables messages) operate, which is to say they write messages to files as configured.  This suggests the failure is specific to kernel/iptables messages.

I currently am working on obtaining a copy of imkmsg to see whether substituting it for imklog has any effect.  I also am working on hacks involving imfile and improg, and on obtaining a copy of the latter.

Pending this, and otherwise having exhausted all known alternatives, my findings tell me that either (a) I have made an obvious and idiotic configuration error (for which a history exists) notwithstanding syntax checks and scrupulous attendance to the documentation; or (b) there is a bug in imuxsock (or conceivably input() or ruleset()) concerning its reading or handling of kernel/iptables messages.

So, the questions are

- Whether the conf file, and the imuxsock rule specification in particular, is valid;
- If not, how to gain ruleset functionality for kernel/iptables messages.  One imagines 
- If so, then whether the conf file in another environment, or an independently sourced conf file with an imuxsock ruleset, elicits the same behavior with kernel/iptables messages.

Hopefully, this clarifies.  Thanks again for your attention.

**Comment by davidelang** [comment] 2020-07-09 03:13
I normally read these messages via e-mail and did not notice a link to the 
document

I suspect that part of your problem is a misunderstanding over what is in the 
different fields. You are looking for msg contains iptables, but iptables would 
normally show up as the syslogtag or programname, not as part of the message

filter on rawmsg instead of msg and see if it contains what you are expecting.

try to write the logs with the template RSYSLOG_DebugFormat and you will see 
exactly what is in each of the variables that you are testing.

the logs should be exactly the same with or without a ruleset, but I think you 
may be misunderstanding what is in the log. As you look at dmesg, you do not 
have a way to easily tell what will be where in the message

so do

if $rawmsg contains "iptables" then /var/log/iptables.debug.log;RSYSLOG_DebugFormat

and then look in there and see what the iptables logs look like.

David Lang

  On 
Wed, 8 Jul 2020, ebsf1 wrote:

> Date: Wed, 08 Jul 2020 18:08:07 -0700
> From: ebsf1 <notifications@github.com>
> Reply-To: rsyslog/rsyslog
>     <reply@reply.github.com>
> To: rsyslog/rsyslog <rsyslog@noreply.github.com>
> Cc: David Lang <david@lang.hm>, Mention <mention@noreply.github.com>
> Subject: Re: [rsyslog/rsyslog] Help with getting imuxsock to read kernel
>     messages (#4344)
> 
> @davidelang thanks.
>
> I uploaded the config file (rsyslog.conf.test.txt) in my prior post and the link downloads, at least for me.  Please advise if you can't see or access it and I'll re-upload it or post the text in a comment here.
>
> It isn't a question of finding logs or having the logs.  It's a question of which rules (or modules) read messages from a socket and write them to logs.  Actually, it seems to reduce to simply reading messages.
>
> To clarify:
>
> - The module in question is imuxsock, which expressly allows specification of a ruleset.
> - The comparison is between (a) rules in a ruleset specified by an imuxsock configuration object (which I refer to as an "imuxsock ruleset"), so:
>
> ```
> input(
> 	type="imuxsock"
> 	ruleset="rst.local"
> 	socket="/run/systemd/journal/syslog"
> )
> ```
>
> - and (b) identical rules cloned outside a ruleset (which I refer to as "standalone" rules).
>
> - The behavior I am observing, and about which I am seeking advice, is that rules in an imuxsock ruleset do not write kernel log messages, specifically log messages sent by iptables, to the configured/specified file.  In the meantime, standalone clones of the failing rules operate, which is to say they write the messages to the configured files.
>
> I have done extensive and rigorous testing/experimentation to isolate the problem.  The config file I previously uploaded has the A/B tests and is commented for clarity and with results.  I have found:
>
> - dmesg reveals that the messages exist.  This excludes iptables and the kernel log buffer as the source of the failure.
> - The first experiment was to clone the failing rules outside the ruleset.  This gives us the "standalone" rules, which operate.  This also confirms that the iptables messages exist because the standalone rules write the messages to the configured/specified file.  This establishes that the issue is the operation of rules in an imuxsock ruleset, and tentatively excludes systemd-journald and socket specification as sources of the failure.
> - Further experiments tested all varieties of syntax, filter, filter text, operator, and property.  None had any effect, which is to say none operated in the ruleset, and all operated standalone.  This excludes these factors as sources of the failure.
> - Additional experiments varied socket (i.e., by creating listeners on all obvious sockets) and the means of interfacing with systemd-journald, without effect.  That is, imuxsock rules continued failing to write kernel & iptables messages to the configured files.  This excludes socket and systemd-journald interface as sources of the failure.
> - In the meantime, other rules in the same ruleset (meaning rules not involving kernel/iptables messages) operate, which is to say they write messages to files as configured.  This suggests the failure is specific to kernel/iptables messages.
>
> I currently am working on obtaining a copy of imkmsg to see whether substituting it for imklog has any effect.  I also am working on hacks involving imfile and improg, and on obtaining a copy of the latter.
>
> Pending this, and otherwise having exhausted all known alternatives, my findings tell me that either (a) I have made an obvious and idiotic configuration error (for which a history exists) notwithstanding syntax checks and scrupulous attendance to the documentation; or (b) there is a bug in imuxsock (or conceivably input() or ruleset()) concerning its reading or handling of kernel/iptables messages.
>
> So, the questions are
>
> - Whether the conf file, and the imuxsock rule specification in particular, is valid;
> - If not, how to gain ruleset functionality for kernel/iptables messages.  One imagines
> - If so, then whether the conf file in another environment, or an independently sourced conf file with an imuxsock ruleset, elicits the same behavior with kernel/iptables messages.
>
> Hopefully, this clarifies.  Thanks again for your attention.
>
>

**Comment by rgerhards** [comment] 2020-07-09 06:48
side-not: IIRC, imuxsock does *not* read kernel logs (iptables is kernel, again IIRC), this is why imklog exists and is traditionally loaded. The world changed when systemd journal entered the space, and so I do not know precisely any longer. I think journal might push kernel logs to the system log socket (or maybe not, not the least depending on journal config).

**Comment by ebsf1** [comment] 2020-07-09 15:18
iptables indeed prints information to the kernel log.

journald.conf has a directive/option called ReadKMsg, which if enabled processes /dev/kmsg messages generated by the kernel.  By default, this is activated.  I also have expressly enabled it on the systems I am working with.

Also, 

`journalctl -f | grep "\[iptables"`

sends iptables messages to the console, so this establishes that systemd-journald is sending kernel messages.

I am just starting my day and have some other demands, but hope to reinstall rsyslog on the U16.04 system from the OBS repository now that I've figured out the pubkey issue.  I understand that imkmesg is included in that distribution (it is absent from others) and if so, hope to test whether substituting imkmesg for imklog has any effect.  Depending on behavior, this may further isolate the cause of the failure.

**Comment by rgerhards** [comment] 2020-07-09 15:24
> this may further isolate the cause of the failure.

I still don't see the exact failure. Did you do a basic dumb install where you dump everything in a single file? I would bet that the messages are there if they are forwarded by the journal.

**Comment by ebsf1** [comment] 2020-07-09 15:30
@davidelang , thanks.  I'll take a crack at that presently and advise.

Do know that iptables is implemented in the kernel and not as a separate application.  Consequently, for iptables log messages, $programname is 'kernel', $syslogtag is 'kernel:', and $app-name is 'kernel'.  The iptables LOG target and its --log-prefix option permit configuration of a string with which to prefix log messages for matching packets.  This allows filtering of log messages on that string.

**Comment by ebsf1** [comment] 2020-07-09 15:38
@rgerhards , among the filters I test in the experimental config file (both in and out of an imuxsock ruleset) are:

```
if prifilt("*.*") then {
		action(
			name="act.facility-all"
			type="omfile"
			dynafile="tpl.df-syslog"
		)
	}
```

and

`*.*;auth,authpriv.none		-/var/log/imuxsock-syslog`

and 

`*.*;auth,authpriv.none		action(name="act.standalone-syslog" type="omfile" file="/var/log/standalone-syslog-modern")`

In each case, the rule fails when in an imuxsock ruleset and operates when standalone.  By "fails," I mean that no iptables messages are written.

**Comment by rgerhards** [comment] 2020-07-09 16:45
> In each case, the rule fails when in an imuxsock ruleset and operates when standalone. By "fails," I mean that no iptables messages are written.

please forgive my ignorance, but this cannot be. Which ruleset processes messages is not relevant. Please strip the config down to just 5 lines with which write everything. Then add 2 lines for the ruleset. If that doesn't work, pls create a debug log. This would indicate a very serious problem inside rsyslog.

**Comment by onet-git** [comment] 2020-07-09 22:53
journald offers forwarding to syslog, kmsg, console, and wall. However, it will only forward log messages it receives from the traditional syslog socket. So while journald collects and stores other logs (e.g. kernel logs) there is no option to enable forwarding of those message.

There have been open bugs about this since 2016 and the systemd developers have indicated that it is working at intended. They believe journald should not forward non-syslog messages. Having looked at the code, forwarding non-syslog messages  would require a non-trivial architectural change to journald.

https://github.com/systemd/systemd/issues/2866
https://github.com/systemd/systemd/issues/5129

To answer your question, to get kernel messages in rsyslog you have two options:

1) enable imkmsg so rsyslog can reads kernel messages directly.
2) disable imuxsock and instead use imjournal to read the raw journal directly.

Option #1 is the recommended configuration, but #2 should also work.

**Comment by ebsf1** [comment] 2020-07-10 06:02
@onet-git , thanks.

What I have found is that the journald.conf directive ReadKMsg, if enabled, causes systemd-journald to process /dev/kmsg messages generated by the kernel.

These messages are, in turn, read by standalone rules in rsyslog.conf, even if not by clones of the same rules in an imuxsock ruleset.  So, it seems that to this extent, kernel messages can be configured to get to rsyslog.

**Comment by ebsf1** [comment] 2020-07-10 06:10
@rgerhards , 

> This would indicate a very serious problem inside rsyslog.

This is my conclusion, too.  Attached are the conf file as you specified, and the debug file.

In this case, the imuxsock ruleset displayed general failure, meaning no files were written at all, while each of the standalone rules operated.

I did a few permutations and could get no rule to operate in the imuxsock ruleset.

I also observed that substituting imkmsg for imklog had no effect, meaning that imuxsock rules still failed and the standalone rules operated similarly.


[rsyslog.debug.txt](https://github.com/rsyslog/rsyslog/files/4901282/rsyslog.debug.txt)
[rsyslog.conf.1.txt](https://github.com/rsyslog/rsyslog/files/4901283/rsyslog.conf.1.txt)

**Comment by onet-git** [comment] 2020-07-10 13:23
You are assuming that because journald reads message from `/dev/kmsg` it will forward them to `/run/systemd/journal/syslog`, the socket which `imuxsock` reads. This assumption is incorrect. There is no configuration of journald where that can be true. The documentation in journald.conf(5) is misleading about this, which why there are open bugs reports against journald about it. 

To repeat, this is not a bug in rsyslog,it is how journald works. Your debug report confirms this true, the kernel messages are never seen by `imuxsock`, because journald never wrote them to `/run/systemd/journal/syslog`.

The simplest way to have rsyslog process `/dev/kmsg` messages is the change you already made, tell rsyslog to read from `/dev/kmsg` in addition to `/run/systemd/journal/syslog`.

 `module(
	load="imklog"
	permitnonkernelfacility="on"
)
`

That are other ways to get the the kernel messages to rsyslog, this just happens to be the easiest.

**Comment by onet-git** [comment] 2020-07-10 13:26
To quote https://www.freedesktop.org/wiki/Software/systemd/syslog/:

`(BTW, journald is smart enough not to forward the kernel messages it gets to you, you should read that on your own, directly from /proc/kmsg, as you always did. It's also smart enough never to forward kernel messages back to the kernel, but that probably shouldn't concern you too much...)`

**Comment by ebsf1** [comment] 2020-07-10 20:12
@onet-git , thanks.

I think we concur that imuxsock is not reading the kernel messages.

I actually have no idea how or where to discern this from the debug log, and would genuinely appreciate your pointing out what to look for.

This said, I don't believe I'm making any assumptions about systemd-journald.  I also don't have any reason to question your observations about it, its documentation, or developers.  I agree that it fundamentally fails if it can't or won't forward kernel messages and especially if the destination can't be configured.  Any idiot knows that the distinction between kernel and "syslog" messages, not to mention even the concept of a socket, is lost on the overwhelming majority of people wading into this mess just attempting to get their systems to work.  Doing this intentionally and hiding references in an arcane wiki is oblivious, and puts the daemon into the category of cute but unreliable coding project of dubious utility to its actual clientele.

Regardless, I do observe that kernel/iptables messages are being read by standalone rsyslog rules, even if not by identical rules in an imuxsock ruleset.  So, systemd-journald somehow is managing to get kernel/iptables messages to rsyslog, in this configuration.  The fact that things are functioning to this point is why I say I'm making no assumptions about systemd-journald, although I do take your point about how its configuration operates, or not.

Concerning imuxsock, however, no documentation or reason exists to think that imuxsock listens only on /run/systemd/journal/syslog.  On the contrary, the imuxsock documentation states:

> This module provides the ability to accept syslog messages from applications running on the local system via Unix sockets.

Note the plural "sockets", and also that it does not specify any specific socket path or the "system socket".  By itself, this means all local log sockets and clearly that is its intent.  The implementation may fall short in reality, but nevertheless.  To remove all doubt, imklog exists, however redundantly, and its documented purpose is:

> Reads messages from the kernel log and submits them to the syslog engine.

Meaning, obviously, to imuxsock not only because that is what its documentation states, but also because imuxsock is the only local listener to accept rulesets, which are fundamental to the rsyslog modern syntax, of which imuxsock is a central part.

Also, no one has managed to say "imuxsock does not read kernel messages."  Instead, the response has been, "send configs and debug logs," not to mention:

> This would indicate a very serious problem inside rsyslog.

from @rgerhards Himself.

Finally, local iptables logging, above all else, would seem to be the most elementary and fundamental capability of any log daemon, and the means of configuring it for such should be simple, obvious, and well-documented.  If not, or the solution is buried in arcane blogs, or requires months of experimentation to discern, then again,

> This would indicate a very serious problem ...

So, unless my configuration is incorrect, and notwithstanding the unflattering picture of systemd-journald and its developers that you paint, it seems there is an issue with imuxsock.

Now, from our exchange, it may emerge that the solution is simply conforming imuxsock to its documentation and intent by getting it listening on all log sockets, either by default or if necessary, by express configuration of imklog or imkmsg.  I'm not a developer but I imagine this would be relatively straightforward if it doesn't exist.  Or, maybe it's a bug that needs fixing.  Regardless, fixing this issue will reinforce the purpose of rsyslog modern syntax, which is to improve the elegance and function of rsyslog configuration.

Again, thanks.

**Comment by rgerhards** [comment] 2020-07-10 20:24
You are misquoting me: I said that something is seriously wrong when a basic 5 line config with imuxsock works differently if and only if the only difference is the presence of a named rule set or not. I did not yet have time to craft the basic config and conduct the test and actually think this is your chore. Especially given the fact that multiple people tell you that what you want to do does not work in that way.

Btw imuxsock listens to multiple sockets if you configure it to do so. But the kernel log is not using a socket at all.  That's why we have imklog and it's predecessor since roughly 30 years.

**Comment by davidelang** [comment] 2020-07-10 20:54
This is where the template RSYSLOG_DebugFormat would help

it will show (among other things) what input the log is arriving through.

so if you can create the simple rule and log via the debug template, it would 
really help

**Comment by ebsf1** [comment] 2020-07-10 22:46
@rgerhards 

> You are misquoting me

Apologies

I am happy to develop another config, and to do all the testing.  The last one was substantially streamlined from its predecessor and I thought it would give you what you need, but apparently not.  I'll take it down further as you suggest.

I also will configure for the RSYSLOG_DebugFormat template as @davidelang requested, and will post the log file that is generated.  That will add some lines but presumably that will be acceptable.

To be clear, I am especially grateful for the input.  All I have to go on otherwise is the documentation, experimentation, and intuition.

**Comment by ebsf1** [comment] 2020-07-11 01:06
Attached is:
- A basic rsyslog.conf file with lines for only the module objects, ruleset, input object, and standalone rule.
- A configuration check file, with the output from rsyslogd -N1
- The log file that resulted from the standalone rule, which includes kernel/iptables messages and others, in RSYSLOG_DebugFormat.
- The debug log file.

As before, the file specified in the ruleset did not write at all.

Hopefully, this gives you what you need.

[all-standalone.log](https://github.com/rsyslog/rsyslog/files/4906025/all-standalone.log)
[rsyslog.conf.txt](https://github.com/rsyslog/rsyslog/files/4906026/rsyslog.conf.txt)
[rsyslog.debug.txt](https://github.com/rsyslog/rsyslog/files/4906027/rsyslog.debug.txt)
[rsyslog.conf-config-check.txt](https://github.com/rsyslog/rsyslog/files/4906036/rsyslog.conf-config-check.txt)

**Comment by rgerhards** [comment] 2020-07-11 09:08
@ebsf1 Thx for the input. Please note that I am having quite a ton of tasks to do at my hand - there currently is very little help (myabe due to Covid). That's a prime reason I need your cooperation. The other one is that, as you already saw with packages, some things may only reproduce on very specific environments.

**read down below first**

To help us get to some clear facts, let me propose some even simpler steps. Please create a config that only consists of these two  lines:
```
module(load="imuxsock")
action(type="omfile" file="/var/log/everything")
```
Just this and nothing else. No debug log, no extra template. Let that run and check if kernel messages are really present. If so, pls post an excerpt of the messages you see.

If you do not see kernel messages, we have a final state and are done with the testing.

If you see kernel messages, a second step possibly is:
```
module(load="imuxsock")
action(type="omfile" file="/var/log/everything.msgdebug" template="RSYSLOG_DebugFormat")
```
again, it would be good to see the content if kernel messages show up. Seeing the log then helps.

If step 1 showed kernel messages, step 2 should also show them. So a third step....

ahem.... I see in your config is invalid and generates this error message: `error during parsing file /etc/rsyslog.conf, on or before line 28: parameter 'socket' required but not specified - fix config` - is this your problem?

If you think now, please do the steps I proposed above (let's talk about step 3 when we are done, no point in spending more time if you config error is already the problem cause).

**Comment by ebsf1** [comment] 2020-07-13 21:51
@rgerhards , more than happy to cooperate.

I ran the experiment you suggested and a few permutations, which may suggest some of the issues.

Initially, the error message that you point out has been present ever since I began attempting to configure rsyslog, regardless of package.  The only way to remove it is to expressly include a socket directive in the input() object for imuxsock, specifying the system socket expressly.  (Note also that this directive is NOT mandatory according to the documentation.)  -->BUT, this is absent with the first configuration, as follows:

I ran five experiments:

- Case 1:  The two-line configuration file you suggested.  NOTE that the action statement is what I have been calling a "standalone" rule, because it is not in a ruleset.
- Case 2:  Case 1 plus loading imklog.
- Case 3:  Case 2 plus an imuxsock input() object and a named ruleset containing a clone of the standalone action statement.
- Case 4:  Case 3 with a "socket" parameter in the input() object, specifying the system socket.
- Case 5:  Case 4 with the log files configured to be in debug format.

The results were:

- Case 1:  No kernel messages in the log file.  No errors in the configuration check.
- Case 2:  Kernel messages including iptables messages, appear in the log file.  No errors in the configuration check.
- Case 3:  Kernel messages including iptables messages appear in the standalone log file.  No file is written according to the action statement in the ruleset.  The same error message concerning the absence of a "socket" parameter, appears.
- Case 4:  Kernel messages including iptables messages appear in the standalone log file.  A ruleset-configured log file exists but includes no kernel messages, and far fewer messages generally.  No errors in the configuration check.
- Case 5:  Same as Case 4.

I believe (subject to others' input) the experiments establish that:

- Case 2 tells us loading imklog is necessary and sufficient for rsyslog to read kernel messages with standalone rules.  No surprise.
- Cases 3 & 4 tell us that, contrary to the documentation, input(socket) is mandatory, even for the system socket /run/systemd/journal/syslog, because no file is written without it.  The documentation is wrong.
- Case 4 tells us that loading imklog is insufficient to configure input() or imuxsock to read kernel messages.  This surprises me, at least.

Also:
- neither imklog nor imkmsg have any known input parameters (including ruleset); and 
- input(type="imklog" ... ) is not a valid configuration (according to syntax check).

Some or all of this may be by design but (subject to others' guidance or input) my tentative conclusions seem to be:
- I believe that no means currently exists within "modern" rsyslog syntax to consolidate all message streams.  The rsyslog engine does this, which may be its most fundamental achievement, but currently, neither input() nor imuxsock is a proxy for all that rsyslog receives.  (Separately, I have tested listeners on other obvious sockets, without success.)
- Practically, I believe this means that ruleset functionality is not available for kernel messages and other message streams that are not consolidated because imuxsock is the only local listener to support rulesets (although a roundabout hack involving imfile may exist).  Standalone rules seem to be the only means to process kernel messages, etc.  So, log configuration depends on a mix of "modern" syntax (for the system socket, if configured) and standalone rules (for everything else), which may be redundant or more complex.  Consolidation into a single algorithm with rulesets isn't yet possible.

This is where the experimentation leads me, at least.  I'd welcome any thoughts.

Case 1 files:
[rsyslog.conf-1.txt](https://github.com/rsyslog/rsyslog/files/4915179/rsyslog.conf-1.txt)
[rsyslog.conf-1-config-check.txt](https://github.com/rsyslog/rsyslog/files/4915180/rsyslog.conf-1-config-check.txt)
[alles.log.txt](https://github.com/rsyslog/rsyslog/files/4915161/alles.log.txt)

Case 2 files:
[rsyslog.conf-2.txt](https://github.com/rsyslog/rsyslog/files/4915181/rsyslog.conf-2.txt)
[rsyslog.conf-2-config-check.txt](https://github.com/rsyslog/rsyslog/files/4915182/rsyslog.conf-2-config-check.txt)
[alles.log-2.txt](https://github.com/rsyslog/rsyslog/files/4915162/alles.log-2.txt)

Case 3 files:
[rsyslog.conf-3.txt](https://github.com/rsyslog/rsyslog/files/4915183/rsyslog.conf-3.txt)
[rsyslog.conf-3-config-check.txt](https://github.com/rsyslog/rsyslog/files/4915184/rsyslog.conf-3-config-check.txt)
[alles-standalone.log.txt](https://github.com/rsyslog/rsyslog/files/4915166/alles-standalone.log.txt)

Case 4 files:
[rsyslog.conf-4.txt](https://github.com/rsyslog/rsyslog/files/4915185/rsyslog.conf-4.txt)
[rsyslog.conf-4-config-check.txt](https://github.com/rsyslog/rsyslog/files/4915186/rsyslog.conf-4-config-check.txt)
[alles-ruleset-socket.log](https://github.com/rsyslog/rsyslog/files/4915163/alles-ruleset-socket.log)
[alles-standalone-socket.log](https://github.com/rsyslog/rsyslog/files/4915167/alles-standalone-socket.log)

Case 5 files:
[alles-ruleset-socket-debug.log](https://github.com/rsyslog/rsyslog/files/4915164/alles-ruleset-socket-debug.log)
[alles-standalone-socket-debug.log](https://github.com/rsyslog/rsyslog/files/4915168/alles-standalone-socket-debug.log)

**Comment by rgerhards** [comment] 2020-07-14 06:46
OK, based on your conclusion I haven't looked at the log files - because conclusion is exactly how it is supposed to work. I think the whole thread boils down to the fact that you would like imklog to have a ruleset parameter and be converted to modern syntax. Sounds reasonable, but you are the first person to ask so, at least in the last couple of years.

You can consolidate things if you use the default ruleset for imklog message. I'll have a look what it takes to do the conversion - it's a long time since I did last, so this may take a bit.

**Comment by rgerhards** [comment] 2020-07-14 06:47
duplicate of #106

**Closed by rgerhards** 2020-07-14 06:47 UTC

**Comment by ebsf1** [comment] 2020-07-14 13:34
@rgerhards , thanks.

Apart from imklog/imkmsg, do note the input(socket) issue (Cases 3 & 4) because behavior and documentation (both for the parameter and the discussion about interface with systemd) conflict.

**Comment by rgerhards** [comment] 2020-07-14 13:57
I did a check:

* case 3 is an invalid config, what you can see in rsyslog's error message. the `socket` parameter is missing for the input.
* in case 4 you define an additional input for, I guess, the same socket. I see no error is reported, which indeed smells a bit like a bug in error reporting

For case 4 it depend on systemd configuration, of course. I think a misunderstanding here is that imuxsock traditionally starts a default listener for the system log socket if not instructed otherwise. What the "system log socket" is depend on the configuration. The doc tries to describe common options, but there is a myriad of combinations, which is hard to foresee.

That said, it would be useful if you could point to where exactly you think the doc is wrong. Best with a proposal (or PR) and what should be changed inside the doc.

**Comment by ebsf1** [comment] 2020-07-15 13:46
@rgerhards , I'll be happy to get you some proposed alternative text but will need a day or two because of some other commitments.

There is a bit of a curiosity in error reporting or behavior that turns up in the operating state file, perhaps among other places, and I will want to get an example of that to you.

**Comment by rgerhards** [comment] 2020-07-16 06:40
> There is a bit of a curiosity in error reporting or behavior that turns up in the operating state file, perhaps among other places, and I will want to get an example of that to you.

feel free to post, I'll have a look at them.

**Comment by ebsf1** [comment] 2020-07-18 02:25
@rgerhards the curiosity in error reporting or behavior appears in the attached rsyslog operating state file.  I will need to understand this to propose alternative language for the documentation.

The attached operating state file was generated using the attached rsyslog.conf file (a) first without the imuxsock input(socket) parameter; and (b) second, with the imuxsock input(socket) parameter specifying the system socket /run/systemd/journal/syslog.  These are Case 3 and Case 4, above, with additional lines to configure the operating state file.

The operating state file (in the first initialization, without input(socket)) gives opposing information-first that the parameter is required, and then that imuxsock acquires the socket without it.  For the second initialization (with input(socket)), imuxsock acquires the socket twice, for unknown reasons.

Also, your statements above seem to oppose:

> case 3 is an invalid config, what you can see in rsyslog's error message. the socket parameter is missing for the input.

Then, you state:

> I think a misunderstanding here is that imuxsock traditionally starts a default listener for the system log socket if not instructed otherwise. 

So, why is omitting input(socket) for the system log socket invalid if imuxsock starts a default listener on the system log socket?

These statements seem to oppose, as do the messages in the operating state file.

Again, I will need to understand this before suggesting alternative text for the imuxsock "[Coexistence with Systemd](https://www.rsyslog.com/doc/v8-stable/configuration/modules/imuxsock.html#imuxsock-systemd-details-label)" section.

Also, this will clarify whether [documentation](https://www.rsyslog.com/doc/v8-stable/configuration/modules/imuxsock.html#socket) for the imuxsock "socket" Input parameter should continue to reflect "mandatory-no" or be changed to "mandatory-yes", among other changes.

Please advise.  Thanks

[rsyslog.conf.txt](https://github.com/rsyslog/rsyslog/files/4940963/rsyslog.conf.txt)
[rsyslog.opg-state1.txt](https://github.com/rsyslog/rsyslog/files/4940964/rsyslog.opg-state1.txt)
