### ISSUE TITLE
impstats TCP forward queue counter not appropriate

### ISSUE THREAD

**Issue by skupkosk** [rsyslog/rsyslog#1585] opened 2017-05-26 12:45 UTC
Just recognized issue with the statistics logged by impstats for the forward in-memory queues.
Discovered this before when trying to do proper sizing for rsyslog server ( http://lists.adiscon.net/pipermail/rsyslog/2017-April/044334.html ). The statistics from the stats file shows the increase of the queue size and then it is reset back to 0 for not known reason.
Did the test and it confirmed the queue size counter doesn't show the actual size of the in-memory queue.

```
May 26 13:50:58 islab-proxy rsyslogd-pstats: TCPFWD2514 queue: size=3 enqueued=235741 full=0 discarde
d.full=0 discarded.nf=0 maxqsize=10345
May 26 13:51:03 islab-proxy rsyslogd-pstats: TCPFWD2514 queue: size=4 enqueued=235863 full=0 discarde
d.full=0 discarded.nf=0 maxqsize=10345
May 26 13:51:08 islab-proxy rsyslogd-pstats: TCPFWD2514 queue: size=10 enqueued=235991 full=0 discarded.full=0 discarded.nf=0 maxqsize=10345
May 26 13:51:13 islab-proxy rsyslogd-pstats: TCPFWD2514 queue: size=61 enqueued=236116 full=0 discarded.full=0 discarded.nf=0 maxqsize=10345
.....
May 26 13:52:08 islab-proxy rsyslogd-pstats: TCPFWD2514 queue: size=1388 enqueued=237443 full=0 discarded.full=0 discarded.nf=0 maxqsize=10345
May 26 13:52:13 islab-proxy rsyslogd-pstats: TCPFWD2514 queue: size=1518 enqueued=237574 full=0 discarded.full=0 discarded.nf=0 maxqsize=10345
May 26 13:52:18 islab-proxy rsyslogd-pstats: TCPFWD2514 queue: size=1635 enqueued=237690 full=0 discarded.full=0 discarded.nf=0 maxqsize=10345
May 26 13:52:23 islab-proxy rsyslogd-pstats: TCPFWD2514 queue: size=1757 enqueued=237812 full=0 discarded.full=0 discarded.nf=0 maxqsize=10345
May 26 13:52:28 islab-proxy rsyslogd-pstats: TCPFWD2514 queue: size=1870 enqueued=237925 full=0 discarded.full=0 discarded.nf=0 maxqsize=10345
.....
May 26 13:53:08 islab-proxy rsyslogd-pstats: TCPFWD2514 queue: size=2841 enqueued=238896 full=0 discarded.full=0 discarded.nf=0 maxqsize=10345
May 26 13:53:13 islab-proxy rsyslogd-pstats: TCPFWD2514 queue: size=2955 enqueued=239010 full=0 discarded.full=0 discarded.nf=0 maxqsize=10345
May 26 13:53:18 islab-proxy rsyslogd-pstats: TCPFWD2514 queue: size=0 enqueued=239139 full=0 discarded.full=0 discarded.nf=0 maxqsize=10345
```

It looks like the counter reset occur every 3 minutes:
```
May 26 13:01:30 0
May 26 13:04:00 3000
May 26 13:04:05 0
May 26 13:07:06 2968
May 26 13:07:11 0
May 26 13:10:16 3062
May 26 13:10:21 0
May 26 13:13:21 2991
May 26 13:13:26 0
```

**Test scenario was as follows:**
 - configure and start sender and receiver for simple TCP forward (no keepalive, no tunning, only TCP forward)
 - block the communication on receiver side (iptables DROP on port)
 - sender started queuing messages (with counter reset after some minutes)
 - permit the communication back on receiver side
 - count the messages on receiver side

**The results were:**
 - **queue size** on sender size showed **2985** messages
 - **+68820 messages** (most of them 2kB in size) **retrieved** from sender on receiver side in 4 second burst after the TCP transport tunnel was recovered

Please, check the statistic gathering for queues.
Rsyslog version tested 8.4.2-1+deb8u2.

**Comment by skupkosk** [comment] 2017-05-26 14:00
Just digg deeper into this issue and found the counter reset occur when the rsyslog retry to open connection. With the counter reset the TCP socket is closed and reopened new one falling into SYN_SENT state.
This might help to find the root cause in code.

Counter reset between 15:48:17 and 15:48:22 in GMT+2
```
May 26 15:48:17 islab-proxy rsyslogd-pstats: TCPFWD2514 queue: size=2959 enqueued=16082 full=0 discarded.full=0 discarded.nf=0 maxqsize=4785
May 26 15:48:22 islab-proxy rsyslogd-pstats: TCPFWD2514 queue: size=0 enqueued=16209 full=0 discarded.full=0 discarded.nf=0 maxqsize=4785
```
and socket close between 15:48:17 and 15:48:22:
```
~# while true; do ss -t -a -o state all dst 10.x.y.111 > ss.$(date +%s); sleep 5; done &
~# cat ss.1495806497
State      Recv-Q Send-Q      Local Address:Port          Peer Address:Port
SYN-SENT   0      1              10.x.y.7:52333         10.x.y.111:2514     timer:(on,4.748ms,6)
~# cat ss.1495806502
State      Recv-Q Send-Q      Local Address:Port          Peer Address:Port
~# #this is the first occurrence of the new socket opened
~# cat ss.1495806532
State      Recv-Q Send-Q      Local Address:Port          Peer Address:Port
SYN-SENT   0      1              10.x.y.7:52334         10.x.y.111:2514     timer:(on,620ms,0)
```

**Comment by rgerhards** [comment] 2017-05-29 06:55
You actually mean the queue size counter? If so, this counter must be correct, because it is the same counter that the queue system uses internally to keep track of how many messages are present. Seeing your full config might help to understand what is going on in 3-minute intervals.

**Comment by davidelang** [comment] 2017-05-29 09:16
does the count of processed messages for the actions match the inputs and queue 
sizes?

**Comment by skupkosk** [comment] 2017-05-30 12:19
These are the configuration files. It is on Debian 8.
Main configuration file:
```
~# cat /etc/rsyslog.conf
$ModLoad imuxsock # provides support for local system logging
$ModLoad imklog   # provides kernel logging support
$ModLoad imudp
$UDPServerRun 9514
$ModLoad imtcp
$InputTCPServerRun 9514
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$FileOwner root
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$WorkDirectory /var/spool/rsyslog
$IncludeConfig /etc/rsyslog.d/*.conf
auth,authpriv.*                 /var/log/auth.log
daemon.*                        -/var/log/daemon.log
kern.*                          -/var/log/kern.log
lpr.*                           -/var/log/lpr.log
mail.*                          -/var/log/mail.log
mail.info                       -/var/log/mail.info
mail.warn                       -/var/log/mail.warn
mail.err                        /var/log/mail.err
news.crit                       /var/log/news/news.crit
news.err                        /var/log/news/news.err
news.notice                     -/var/log/news/news.notice
*.=debug;\
        auth,authpriv.none;\
        news.none;mail.none     -/var/log/debug
*.=info;*.=notice;*.=warn;\
        auth,authpriv.none;\
        cron,daemon.none;\
        mail,news.none;\
        user.none               -/var/log/messages
*.emerg                         :omusrmsg:*
daemon.*;mail.*;\
        news.err;\
        *.=debug;*.=info;\
        *.=notice;*.=warn       |/dev/xconsole
```
Forward configuration
```
~# awk '!/^#|^$/' /etc/rsyslog.d/forward-1.conf
$ActionQueueFileName forward1
$ActionQueueType LinkedList
$ActionQueueSaveOnShutdown on
$ActionQueueSize 150000
$ActionQueueMaxDiskSpace 50m
$ActionQueueHighWaterMark 130000
$ActionQueueLowWaterMark 100000
$ActionName TCPFWD2514
*.*     @@10.x.y.111:2514
```
Main queue configuration
```
~# awk '!/^#|^$/' /etc/rsyslog.d/main-queue.conf
$MainMsgQueueFileName main_queue
$MainMsgQueueSize 1000000
$MainMsgQueueHighWaterMark 600000
$MainMsgQueueLowWaterMark 100000
$MainMsgQueueMaxDiskSpace 1000m
$MainMsgQueueDiscardMark 950000
$MainMsgQueueSaveOnShutdown on
```
Stats configuration
```
~# awk '!/^#|^$/' /etc/rsyslog.d/stats.conf
$ModLoad impstats
$PStatInterval 5
$PStatSeverity 7
syslog.=debug -/var/log/rsyslog-stats
& stop
```

**Comment by rgerhards** [comment] 2017-05-30 16:41
Judging from the config excerpt, I would say the 3-minute timeout is when the action fails, which will run all messages in "failed mode", aka "throw away".

**Comment by skupkosk** [comment] 2017-06-01 08:50
I am able to reproduce this on rsyslog 8.4.2 in Debian. On the sender side the local file destination was added to the end of the forward-1.conf file to be able to check the counts of messages from files on both ends:
`local7.info     -/var/log/test.log`

<img width="423" alt="rsyslog-queue-port-drop-pub" src="https://cloud.githubusercontent.com/assets/8864662/26671698/c38c57fe-46b6-11e7-9853-b9fba327f88a.png">

These is the scenario with timeframes:
9:51 restarted rsyslogs
9:52 start logging
9:53 blocked port with drop
 <queue is increasing> TCP socket tx queue size 104848B
10:10 TCP socket restart <in SYN_SENT state> TCP socket tx queue size 1B
10:12 TCP socket restart <in SYN_SENT state> TCP socket tx queue size 1B
10:15 uncblocked port
10:16 queue emptied
10:17 stopped logging

summary: number of received messages 24023 and sent 28427
4404 messages lost

On the receiver side the last message before drop was received at
09:53:02
and first message after unblocking port at
10:16:24

At 10:10:39 the QSIZE is reset from 19982 to 0 and no message is received on the receiver side. This happen at 10:16:24 once the port is unblocked.
Might be related to socket in EINPROGRESS state, but not sure.
Port is blocked with simple DROP of all incoming packets for the receiver TCP port.

**Comment by rgerhards** [comment] 2017-06-01 08:52
As I said, this is expected behaviour as you do not configure the retryResumeInterval, which means messages are simply failed when the send times out. See doc here (for example):

http://www.rsyslog.com/doc/v8-stable/tutorials/reliable_forwarding.html

**Comment by skupkosk** [comment] 2017-06-01 09:03
I do not care of the lost messages at the moment, but the queue size provided by the impstats.
It fall down, but the messages not received and remained somewhere on the sender side.

These are the stats before the QSIZE reset:
```
Jun  1 10:10:39 sender rsyslogd-pstats: imuxsock: submitted=21152 ratelimit.discarded=0 ratelimit.numratelimiters=0
Jun  1 10:10:39 sender rsyslogd-pstats: TCPFWD2514: processed=21150 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 2: processed=21150 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 3: processed=6636 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 4: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 5: processed=2 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 6: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 7: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 8: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 9: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 10: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 11: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 12: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 13: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 14: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 15: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 16: processed=21152 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 17: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: action 18: processed=21154 failed=0 suspended=1 suspended.duration=1170 resumed=0
Jun  1 10:10:39 sender rsyslogd-pstats: imudp(*:9514): submitted=0
Jun  1 10:10:39 sender rsyslogd-pstats: imudp(*:9514): submitted=0
Jun  1 10:10:39 sender rsyslogd-pstats: imtcp(9514): submitted=0
Jun  1 10:10:39 sender rsyslogd-pstats: resource-usage: utime=1304000 stime=1972000 maxrss=55856 minflt=13565 majflt=0 inblock=0 o
ublock=170832 nvcsw=44585 nivcsw=2
Jun  1 10:10:39 sender rsyslogd-pstats: TCPFWD2514 queue[DA]: size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0
Jun  1 10:10:39 sender rsyslogd-pstats: TCPFWD2514 queue: size=19982 enqueued=21150 full=0 discarded.full=0 discarded.nf=0 maxqsize=19982
Jun  1 10:10:39 sender rsyslogd-pstats: main Q[DA]: size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0
Jun  1 10:10:39 sender rsyslogd-pstats: main Q: size=26 enqueued=27818 full=0 discarded.full=0 discarded.nf=0 maxqsize=29
Jun  1 10:10:39 sender rsyslogd-pstats: imudp(w0): called.recvmmsg=0 called.recvmsg=0 msgs.received=0
```
and these right after QSIZE reset
```
Jun  1 10:10:44 sender rsyslogd-pstats: imuxsock: submitted=21247 ratelimit.discarded=0 ratelimit.numratelimiters=0
Jun  1 10:10:44 sender rsyslogd-pstats: TCPFWD2514: processed=21245 failed=0 suspended=1 suspended.duration=30 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 2: processed=21245 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 3: processed=6664 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 4: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 5: processed=2 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 6: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 7: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 8: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 9: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 10: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 11: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 12: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 13: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 14: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 15: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 16: processed=21248 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 17: processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: action 18: processed=21250 failed=0 suspended=1 suspended.duration=1170 resumed=0
Jun  1 10:10:44 sender rsyslogd-pstats: imudp(*:9514): submitted=0
Jun  1 10:10:44 sender rsyslogd-pstats: imudp(*:9514): submitted=0
Jun  1 10:10:44 sender rsyslogd-pstats: imtcp(9514): submitted=0
Jun  1 10:10:44 sender rsyslogd-pstats: resource-usage: utime=1356000 stime=1988000 maxrss=96572 minflt=23832 majflt=0 inblock=0 oublock=171608 nvcsw=44847 nivcsw=2
Jun  1 10:10:44 sender rsyslogd-pstats: TCPFWD2514 queue[DA]: size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0
Jun  1 10:10:44 sender rsyslogd-pstats: TCPFWD2514 queue: size=0 enqueued=21245 full=0 discarded.full=0 discarded.nf=0 maxqsize=20010
Jun  1 10:10:44 sender rsyslogd-pstats: main Q[DA]: size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0
Jun  1 10:10:44 sender rsyslogd-pstats: main Q: size=26 enqueued=27942 full=0 discarded.full=0 discarded.nf=0 maxqsize=29
Jun  1 10:10:44 sender rsyslogd-pstats: imudp(w0): called.recvmmsg=0 called.recvmsg=0 msgs.received=0
```

I need to implement the QSIZE and RSS monitoring for rsyslog processes and impstats outputs are the only I can rely on.

**Comment by skupkosk** [comment] 2017-06-01 09:37
```
Jun  1 10:10:40 sender rsyslogd-2007: action 'TCPFWD2514' suspended, next retry is Thu Jun  1 10:11:10 2017 [try http://www.rsyslog.com/e/2007 ]
Jun  1 10:16:24 sender rsyslogd0: action 'TCPFWD2514' resumed (module 'builtin:omfwd') [try http://www.rsyslog.com/e/0 ]
Jun  1 10:16:24 sender rsyslogd-2359: action 'TCPFWD2514' resumed (module 'builtin:omfwd') [try http://www.rsyslog.com/e/2359 ]
```
Now I understand, the failed messages remain in queue, but are not covered by impstats as they are considered as failed.

**Comment by davidelang** [comment] 2017-06-01 10:25
they don't remain in the queue, when they are considered to have failed. As far 
as the queue is concerned that is the same as if they were delivered on the 
sender side, they are removed from the queue and considered completed.

**Comment by skupkosk** [comment] 2017-06-01 11:07
That sounds interesting. Where are those messages placed? Is it possible to limit the buffer of "failed-mode" messages or let the rsyslog discard them?
Would it make sense to include the stats of these "failed mode" messages in impstats output (as they use rsyslog resources - which is obvious from the increase of RSS in the previously attached image)?

**Comment by rgerhards** [comment] 2017-06-01 14:22
ahhhh... you actually have a different problem: you are investigating a memory leak, right? Rsyslog does not store messages that are done, they are discarded and memory is (should be) freed. The 8.4 version you use is pretty old, released in October 2014. Most probably your problem will go away if you update to the current 8.27.0 version.

**Comment by davidelang** [comment] 2017-06-01 14:48
They aren't placed anywhere.

delivery failures are on a per-action basis, a message can successfully be 
delivered to one action and fail on another action. This info is in the pstats 
data in each action line.

failed messages aren't 'placed' anywhere. When rsyslog finishes processing a 
message (which could be doing nothing with it if that's what the filters on all 
the actions say, or it could be delivering it, or it could be delivering it to 
some actions and failing to delvier it to others), it gets deleted from the 
queues.

**Comment by skupkosk** [comment] 2017-06-02 06:11
Thank you for all your comments.
Will try to test with newer versions of rsyslog and consider opening bug report for Debian package.

**Comment by skupkosk** [comment] 2017-06-02 12:13
Confirm this memory leak (related to handling "failed" messages) is not seen on rsyslog version 8.23.0-2~bpo8+1 from Jessie backports.
Opened [bug report at Debian](https://bugs.debian.org/863962).
You can close this issue.

**Closed** 2017-06-02 12:15 UTC

**Comment by skupkosk** [comment] 2017-06-02 12:31
This is the output from the test with 8.23.0-2~bpo8+1 version with drop of the messages at 13:49.
<img width="423" alt="rsyslog-queue-port-drop-backports-pub" src="https://cloud.githubusercontent.com/assets/8864662/26725615/b392a6de-479f-11e7-9ab9-621a5b2e254d.png">
