### ISSUE TITLE
Switching from GnuTLS to OpenSSL cause imtcp 100% CPU

### ISSUE THREAD

**Issue by deepgroove1000** [rsyslog/rsyslog#5095] opened 2023-02-28 21:53 UTC
### Expected behavior
imtcp thread is using CPU at 20 to 30%
imfile is not writing to log file collected by imtcp.

### Actual behavior
This have similar symptoms to  #4823 except I am switching from GnuTLS to OpenSSL

imtcp thread is using CPU at 100%

![image](https://user-images.githubusercontent.com/126529197/221987028-b54e7298-b8df-40fd-9a4e-901c0a0486b0.png)

checking strace
[pid 715918] read(119,  <unfinished ...>
[pid 715928] <... recvfrom resumed>0x7f1bc13f47c7, 1, MSG_PEEK|MSG_DONTWAIT, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715917] epoll_wait(6,  <unfinished ...>
[pid 715928] write(91, "\27\3\3\0\2642\234#R\316{\254G\366<D\36\1\377\207%9`H0@\353Z\272\215\323\322"..., 185 <unfinished ...>
[pid 715918] <... read resumed>0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715928] <... write resumed>)       = 185
[pid 715928] futex(0x557b714b1e54, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715917] <... epoll_wait resumed>[{events=EPOLLIN, data={u32=3088204880, u64=139757029049424}}], 128, -1) = 1
[pid 715918] read(119,  <unfinished ...>
[pid 715917] recvfrom(142,  <unfinished ...>
[pid 715918] <... read resumed>0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715917] <... recvfrom resumed>"139 <15>Feb 24 09:22:55 hodoam01"..., 131072, 0, NULL, NULL) = 143
[pid 715918] read(119,  <unfinished ...>
[pid 715917] futex(0x557b714e0264, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 715918] <... read resumed>0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715925] <... futex resumed>)       = 0
[pid 715917] <... futex resumed>)       = 1
[pid 715925] futex(0x557b714e0020, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 715918] read(119,  <unfinished ...>
[pid 715925] <... futex resumed>)       = -1 EAGAIN (Resource temporarily unavailable)
[pid 715917] futex(0x557b714e0020, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 715925] futex(0x557b714e0020, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 715918] <... read resumed>0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715925] <... futex resumed>)       = 0
[pid 715917] <... futex resumed>)       = 0
[pid 715925] futex(0x557b714b1e54, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 715918] read(119,  <unfinished ...>
[pid 715928] <... futex resumed>)       = 0
[pid 715925] <... futex resumed>)       = 1
[pid 715917] recvfrom(142,  <unfinished ...>
[pid 715928] futex(0x557b714b1c00, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 715925] futex(0x557b714b1c00, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 715918] <... read resumed>0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715928] <... futex resumed>)       = -1 EAGAIN (Resource temporarily unavailable)
[pid 715925] <... futex resumed>)       = 0
[pid 715917] <... recvfrom resumed>0x7f1bc8403460, 131072, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715928] futex(0x557b714b1c00, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 715925] write(90, "<15>1 2023-02-24T09:22:55-08:00 "..., 158 <unfinished ...>
[pid 715918] read(119,  <unfinished ...>
[pid 715928] <... futex resumed>)       = 0
[pid 715925] <... write resumed>)       = 158
[pid 715917] epoll_ctl(6, EPOLL_CTL_MOD, 142, {events=EPOLLIN|EPOLLONESHOT|EPOLLET, data={u32=3088204880, u64=139757029049424}} <unfinished ...>
[pid 715928] recvfrom(91,  <unfinished ...>
[pid 715925] futex(0x557b714e0260, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 715918] <... read resumed>0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715928] <... recvfrom resumed>0x7f1bc13f47c7, 1, MSG_PEEK|MSG_DONTWAIT, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715917] <... epoll_ctl resumed>)   = 0
[pid 715928] write(91, "\27\3\3\0\2662\234#R\316{\254H\270\266\200\262\370\232\233\303\345h\27\262\211\267\345\355\346[\215"..., 187 <unfinished ...>
[pid 715918] read(119,  <unfinished ...>
[pid 715928] <... write resumed>)       = 187
[pid 715917] epoll_wait(6,  <unfinished ...>
[pid 715928] futex(0x557b714b1e50, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 715918] <... read resumed>0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119, 0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)
[pid 715918] read(119,  <unfinished ...>
[pid 715917] <... epoll_wait resumed>[{events=EPOLLIN, data={u32=3088204880, u64=139757029049424}}], 128, -1) = 1
[pid 715918] <... read resumed>0x7f1bb03653e3, 5) = -1 EAGAIN (Resource temporarily unavailable)

### Steps to reproduce the behavior

global(
    workDirectory="/var/lib/rsyslog"
    maxMessageSize="128K"
    DefaultNetStreamDriver="ossl"
    DefaultNetStreamDriverCAFile="/etc/rsyslog-keys/removed for privacy.pem"
    DefaultNetStreamDriverCertFile="/etc/rsyslog-keys/removed for privacy.pem"
    DefaultNetStreamDriverKeyFile="/etc/rsyslog-keys/removed for privacy.key"
)

module(
    load="imtcp"
    MaxSessions="14096"
    StreamDriver.Name="ossl"
    StreamDriver.Mode="1"
    StreamDriver.AuthMode="anon"
    gnutlsPriorityString="Protocol=ALL,-TLSv1
    MinProtocol=TLSv1.1"
#    PermittedPeer="*"
)

input(
    type="imtcp"
    address="0.0.0.0"
    port="6514"
    ruleset="hive-tls"
)

ruleset(name="hive-tls")
{
    action(
       type="omfwd"
       template="RSYSLOG_SyslogProtocol23Format"
       queue.filename="hive-queue-tls"
       queue.maxdiskspace="10g"
       queue.saveonshutdown="on"
       queue.size="250000"
       queue.type="fixedArray"
       action.resumeRetryCount="-1"
       queue.dequeueBatchSize="4096"
       target="removed for privacy"
       protocol="tcp"
       port="1515"
       StreamDriver="ossl"
       StreamDriverMode="1"
       StreamDriverAuthMode="anon"
    )

    action(
       type="omfile"
       template="RSYSLOG_SyslogProtocol23Format"
       file="/var/log/rsyslog/hive-tls.log"
    )
}

### Environment

rsyslogd  8.2102.0-7.el8_6.1 (aka 2021.02) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/rsyslogd.pid
        Number of Bits in RainerScript integers: 64

**Comment by alorbach** [comment] 2023-03-02 10:59
Can you test this with the current version? I think this was caused by an unhandeled underlaying socket error fixed in this commit:
https://github.com/rsyslog/rsyslog/commit/7cb9038288a1fe7cdea79c083e07f3637222abfa

**Closed** 2023-03-16 21:00 UTC
