### ISSUE TITLE
Log error message when log over $MaxMessageSize

### ISSUE THREAD

**Issue by daniftodi** [rsyslog/rsyslog#2772] opened 2018-06-13 08:46 UTC
### Expected behavior
Log error message when log over $MaxMessageSize
### Actual behavior
Truncates log message
### Steps to reproduce the behavior
Log a message with size over $MaxMessageSize
### Environment
- rsyslog version: 8.35.0
- platform: Centos 7

This is not a bug, it's a feature that I'm trying to achieve if possible. I need to configure **rsyslogd** to log an error message if logged message size is over $MaxMessageSize.

Is this possible?

Thank you.

**Comment by rgerhards** [comment] 2018-06-13 15:44
Can you be a bit more precise with reproduction steps. We just added such a message, so it would be good to know on which path none is emitted (e.g. imuxsock, imptcp, ...).

**Comment by daniftodi** [comment] 2018-06-14 11:03
@davidelang  could you give an example please?

@rgerhards steps to reproduce this:
1. Set $MaxMessageSize to 255
2. Log a message with size greater than 255 ( ex: 512 )

**Comment by rgerhards** [comment] 2018-06-14 11:16
Can you be a bit more precise with reproduction steps. We just added such a message, so it would be good to know on which path none is emitted (e.g. imuxsock, imptcp, ...).

**Comment by davidelang** [comment] 2018-06-14 18:19
On Thu, 14 Jun 2018, Dan Iftodi wrote:

> @davidelang  could you give an example please?

set maxmessagesize = 256
if len($rawmsg)== 256 then { oversized message arrived}

David Lang

> @rgerhards steps to reproduce this:
> 1. Set $MaxMessageSize to 255
> 2. Log a message with size greater than 255 ( ex: 512 )
>
>

**Comment by rgerhards** [comment] 2018-06-15 06:51
> set maxmessagesize = 256
> if len($rawmsg)== 256 then { oversized message arrived}

I would still like to point out that this **should not** be necessary, as rsyslog is expected to emit a message by itself in that case. This is why I would prefer to solve the root issue.

**Comment by daniftodi** [comment] 2018-06-17 06:38
> set maxmessagesize = 256
> if len($rawmsg)== 256 then { oversized message arrived}

@davidelang  sorry for stupid question but where do you insert such configuration? ( as I know, the rsyslog.conf has a different formatting).

**Comment by rgerhards** [comment] 2018-07-09 12:58
I am closing this topic as I did not get sufficient information in order to check the root cause. Any new information, feel free to post - I'll reopen when appropriate.

**Closed by rgerhards** 2018-07-09 12:58 UTC
