### ISSUE TITLE
No way to configure a per remote server CAFile

### ISSUE THREAD

**Issue by Popyllol** [rsyslog/rsyslog#5150] opened 2023-05-31 12:21 UTC
### Expected behavior
We need to configure CAFile per destination server as we have more than one TCP syslog destination with different CAs.
So we need something like:
```
action (
  ...
  StreamDriverCAFile=...
  ...
)
```
instead of defining the global DefaultNetstreamDriverCAFile or NetstreamDriverCAExtraFiles (as we have GnuTLS).

### Actual behavior
Nothing to configure this.

### Environment
- rsyslog version: v8.2106.0
- platform: SuSE SLES 15.2
- config lines now:
```
global(
  DefaultNetstreamDriverCAFile="/etc/ssl/certs/MyCA-2020.pem"
)
ruleset(name="remotesyslog") {
  action(
    name="syslogserver"
    type="omfwd"
    protocol="tcp"
    target="syslog.domain.tld"
    port="6514"
    StreamDriver="gtls"
    StreamDriverMode="1"
    StreamDriverAuthMode="x509/name"
    gnutlsPriorityString="%SERVER_PRECEDENCE:%LATEST_RECORD_VERSION:PFS:-VERS-TLS-ALL:+VERS-TLS1.2:-VERS-DTLS-ALL:-KX-ALL:-CIPHER-ALL:-MAC-ALL:-CURVE-ALL:-SIGN-ALL:+ECDHE-RSA:+ECDHE-ECDSA:+DHE-DSS:+DHE-RSA:+AES-256-CBC:+AES-128-CBC:+AES-256-GCM:+AES-128-GCM:+CHACHA20-POLY1305:+SHA256:+SHA384:+AEAD:+CURVE-SECP256R1:+CURVE-SECP384R1:+SIGN-RSA-SHA256"
  )
}
```

**Comment by rgerhards** [comment] 2023-06-06 12:23
closing as this was just an too-old version and so the issue is solved.

**Closed by rgerhards** 2023-06-06 12:23 UTC
