### ISSUE TITLE
segfault caused by fjson while parsing response from omelasticsearch

### ISSUE THREAD

**Issue by ngarratt** [rsyslog/rsyslog#1890] opened 2017-10-23 14:22 UTC
We've started getting segfaults in rsyslog (v8.29.0 from RPM) since we started ingesting logs for a custom FTP server. This server is being scanned by Nessus, which is attempting shell escape with unexpected input on the USER command.

This is being parsed correctly on input, written to local files, and written to elasticsearch. However, it looks like the response from elasticsearch is not being parsed by fjson_tokener_parse correctly and resulting in a null string (segfaulting __strlen_sse2).

I assume this is due to the curly braces in the field (inside quotes, so still valid JSON).

Here is the backtrace
```
(gdb) bt 20
#0  0x00007f7431caac31 in __strlen_sse2 () from /lib64/libc.so.6
#1  0x00007f7432406948 in fjson_tokener_parse_ex (tok=tok@entry=0x7f73e0044a30, str=str@entry=0x0, len=len@entry=-1) at json_tokener.c:252
#2  0x00007f7432408b77 in fjson_tokener_parse_verbose (str=0x0, error=error@entry=0x7f7404ff8bdc) at json_tokener.c:176
#3  0x00007f7432408bce in fjson_tokener_parse (str=<optimized out>) at json_tokener.c:164
#4  0x00007f742dfba892 in checkResult (
    reqmsg=0x7f73e0084570 "{\"index\":{\"_index\": \"astroftp-2017.10.21\",\"_type\":\"astroftp\"}}\n{ \"host\": \"astroftpwts1\", \"app\": \"astroftp\", \"stack\": \"stage2\", \"metadata\": { \"filename\": \"\\/cust\\/astroftp\\/logs\\/ftpdaemon-error.log\" }, \"msg\": \"OPENED\", \"severity\": \"INFO\", \"thread\": \"pool-11-thread-39\", \"date\": \"2017-10-21T12:44:10.660Z\", \"event.tags\": [ \"astro\" ] }\n{\"index\":{\"_index\": \"astroftp-2017.10.21\",\"_type\":\"astroftp\"}}\n{ \"host\": \"astroftpwts1\", \"app\": \"astroftp\", \"stack\": \"stage2\", \"metadata\": { \"filename\": \"\\/cust\\/astroftp\\/logs\\/ftpdaemon-error.log\" }, \"msg\": \"SENT: 220 Service ready for new user.\\r\\n\", \"severity\": \"INFO\", \"thread\": \"pool-11-thread-39\", \"date\": \"2017-10-21T12:44:10.661Z\", \"event.tags\": [ \"astro\" ] }\n{\"index\":{\"_index\": \"astroftp-2017.10.21\",\"_type\":\"astroftp\"}}\n{ \"host\": \"astroftpwts1\", \"app\": \"astroftp\", \"stack\": \"stage2\", \"metadata\": { \"filename\": \"\\/cust\\/astroftp\\/logs\\/ftpdaemon-error.log\" }, \"msg\": \"RECEIVED: USER () { :;}; echo \\\"NESSUS-e07ad3ba-$((17 + 12))-59f8d00f4bdf\\\"\", \"severity\": \"INFO\", \"thread\": \"pool-11-thread-39\", \"date\": \"2017-10-21T12:44:10.662Z\", \"event.tags\": [ \"astro\" ] }\n", pWrkrData=0x7f73e0002dc0) at omelasticsearch.c:1103
#5  curlPost (pWrkrData=pWrkrData@entry=0x7f73e0002dc0,
    message=message@entry=0x7f73e0084570 "{\"index\":{\"_index\": \"astroftp-2017.10.21\",\"_type\":\"astroftp\"}}\n{ \"host\": \"astroftpwts1\", \"app\": \"astroftp\", \"stack\": \"stage2\", \"metadata\": { \"filename\": \"\\/cust\\/astroftp\\/logs\\/ftpdaemon-error.log\" }, \"msg\": \"OPENED\", \"severity\": \"INFO\", \"thread\": \"pool-11-thread-39\", \"date\": \"2017-10-21T12:44:10.660Z\", \"event.tags\": [ \"astro\" ] }\n{\"index\":{\"_index\": \"astroftp-2017.10.21\",\"_type\":\"astroftp\"}}\n{ \"host\": \"astroftpwts1\", \"app\": \"astroftp\", \"stack\": \"stage2\", \"metadata\": { \"filename\": \"\\/cust\\/astroftp\\/logs\\/ftpdaemon-error.log\" }, \"msg\": \"SENT: 220 Service ready for new user.\\r\\n\", \"severity\": \"INFO\", \"thread\": \"pool-11-thread-39\", \"date\": \"2017-10-21T12:44:10.661Z\", \"event.tags\": [ \"astro\" ] }\n{\"index\":{\"_index\": \"astroftp-2017.10.21\",\"_type\":\"astroftp\"}}\n{ \"host\": \"astroftpwts1\", \"app\": \"astroftp\", \"stack\": \"stage2\", \"metadata\": { \"filename\": \"\\/cust\\/astroftp\\/logs\\/ftpdaemon-error.log\" }, \"msg\": \"RECEIVED: USER () { :;}; echo \\\"NESSUS-e07ad3ba-$((17 + 12))-59f8d00f4bdf\\\"\", \"severity\": \"INFO\", \"thread\": \"pool-11-thread-39\", \"date\": \"2017-10-21T12:44:10.662Z\", \"event.tags\": [ \"astro\" ] }\n", msglen=1106, tpls=tpls@entry=0x0, nmsgs=3)
    at omelasticsearch.c:1178
#6  0x00007f742dfbab6a in submitBatch (pWrkrData=0x7f73e0002dc0) at omelasticsearch.c:1194
#7  0x00007f74332d26fe in actionTryCommit (pWti=0x7f743456f780, pThis=0x7f74344f4b30) at ../action.c:1225
#8  actionCommit (pThis=pThis@entry=0x7f74344f4b30, pWti=pWti@entry=0x7f743456f780) at ../action.c:1311
#9  0x00007f74332d3728 in processBatchMain (pVoid=0x7f74344f4b30, pBatch=0x7f743456f7b0, pWti=0x7f743456f780) at ../action.c:1421
#10 0x00007f74332c8e2c in ConsumerReg (pThis=0x7f74344f5310, pWti=0x7f743456f780) at queue.c:2005
#11 0x00007f74332c5935 in wtiWorker (pThis=pThis@entry=0x7f743456f780) at wti.c:365
#12 0x00007f74332c49ed in wtpWorker (arg=0x7f743456f780) at wtp.c:417
#13 0x00007f7432c24e25 in start_thread () from /lib64/libpthread.so.0
#14 0x00007f7431d1c34d in clone () from /lib64/libc.so.6
```

**Comment by rgerhards** [comment] 2017-10-23 16:59
This seems to be a duplicate of https://github.com/rsyslog/rsyslog/issues/1885 but with interesting additional information.

**Comment by rgerhards** [comment] 2017-10-23 17:04
To be parsed string is
```
{"index":{"_index": "astroftp-2017.10.21","_type":"astroftp"}}
{ "host": "astroftpwts1", "app": "astroftp", "stack": "stage2", "metadata": { "filename": "\\/cust\\/astroftp\\/logs\\/ftpdaemon-error.log" }, "msg": "OPENED", "severity": "INFO", "thread": "pool-11-thread-39", "date": "2017-10-21T12:44:10.660Z", "event.tags": [ "astro" ] }
{"index":{"_index": "astroftp-2017.10.21","_type":"astroftp"}}
{ "host": "astroftpwts1", "app": "astroftp", "stack": "stage2", "metadata": { "filename": "\\/cust\\/astroftp\\/logs\\/ftpdaemon-error.log" }, "msg": "SENT: 220 Service ready for new user.\\r\
", "severity": "INFO", "thread": "pool-11-thread-39", "date": "2017-10-21T12:44:10.661Z", "event.tags": [ "astro" ] }
{"index":{"_index": "astroftp-2017.10.21","_type":"astroftp"}}
{ "host": "astroftpwts1", "app": "astroftp", "stack": "stage2", "metadata": { "filename": "\\/cust\\/astroftp\\/logs\\/ftpdaemon-error.log" }, "msg": "RECEIVED: USER () { :;}; echo \\"NESSUS-e07ad3ba-$((17 + 12))-59f8d00f4bdf\\"", "severity": "INFO", "thread": "pool-11-thread-39", "date": "2017-10-21T12:44:10.662Z", "event.tags": [ "astro" ] }
```

**Comment by rgerhards** [comment] 2017-10-23 17:06
Have a look at the patch posted in #1885. I think it will possibly solve your case as well. If not, please post a debug log (also see 1885 for details).

**Comment by ngarratt** [comment] 2017-10-23 21:12
Patched against 8.29 (3d2740d applied cleanly), and I'll test.

FYI, I had to fix three other issues while trying to build the RPMs using the spec from rsyslog-pkg-rhel-centos

Commit 1a6f8d0 introduced some bad edits - erroneous 'Paperclips' added to mmnormalize Requires and erroneous 'liblognor' added to mmfields resulting in broken RPMs. This also affects your hosted RPMs (unsatisfied dependencies on '000' and '30')

Created the rsyslog-systemd-centos7.patch (based on #783), as this isn't in sources

Had to disable libksi (spec refers to a libgt.adiscon.com host for the source, which doesn't appear to exist). Not something I need, so no issues disabling for my builds

**Comment by ngarratt** [comment] 2017-11-06 17:18
We've had no further segfaults since the patch in #1885 was applied. We were typically getting a few of them each week, so I would consider this resolved.

**Comment by rgerhards** [comment] 2017-11-06 17:22
Thanks for letting me know, this is good feedback.

**Comment by rgerhards** [comment] 2017-11-06 17:22
@friedl can you please have a look at https://github.com/rsyslog/rsyslog/issues/1890#issuecomment-338798387 in regard to the packaging.

**Comment by friedl** [comment] 2017-11-10 10:34
@ngarratt Bad edits have been fixed.

**Closed** 2017-11-13 07:38 UTC
Labels: duplicate
