### ISSUE TITLE
Confirmed memory leak

### ISSUE THREAD

**Issue by mostolog** [rsyslog/rsyslog#1376] opened 2017-01-24 09:17 UTC
As discussed in http://lists.adiscon.net/pipermail/rsyslog/2017-January/044127.html seems there's a leak.

Running
> valgrind --tool=memcheck --log-file=/data/valgrind.log --show-possibly-lost=yes --track-origins=yes --trace-children=yes --leak-check=full --show-leak-kinds=all rsyslogd -n

while receiving 100m/s for a few minutes. Attached config, impstats and valgrind traces.

[config.txt](https://github.com/rsyslog/rsyslog/files/726148/config.txt)
[stats.txt](https://github.com/rsyslog/rsyslog/files/726150/stats.txt)
[valgrind.txt](https://github.com/rsyslog/rsyslog/files/726151/valgrind.txt)

**Comment by rgerhards** [comment] 2017-01-24 11:45
The problem is related to the ```$@timestamp``` variable. This is not a proper name (neither a message nor system property and also no local, global or message variable). However, that is not properly detected and in my testing rsyslog even dumps core (under instrumentation). 

I guess  ```$!@timestamp``` was actually meant. @mostolog it would be great if you could change and re-run your test. I'll continue to see what we need to do for proper error detection.

**Comment by mostolog** [comment] 2017-01-24 16:52
Attached config+valgrind+impstats, getting just a few messages. Do you need a higher message rate?

[config.txt](https://github.com/rsyslog/rsyslog/files/727324/config.txt)
[valgrind.txt](https://github.com/rsyslog/rsyslog/files/727311/valgrind.txt)
[impstats.txt](https://github.com/rsyslog/rsyslog/files/727316/impstats.txt)

**Comment by rgerhards** [comment] 2017-01-24 17:03
Thanks, this verifies that the mem leak went away.

**Comment by mostolog** [comment] 2017-01-24 17:04
Should I try again adding more lines to my config? (it was originally using with omelasticsearch)

**Comment by rgerhards** [comment] 2017-01-24 17:06
The original config should work now, as we have identified and eliminated the source of the problem.

**Comment by rgerhards** [comment] 2017-01-24 17:07
Well, the original config **with the fixed variable name** should work, of course. Not the unchanged one ;-)

**Comment by mostolog** [comment] 2017-01-24 17:11
Changed $@timestamp to $!@timestamp (anyway: it's commented by now) and testing again with omelasticsearch+omkafka. Will paste traces for double-checking ;)

**Comment by mostolog** [comment] 2017-01-24 17:48
Full configuration. Awaiting your comments.

[config.txt](https://github.com/rsyslog/rsyslog/files/727472/config.txt)
[impstats.txt](https://github.com/rsyslog/rsyslog/files/727474/impstats.txt)
[valgrind.txt](https://github.com/rsyslog/rsyslog/files/727475/valgrind.txt)

**Comment by rgerhards** [comment] 2017-01-24 18:03
all well

**Comment by mostolog** [comment] 2017-01-24 18:04
Closing is up to you. Thanks! ;)

**Comment by rgerhards** [comment] 2017-01-24 18:09
I'll close once everything is merged, thx.

2017-01-24 19:04 GMT+01:00 mostolog <notifications@github.com>:

**Comment by rgerhards** [comment] 2017-01-25 09:08
Invalid var names are now also checked on startup.

**Closed** 2017-01-25 09:08 UTC
Labels: bug
