### ISSUE TITLE
Update on Debian 10 fails / Timeout restart

### ISSUE THREAD

**Issue by Tango9191** [rsyslog/rsyslog#4602] opened 2021-06-10 12:02 UTC
### Expected behavior
Upgrade to new rsyslog-version works without problems
### Actual behavior
Upgrade fails while it tries to restart rsyslog service
### Steps to reproduce the behavior
Add repo,  
apt update 
apt install rsyslog
### Environment
- rsyslog version:  rsyslog/unknown 8.2104.0-1 amd64 [upgradable from: 8.1901.0-1]
- platform: Debian 10 (Buster)
- for configuration questions/issues, include rsyslog.conf and included config files

Reading package lists... Done
Building dependency tree       
Reading state information... Done
rsyslog is already the newest version (8.2104.0-1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Setting up rsyslog (8.2104.0-1) ...
Job for rsyslog.service failed because a timeout was exceeded.
See "systemctl status rsyslog.service" and "journalctl -xe" for details.
invoke-rc.d: initscript rsyslog, action "restart" failed.
● rsyslog.service - System Logging Service
   Loaded: loaded (/lib/systemd/system/rsyslog.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: timeout) since Thu 2021-06-10 11:14:22 UTC; 7ms ago
     Docs: man:rsyslogd(8)
           http://www.rsyslog.com/doc/
  Process: 19741 ExecStart=/usr/sbin/rsyslogd -n (code=exited, status=0/SUCCESS)
 Main PID: 19741 (code=exited, status=0/SUCCESS)
dpkg: error processing package rsyslog (--configure):
 installed rsyslog package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 rsyslog
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by davidelang** [comment] 2021-06-10 12:06
is rsyslog running after this? if not, what error is generated (and can you run 
it manually as root?)

David Lang

**Comment by Tango9191** [comment] 2021-06-10 12:33
Hi, thanks for your fast answer!
Yes it is running, If I try to stop&start:

> root@presidentialopen:/home/tsec]# systemctl stop rsyslog
> [root@presidentialopen:/home/tsec]# systemctl status rsyslog
> ● rsyslog.service - System Logging Service
>    Loaded: loaded (/lib/systemd/system/rsyslog.service; enabled; vendor preset: enabled)
>    Active: inactive (dead) since Thu 2021-06-10 12:18:02 UTC; 8min ago
>      Docs: man:rsyslogd(8)
>            http://www.rsyslog.com/doc/
>   Process: 20379 ExecStart=/usr/sbin/rsyslogd -n (code=exited, status=0/SUCCESS)
>  Main PID: 20379 (code=exited, status=0/SUCCESS)
> 
> Jun 10 12:17:56 presidentialopen systemd[1]: Starting System Logging Service...
> Jun 10 12:18:02 presidentialopen systemd[1]: rsyslog.service: Succeeded.
> Jun 10 12:18:02 presidentialopen systemd[1]: Stopped System Logging Service.
> [root@presidentialopen:/home/tsec]# systemctl start rsyslog 
> Job for rsyslog.service failed because a timeout was exceeded.
> See "systemctl status rsyslog.service" and "journalctl -xe" for details.



I can kill it and run it as root with /usr/sbin/rsyslog -nd

Kind regards,
Dan

**Comment by davidelang** [comment] 2021-06-10 12:37
my guess is that the systemd config file is starting it without the -n option, 
so it's going into the background and systemd is loosing track of it.

no idea what changed between versions, but I'd start there

David Lang

**Comment by Tango9191** [comment] 2021-06-10 12:52
thanks, bit I don't think so:

[root@presidentialopen:/home/tsec]# ps auxw |grep -i syslog
message+   456  0.0  0.0   9540  4620 ?        Ss   Jun09   0:47 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root     20663  0.0  0.0   6208   884 pts/1    S+   12:49   0:00 grep -i syslog
[root@presidentialopen:/home/tsec]# systemctl start syslog.socket 
[root@presidentialopen:/home/tsec]# ps auxw |grep -i syslog
message+   456  0.0  0.0   9540  4620 ?        Ss   Jun09   0:47 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root     20666  0.0  0.0 293320  2980 ?        Ssl  12:49   0:00 /usr/sbin/rsyslogd -n
root     20672  0.0  0.0   6208   888 pts/1    S+   12:49   0:00 grep -i syslog
[root@presidentialopen:/home/tsec]# systemctl restart rsyslog
Job for rsyslog.service failed because a timeout was exceeded.
See "systemctl status rsyslog.service" and "journalctl -xe" for details.

So it gets started with the -n option

Do you have another idea?

Kind regards,
Dan

**Comment by Tango9191** [comment] 2021-06-11 07:30
echo 'deb http://download.opensuse.org/repositories/home:/rgerhards/Debian_10/ /' | sudo tee /etc/apt/sources.list.d/home:rgerhards.list
curl -fsSL https://download.opensuse.org/repositories/home:rgerhards/Debian_10/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_rgerhards.gpg > /dev/null
apt update
apt list --upgradable
apt install rsyslog

**Comment by jay7x** [comment] 2021-06-12 03:56
Is it duplicate of (or related to) the #4576 ?

**Comment by rgerhards** [comment] 2021-06-12 09:05
This is potentially fixed via https://build.opensuse.org/request/show/899586#revision_details_1 (rsyslog.dsc part). The repo is currently being re-build. The new version should be available later today. I would appreciate if you could give it a try.

**Comment by rgerhards** [comment] 2021-06-12 09:05
> Is it duplicate of (or related to) the #4576 ?

thx, good catch. 99% sure it is the same issue.

**Comment by rgerhards** [comment] 2021-06-14 07:27
I assume this is fixed, so closing issue. Let me know if the problem persists.

**Closed by rgerhards** 2021-06-14 07:27 UTC
Labels: bug, packaging

**Comment by Tango9191** [comment] 2021-06-14 07:54
https://github.com/rsyslog/rsyslog/issues/4576  
fixed it. **THANKS!**

(Without the change "apt install rsyslog" failed imho because there is no new version)
