### ISSUE TITLE
Setting net.aclResolveHostname/net.acladdhostnameonfail segfaults

### ISSUE THREAD

**Issue by nbartos** [rsyslog/rsyslog#272] opened 2015-03-17 16:55 UTC
When compiling using hardned gcc (gentoo), specifying net.aclResolveHostname or net.acladdhostnameonfail results in rsyslogd segfaulting on startup.

I did a quick look at the code, but my C is fairly rusty.  It seems that net.pACLAddHostnameOnFail/net.pACLDontResolve are not being initialized properly before trying to be used in runtime/glbl.c.  Is there a reason net.pACLAddHostnameOnFail and net.pACLDontResolve are integer pointers instead of just being integers?

**Comment by radosroka** [comment] 2017-02-17 09:48
This is still an issue even in fedora machines. (rsyslog 8.24.0)

**Comment by radosroka** [comment] 2017-02-21 09:07
@rgerhards after small research I think this is caused by uninitialized net static structure in glbl objUse(net) is not called after start of glbl module. net.pACLAddHostnameOnFail/net.pACLDontResolve are zeros and they are segfaulting inside of glblDoneCnf() when derefencing *(net.pACLDontResolve).

**Comment by radosroka** [comment] 2017-02-21 09:14
I'm not sure if it even possible to call objUse for net in BEGINAbstractObjClassInit, but it is the first option.

The second option is that instead of dereferencing *(net.pACLDontResolve) we can use global variable which it points to.

Third option can be initialization inside BEGINAbstractObjClassInit line net.pACLDontResolve = ACLDontResolve.

**Comment by rgerhards** [comment] 2017-02-28 14:15
fixed via pr

**Closed by rgerhards** 2017-02-28 14:15 UTC
Labels: bug
