### ISSUE TITLE
how to config rsyslog send log to log server over omfwd module use tcp&TLS

### ISSUE THREAD

**Issue by Cloud-Leung** [rsyslog/rsyslog#1688] opened 2017-07-21 09:59 UTC
i'm sorry to submit this problem .
But I really don't know how tcp&tls should be configured .

environment: 
i have a log server use TCP&tls , and ti's One-way authentication .
this code is my ca file command : 
keytool -genkey -keysize 2048 -validity 365 -keyalg RSA -dname "CN=*.nest.com" -keypass 123456 -storepass 123456 -keystore gornix.jks

and this is my rsyslog config file : 

module(load="imfile" PollingInterval="5" mode="inotify")
input(type="imfile"
      File="/usr/local/data/gelf.log"
      startmsg.regex="[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2} [[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}"
      Tag="tag2" ruleset="writeRemoteData")

template(name="logline_testtcp" type="string"
         string="%$myhostname% %app-name% [1cXi422TloejhaKj type=regex_log4j5 tag=\"syslog\"] /$%timegenerated:::date-rfc3339%$/ %msg%\n"
        )
ruleset(name="writeRemoteData") {
        action(type="omfwd" template="logline_testtcp" Target="192.168.2.162" Port="7878" Protocol="tcp"
		StreamDriver="gtls" StreamDriverMode="1" StreamDriverAuthMode="x509/name" StreamDriverPermittedPeers="CN=*.nestvision.com" )
}

when it start , is looks like right , but my log-server can't receive message, if i remove this config:
StreamDriver="gtls" StreamDriverMode="1" StreamDriverAuthMode="x509/name" StreamDriverPermittedPeers="CN=*.nestvision.com"

and send message to a TCP without TLS ,it  works well .

so i think it must be config doesn't right , how to config this ?
I had checked my server and also tested it, that's right i think .

**Comment by alorbach** [comment] 2018-09-05 11:41
This is not a bug, more a configuration issue - therefor closing.

**Closed by alorbach** 2018-09-05 11:41 UTC
