### ISSUE TITLE
in:imfile general protection (segfaults) sometimes on midnight, maybe because logback rotated logs?

### ISSUE THREAD

**Issue by spiritmonger** [rsyslog/rsyslog#3034] opened 2018-09-19 13:22 UTC
### Expected behavior
no segmentation faults or more information for some fix

### Actual behavior
on system, where running some scala/tomcat application with logback.xml configure, sometimes (not every day) i saw segmentation fault. this example is from one node, where segfault was two day consecutively, on midnight. imfile is used for 6 different files, but with same config template (see below):

```
audit.log
type=ANOM_ABEND msg=audit(1537228800.151:18546): auid=0 uid=0 gid=0 ses=2961 pid=21491 comm="in:imfile" exe="/sbin/rsyslogd" sig=11
dmesg:
[10207641.318698] traps: in:imfile[21491] general protection ip:555e0c113f57 sp:7fc6576262d8 error:0 in rsyslogd[555e0c0d7000+9e000]
```

```
audit.log
type=ANOM_ABEND msg=audit(1537315200.237:18783): auid=0 uid=0 gid=0 ses=2990 pid=17376 comm="in:imfile" exe="/sbin/rsyslogd" sig=11
dmesg:
[10294041.406976] traps: in:imfile[17376] general protection ip:7f0d16ef9694 sp:7f0d14c61660 error:0 in libc-2.17.so[7f0d16eb1000+1b8000]
```

### Steps to reproduce the behavior
i tried on other node (can't debug on prod), but can't find way to reproduce segfaults. propably help me how i can?

### Environment
- rsyslog version:
```
rsyslogd 8.37.0, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			No
	Number of Bits in RainerScript integers: 64
```

- platform: Linux --NODENAME-- 4.1.17-22.30.amzn1.x86_64 #1 SMP Fri Feb 5 23:44:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- for configuration questions/issues, include rsyslog.conf and included config files

```
# LOGBACK configuration
<configuration scan="true" scanPeriod="60 seconds">
  <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <file>/var/log/file.log</file>
    <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
      <fileNamePattern>/var/log/file.log.%d{yyyy-MM-dd}.%i.gz</fileNamePattern>
      <maxFileSize>50MB</maxFileSize>
      <maxHistory>7</maxHistory>
      <totalSizeCap>500MB</totalSizeCap>
    </rollingPolicy>
    <encoder>
      <pattern>file: %date [%X{Type}:%X{id}] [%X{X-IdCall}] [%level] %logger %message%n</pattern>
    </encoder>
  </appender>

  <root level="INFO">
    <appender-ref ref="FILE"/>
  </root>

  <!--  application -->
  <logger name="xxx" level="INFO"/>
  <!--  for logging http requests/responses -->
  <logger name="xxx" level="INFO"/>
</configuration>
```

```
# RSYSLOG configuration file
input(type="imfile"
  File="/var/log/file.log"
  Tag="file:"
  ReadMode="0"
  Facility="local5"
  MaxSubmitAtOnce="1024"
  trimLineOverBytes="129024"
  discardTruncatedMsg="on"
  msgDiscardingError="off"
  reopenOnTruncate="on"
)
```

**Comment by spiritmonger** [comment] 2018-09-19 13:27
```
# rsyslog.conf

$WorkDirectory /var/spool/rsyslog

$MaxMessageSize 128k
$PreserveFQDN off
## Filter duplicated messages
$RepeatedMsgReduction off

module(load="imuxsock") # provides support for local system logging (e.g. via logger command)
module(load="imklog")   # provides kernel logging support (previously done by rklogd)
module(load="imudp")    # needs to be done just once
# module(load"immark")   # provides --MARK-- message capability
module(load="mmjsonparse")

## must be locally
input(type="imudp" Address="127.0.0.1" port="514" name="udpLocal")

## Set the default permissions for all log files.
$FileOwner root
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022

## Enable async write
$OMFileFlushInterval 10
$OMFileASyncWriting on
$OMFileFlushOnTXEnd off
$OMFileIOBufferSize 256k

## Use default template
# $ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

## File syncing capability is disabled by default. This feature is usually not required,
## not useful and an extreme performance hit
# $ActionFileEnableSync on

## Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf
```

**Comment by rgerhards** [comment] 2018-09-24 11:14
I would think that this is a duplicate of https://github.com/rsyslog/rsyslog/issues/3021 - let's flag it as such for now. If the fix for #3021 doesn't help, please let us know.

**Comment by spiritmonger** [comment] 2018-09-27 10:38
on releasenotes i saw: "It still is highly recommended NOT to turn on "reopenOnTruncate" in imfile."
what happened, when watched file is truncated?

**Comment by rgerhards** [comment] 2019-02-28 13:23
as #3021 is closed, I close this one, too.

**Closed by rgerhards** 2019-02-28 13:23 UTC
Labels: duplicate
