### ISSUE TITLE
rsyslogd: imfile: wd 8 already in wdmap!

### ISSUE THREAD

**Issue by lurenx** [rsyslog/rsyslog#2995] opened 2018-09-05 22:01 UTC
### Expected behavior
continue read file

### Actual behavior
stop read file
### Steps to reproduce the behavior

```
input(
    type="imfile"
    File="/var/log/nginx/access*.log"
    Tag="nginx_input"
    Severity="info"
    persiststateinterval="60"
    deleteStateOnFileDelete="on"
    freshStartTail="on"
    reopenOnTruncate="on"
    Facility="local7"
)
```

### Environment
- rsyslog version: 8.37.0
- platform: centos 6&7

**Comment by davidelang** [comment] 2018-09-06 00:52
it stops reading a file under what conditions?

**Comment by lurenx** [comment] 2018-09-06 01:17
@davidelang  after logrotate with nocopytruncate option

**Comment by davidelang** [comment] 2018-09-06 13:13
so you are saying that you:

1. have a file you are writing to and rsyslog is reading from

2. you rotate it with logrotate and the nocopytruncate option (which moves the 
file to a different name)

3. you then have the process writing to the file close it's output and re-open 
the file to continue writing to it. (if you don't do this, the logs continue to 
end up in the old file that now has a different name)

4. the new logs continue toshow up in the file but rsyslog does not read them.

Is this correct?

**Comment by rgerhards** [comment] 2018-09-10 12:32
@lurenx how is your traffic? Quite a bit? Sometimes nothing for a couple of minutes? So that rotation could  leave an empty file for a prolonged period?

I am asking because we are trying to reproduce the root cause for this issue (and other related ones) so far without success.

**Comment by rgerhards** [comment] 2018-09-10 12:36
Is this a pure duplicate of https://github.com/rsyslog/rsyslog/issues/1605? If so, we should close this issue tracker. Let's keep it open if it really is a new case...

**Comment by rgerhards** [comment] 2018-09-20 08:07
no reply, so looks like a duplicate

**Closed by rgerhards** 2018-09-20 08:07 UTC
Labels: bug, imfile
