### ISSUE TITLE
Rsyslog 8.31 doesn't start on CentOS 7

### ISSUE THREAD

**Issue by timtofan** [rsyslog/rsyslog#2167] opened 2017-12-05 16:17 UTC
Rsyslog daemon itself starts and processes incoming messages.
Though systemd doesn't seem to get notified by the service and terminates rsyslogd upon timeout.

Looks like below line from [rsyslogd.c](https://github.com/rsyslog/rsyslog/blob/a5d4e121ea29c427e936aaf33fffc8530bc8c10c/tools/rsyslogd.c#L1942) doesn't run in 8.31 which may be related to a recent change in [acb62dfd](https://github.com/rsyslog/rsyslog/commit/acb62dfdab44cd00e35031984dcaa52e3777900b):
```sd_notify(0, "READY=1");```

Start attempt failure:
```
[16:17 ~]# service rsyslog start
Starting rsyslog (via systemctl):  Job for rsyslog.service failed because a timeout was exceeded. See "systemctl status rsyslog.service" and "journalctl -xe" for details.
                                                           [FAILED]
[16:19 ~]#
```

Journalctl output:
```
Dec 05 16:17:32 systemd[1]: Starting System Logging Service...
Dec 05 16:17:32 rsyslogd[27460]:  [origin software="rsyslogd" swVersion="8.31.0" x-pid="27460" x-info="http://www.rsyslog.com"] start
Dec 05 16:19:02 systemd[1]: rsyslog.service start operation timed out. Terminating.
Dec 05 16:19:02 rsyslogd[27460]:  [origin software="rsyslogd" swVersion="8.31.0" x-pid="27460" x-info="http://www.rsyslog.com"] exiting on signal 15.
Dec 05 16:19:02 systemd[1]: Failed to start System Logging Service.
Dec 05 16:19:02 systemd[1]: Unit rsyslog.service entered failed state.
Dec 05 16:19:02 systemd[1]: rsyslog.service failed.
Dec 05 16:19:03 systemd[1]: rsyslog.service holdoff time over, scheduling restart.
```

Strace of sd_notify using 8.27:
```
[pid 39083] <... ppoll resumed> )       = 1 ([{fd=3, revents=POLLIN}])
[pid 39083] recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"l\4\1\1I\0\0\0\10\0\0\0z\0\0\0\1\1o\0\31\0\0\0", 24}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=1, uid=0, gid=0}}], msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 24
[pid 39083] recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"/org/freedesktop/systemd1\0\0\0\0\0\0\0\2\1s\0 \0\0\0org.freedesktop.systemd1.Manager\0\0\0\0\0\0\0\0\3\1s\0\n\0\0\0JobRemoved\0\0\0\0\0\0\10\1g\0\4uoss\0\0\0\0\0\0\0\2724\0\0#\0\0\0/org/freedesktop/systemd1/job/13498\0\17\0\0\0rsyslog.service\0\4\0\0\0done\0", 193}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=1, uid=0, gid=0}}], msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 193
```

Same strace using 8.31:
```
[pid 32343] <... ppoll resumed> )       = 1 ([{fd=3, revents=POLLIN}])
[pid 32343] recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"l\4\1\1!\2\0\0\10\0\0\0\226\0\0\0\1\1o\0000\0\0\0", 24}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=1, uid=0, gid=0}}], msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 24
[pid 32343] recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"/org/freedesktop/systemd1/unit/rsyslog_2eservice\0\0\0\0\0\0\0\0\2\1s\0\37\0\0\0org.freedesktop.DBus.Properties\0\3\1s\0\21\0\0\0PropertiesChanged\0\0\0\0\0\0\0\10\1g\0\10sa{sv}as\0\0\0 \0\0\0org.freedesktop.systemd1.Service\0\0\0\0\204\1\0\0\0\0\0\0\7\0\0\0MainPID\0\1u\0\0Z~\0\0\0\0\0\0\n\0\0\0ControlPID\0\1u\0\0\0\0\0\0\0\n\0\0\0StatusText\0\1s\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\v\0\0\0StatusErrno\0\1i\0\0\0\0\0\0\6\0\0\0Result\0\1s\0\0\0\7\0\0\0timeout\0\0\0\0\0\26\0\0\0ExecMainStartTimestamp\0\1t\0\0\0\22\24W\232\231_\5\0\37\0\0\0ExecMainStartTimestampMonotonic\0\1t\0\0\245\253\252v\245\1\0\0\25\0\0\0ExecMainExitTimestamp\0\1t\0\0\0\0\0\0\0\0\0\0\0\0\36\0\0\0ExecMainExitTimestampMonotonic\0\1t\0\0\0\0\0\0\0\0\0\0\0\v\0\0\0ExecMainPID\0\1u\0\0Z~\0\0\f\0\0\0ExecMainCode\0\1i\0\0\0\0\0\16\0\0\0ExecMainStatus\0\1i\0\0\0\0\0\0\0i\0\0\0\f\0\0\0ExecStartPre\0\0\0\0\t\0\0\0ExecStart\0\0\0\r\0\0\0ExecStartPost\0\0\0\n\0\0\0ExecReload\0\0\10\0\0\0ExecStop\0\0\0\0\f\0\0\0ExecStopPost\0", 689}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=1, uid=0, gid=0}}], msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 689
```

Systemd packages installed on the box:
```
[~]# rpm -qa | grep systemd
systemd-sysv-219-42.el7_4.4.x86_64
systemd-libs-219-42.el7_4.4.x86_64
systemd-219-42.el7_4.4.x86_64
```

Libraries provided by systemd-libs:
```
[~]# rpm -ql systemd-libs-219-42.el7_4.4.x86_64
/usr/lib64/libnss_myhostname.so.2
/usr/lib64/libnss_mymachines.so.2
/usr/lib64/libsystemd-daemon.so.0
/usr/lib64/libsystemd-daemon.so.0.0.12
/usr/lib64/libsystemd-id128.so.0
/usr/lib64/libsystemd-id128.so.0.0.28
/usr/lib64/libsystemd-journal.so.0
/usr/lib64/libsystemd-journal.so.0.11.5
/usr/lib64/libsystemd-login.so.0
/usr/lib64/libsystemd-login.so.0.9.3
/usr/lib64/libsystemd.so.0
/usr/lib64/libsystemd.so.0.6.0
/usr/lib64/libudev.so.1
/usr/lib64/libudev.so.1.6.2
/usr/lib64/security/pam_systemd.so

**Comment by deoren** [comment] 2017-12-05 16:36
Possible duplicate of #2134. Could also be related to #2150.

**Comment by deoren** [comment] 2017-12-05 16:50
@timtofan My apologies, I believe I misread your report. I think I mixed up your issue with something else that I and others using CentOS 7 packages from the Adiscon yum repo have recently encountered.

- Did you install using the Adiscon yum repo, from source or elsewhere?
- Could you provide a minimum conf file that replicates the issue?

This is what I had typed up with the intention of helping you with the issue I was facing. While it likely doesn't apply to your situation, I'm posting anyway just in case it helps someone else who stumbles across this issue in the future:

> Are you using packages from the Adiscon yum repo? If so, #2134 lists a variety of workarounds for the issue. 
> 
> - Option 1: Run `systemctl --no-reload preset rsyslog` after installing the 8.31.0 packages
> - Option 2: Run `systemctl disable rsylsog; systemctl enable rsyslog` to accomplish what appears to be the same thing (create the missing symlink from `/etc/systemd/system/syslog.service` to `/usr/lib/systemd/system/rsyslog.service`.
> 
> It appears that when the new 8.31.0 packages are installed that the changes in the `rsyslog.service` unit file (between 8.30.0 and 8.31.0) are not picked up by systemd until one or the other occurs and thus the `/run/systemd/journal/syslog` socket is not created. Since the current unit file indicates this is a dependency, rsyslog fails to startup properly.

**Comment by timtofan** [comment] 2017-12-06 09:28
@deoren
Indeed, the package is from adiscon repo.
Here is a minimum config file:
```
$EscapeControlCharactersOnReceive off
$MaxMessageSize 64k
$MaxOpenFiles 8192
$PreserveFQDN on
$WorkDirectory /var/lib/rsyslog
$umask 0000

action(type="omfile" File="/tmp/rsyslog.log" asyncWriting="on")
```

**Comment by deoren** [comment] 2017-12-07 01:23
@timtofan Unfortunately I was not able to replicate the issue using that configuration and the `rsyslog-8.31.0-3.el7.x86_64` package from the Adiscon repo.

rsyslog wouldn't start at all on boot (after upgrading to the `rsyslog-8.31.0-3.el7.x86_64` package) using that or the original configuration until I employed the workarounds noted on #2134 (in this case `systemctl disable rsyslog; systemctl enable rsyslog). Once I did so, the daemon runs without crashing.

`[root@centos7-test redhat]# uname -a`
```
Linux centos7-test 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Can you post your (sanitized) output from these commands?

1. `systemctl status rsyslog`
1. `systemctl status syslog.socket`
1. `grep -Ev '^$|^\s*#' /etc/rsyslog.conf /etc/rsyslog.d/*.conf`

**Comment by timtofan** [comment] 2017-12-07 09:23
@deoren Thanks for looking into the issue.
Tried both `systemctl disable rsyslog; systemctl enable rsyslog` and `systemctl daemon-reload`.
Also tried both with commented out and uncommented systemd unit setting `Alias=syslog.service`.
Though the service is still failing to start.

`uname -a`:
```
Linux hostname 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

`lsb_release -r`:
```
Release:	7.4.1708
```

`systemctl status rsyslog`:
```
● rsyslog.service - System Logging Service
   Loaded: loaded (/etc/systemd/system/rsyslog.service; enabled; vendor preset: enabled)
   Active: activating (start) since Thu 2017-12-07 09:52:43 CET; 1s ago
     Docs: man:rsyslogd(8)
           http://www.rsyslog.com/doc/
 Main PID: 56952 (rsyslogd)
   CGroup: /system.slice/rsyslog.service
           └─56952 /sbin/rsyslogd -n -i /var/run/syslogd.pid

Dec 07 09:52:43 systemd[1]: Starting System Logging Service...
Dec 07 09:52:43 rsyslogd[56952]:  [origin software="rsyslogd" swVersion="8....rt
Hint: Some lines were ellipsized, use -l to show in full.
```

`systemctl status syslog.socket`:
```
● syslog.socket - Syslog Socket
   Loaded: loaded (/usr/lib/systemd/system/syslog.socket; static; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:systemd.special(7)
           http://www.freedesktop.org/wiki/Software/systemd/syslog
   Listen: /run/systemd/journal/syslog (Datagram)
```

`grep -Ev '^$|^\s*#' /etc/rsyslog.conf /etc/rsyslog.d/*.conf`:
```
/etc/rsyslog.conf:$EscapeControlCharactersOnReceive off
/etc/rsyslog.conf:$MaxMessageSize 64k
/etc/rsyslog.conf:$MaxOpenFiles 8192
/etc/rsyslog.conf:$PreserveFQDN on
/etc/rsyslog.conf:$WorkDirectory /var/lib/rsyslog
/etc/rsyslog.conf:$umask 0000
/etc/rsyslog.conf:action(type="omfile" File="/tmp/rsyslog.log" asyncWriting="on")
grep: /etc/rsyslog.d/*.conf: No such file or directory
```

**Comment by rgerhards** [comment] 2017-12-07 09:28
@friedl is currently preparing an updated package. It may be worth waiting until he is done. Maybe you could even help checking that it actually works?

**Comment by rgerhards** [comment] 2017-12-07 09:31
I should add that info that the package build environment lacked proper systemd-devel package, which lead to disabling systemd support. This *should* now be solved. As @timtofan said in the initial posting, the commit he mentioned now conditionally turns off systemd support if the package is not present. For 8.32.0, I have added an option to enforce systemd support and the build will fail when the required package is not available (instead of the 8.31 downgrade of functionality). Again, the upcoming new packages should have this fixed.

**Comment by rgerhards** [comment] 2017-12-07 09:32
And one more thing forgotten: the packages we pushed last week, worked around this by changing the notification mode. I admit I do not understand why this does not work in @timtofan's cases, but I think it's not worth troubleshooting the work-around when we have the final solution close to ready. Hopefully now all said...

**Comment by friedl** [comment] 2017-12-07 11:01
@timtofan can you possibly try out a package from our testing repository?

For this you need to change the repository in /etc/yum.repos.d/rsyslog.repo from
`baseurl=http://rpms.adiscon.com/v8-stable/epel-$releasever/$basearch`
to
`baseurl=http://rpms.adiscon.com/testing/epel-$releasever/$basearch`

Then do a
`yum update`
and use 
`yum install rsyslog-8.31.0`

The RPM that is now installed should identify as
`rsyslog-8.31.0-5`

**Comment by timtofan** [comment] 2017-12-07 12:32
@friedl I tested it and the issue is absent in 8.31.0-5. The service starts without any issue. 👍

**Closed** 2017-12-10 20:50 UTC

**Comment by timtofan** [comment] 2017-12-13 17:33
Is there a plan to move 8.31.0-5 to v8-stable repo?
