### ISSUE TITLE
Random queue-persist.sh test failure

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog#2473] opened 2018-02-11 19:23 UTC
**reported failures in CI runs: http://build.rsyslog.com/testbench-showtest.php?testname=queue-persist.sh**

It has happen again, this time on a amd64 system which was already busy (load: ~4.0) when rsyslog's test suite run:
```
[queue-persist.sh]:
testing memory queue persisting to disk, mode LinkedList
------------------------------------------------------------
Test: ./queue-persist.sh
------------------------------------------------------------
rsyslogd started, start msg not yet seen, pid  111960
rsyslogd startup msg seen, pid  111960
injecting 5000 messages
imdiag[13500]: 5000 messages injected
rsyslog internal message (6,-2041): main Q: regular queue shutdown timed out on primary queue (this is OK, timeout was 1) [v8.32.0 try http://www.rsyslog.com/e/2041 ]
There must exist some files now:
total 2164
-rw------- 1 portage portage 1048581 Feb 11 16:07 mainq.00000001
-rw------- 1 portage portage 1048581 Feb 11 16:07 mainq.00000002
-rw------- 1 portage portage  106429 Feb 11 16:07 mainq.00000003
-rw------- 1 portage portage     557 Feb 11 16:07 mainq.qi
.qi file:
<OPB:1:qqueue:1:
+iQueueSize:2:4:4974:
+tVars.disk.sizeOnDisk:2:7:2203591:
>End
.
<Obj:1:strm:1:
+iCurrFNum:2:1:3:
+pszFName:1:5:mainq:
+iMaxFiles:2:8:10000000:
+bDeleteOnClose:2:1:0:
+sType:2:1:1:
+tOperationsMode:2:1:2:
+tOpenMode:2:3:384:
+iCurrOffs:2:6:106429:
+inode:2:1:0:
+strtOffs:2:1:0:
+bPrevWasNL:2:1:0:
>End
.
<Obj:1:strm:1:
+iCurrFNum:2:1:1:
+pszFName:1:5:mainq:
+iMaxFiles:2:8:10000000:
+bDeleteOnClose:2:1:1:
+sType:2:1:1:
+tOperationsMode:2:1:1:
+tOpenMode:2:3:384:
+iCurrOffs:2:1:0:
+inode:2:1:0:
+strtOffs:2:1:0:
+bPrevWasNL:2:1:0:
>End
.
rsyslogd started, start msg not yet seen, pid  112028
rsyslogd startup msg seen, pid  112028
imdiag[13500]: mainqueue empty
-------------------------------------------------------------------------------
testing memory queue persisting to disk, mode FixedArray
------------------------------------------------------------
Test: ./queue-persist.sh
------------------------------------------------------------
rsyslogd started, start msg not yet seen, pid  112143
rsyslogd startup msg seen, pid  112143
injecting 5000 messages
imdiag[13500]: 5000 messages injected
rsyslog internal message (6,-2041): main Q: regular queue shutdown timed out on primary queue (this is OK, timeout was 1) [v8.32.0 try http://www.rsyslog.com/e/2041 ]
There must exist some files now:
total 2168
-rw------- 1 portage portage 1048581 Feb 11 16:07 mainq.00000001
-rw------- 1 portage portage 1048581 Feb 11 16:07 mainq.00000002
-rw------- 1 portage portage  109087 Feb 11 16:07 mainq.00000003
-rw------- 1 portage portage     557 Feb 11 16:07 mainq.qi
.qi file:
<OPB:1:qqueue:1:
+iQueueSize:2:4:4980:
+tVars.disk.sizeOnDisk:2:7:2206249:
>End
.
<Obj:1:strm:1:
+iCurrFNum:2:1:3:
+pszFName:1:5:mainq:
+iMaxFiles:2:8:10000000:
+bDeleteOnClose:2:1:0:
+sType:2:1:1:
+tOperationsMode:2:1:2:
+tOpenMode:2:3:384:
+iCurrOffs:2:6:109087:
+inode:2:1:0:
+strtOffs:2:1:0:
+bPrevWasNL:2:1:0:
>End
.
<Obj:1:strm:1:
+iCurrFNum:2:1:1:
+pszFName:1:5:mainq:
+iMaxFiles:2:8:10000000:
+bDeleteOnClose:2:1:1:
+sType:2:1:1:
+tOperationsMode:2:1:1:
+tOpenMode:2:3:384:
+iCurrOffs:2:1:0:
+inode:2:1:0:
+strtOffs:2:1:0:
+bPrevWasNL:2:1:0:
>End
.
rsyslogd started, start msg not yet seen, pid  112211
rsyslogd startup msg seen, pid  112211
imdiag[13500]: mainqueue empty
rsyslog internal message (6,-2041): main Q: regular queue shutdown timed out on primary queue (this is OK, timeout was 1) [v8.32.0 try http://www.rsyslog.com/e/2041 ]
ABORT! Timeout waiting on shutdown
Instance is possibly still running and may need
manual cleanup.
ERROR: left-over instance 112211, killing it
UID         PID   PPID  C STIME TTY          TIME CMD
portage  112211 111927  0 16:07 pts/1    00:00:00 ../tools/rsyslogd -C -n -irsyslog.pid -M../runtime/.libs:../.libs -f./
ABORT! hanging instances left at exit
./diag.sh: line 68: 112211 Killed                  LD_PRELOAD=$RSYSLOG_PRELOAD $valgrind ../tools/rsyslogd -C -n -irsyslog$3.pid -M../runtime/.libs:../.libs -f$CONF_FILE
no core file found, cannot provide additional info
ls: cannot access 'core*': No such file or directory
FAIL queue-persist.sh (exit status: 1)
```

**Comment by rgerhards** [comment] 2018-02-11 19:34
I unfortunately can't nail these cases. I think something goes wrong during termination. But I can't reproduce. Tried arm and stress utility without any success ;-(

Will continue to try...

**Comment by rgerhards** [comment] 2018-05-14 07:35
Note to myself: this probably is related too too-low default enq timeout for this use case (like the diskq test)

**Comment by rgerhards** [comment] 2018-11-13 08:43
We have not seen any failures recently. I guess this was indeed related to enq timeout and is now fixed. Please re-open if the problem reoccurs.

**Closed by rgerhards** 2018-11-13 08:43 UTC
Labels: bug, testbench
