### ISSUE TITLE
ompgsql filling postgresql logs with WARNING:  there is already a transaction in progress

### ISSUE THREAD

**Issue by SammyA** [rsyslog/rsyslog#399] opened 2015-06-09 08:09 UTC
Upgrading from 7.6.3-2~bpo70+1 (debian wheezy-backports) to 8.4.2-1
(debian jessie) resulted in the postgresql server logs being filled
with hundreds of "WARNING: there is already a transaction in progress"
messages per second, quickly filling the log disk, and causing the
postgresql server to fail.

The rsyslog config is:

\# Provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")

\# Provides TCP syslog reception
module(load="imtcp")
input(type="imtcp" port="514")

module(load="mmutf8fix")
action(type="mmutf8fix" mode="controlcharacters")

$template pgsqltemplate,"INSERT INTO logs (host, facility, priority, level, tag, \
          program, msg, hostname) VALUES ( '%fromhost-ip%', '%syslogfacility-text%', '%syslogpriority-text%', \
          '%syslogseverity-text%','%syslogtag%', '%programname%', '%msg%' , '%hostname%')",stdsql

$ModLoad ompgsql
\*.* :ompgsql:caradhras.local,syslog,syslog,XXXXXXXX;pgsqltemplate

Reverting back to 7.6.3 solves the problem for now.

**Comment by mbiebl** [comment] 2015-06-11 16:39
Looking through the changes between v7 and v8, I see this

commit ccca729c550466fa1f55fe8d1b2391489251ace8
Author: Rainer Gerhards <rgerhards@adiscon.com>
Date:   Wed Nov 13 12:59:36 2013 +0100

    ompgsql: very minimal support for v8 omod interface
    
    TX DISABLED, single instance, untested - but at least it builds so
    that users can test...


And this comment in the code:
+
+#      warning: transaction support missing for v8
+       bCoreSupportsBatching= 0;
+       DBGPRINTF("ompgsql: transactions are not yet supported on v8\n");

**Comment by alorbach** [comment] 2015-07-07 08:38
Tried to reproduce this problem with 8.11.0 (current master branch), but was not able to. 
No warnings are generated, so the problem might be already solved. Is it possible for you to try the rsyslog version 8.11.0 from our debian repository? 

More about our Debian repository here: 
http://www.rsyslog.com/debian-repository/

**Comment by mbiebl** [comment] 2015-07-07 13:43
@alorbach well, even 8.11.0 still has this comment in the code that transactions are not supported and I can't see any relevant changes being done between 8.4 and 8.11 when looking at the git history.

I suspect this might be a postgresql configuration issue. @SammyA can you share your postgresql configuration?

**Comment by rgerhards** [comment] 2015-07-07 15:12
@mbiebl well, it does not support transactions, that's right. But it should do single inserts, without either starting or stopping a transaction, e.g. make no transaction calls at all. I assume this would not trigger the message reported here?

@alorbach could you double-check that no transaction calls are done?

**Comment by alorbach** [comment] 2015-07-07 16:23
@SammyA would be greate to get your pgsql configuration. 
@mbiebl I haven't looked into the code yet to be honest, I was focusing on getting a configuration to work in order to reproduce the problem.

**Comment by rgerhards** [comment] 2015-07-08 08:31
I made a change based on pure code review. As @alorbach can not reproduce, we really don't know if it works, but I think it will. It would be great if @SammyA could try it out and report back. The bug will be closed when the patch is finally merged, please re-open if the problem is not solved.

**Closed** 2015-07-09 08:18 UTC
Labels: waitingOnResponse

**Comment by SammyA** [comment] 2015-07-13 07:56
Was out of the office last week, so apologies for not getting back sooner. I applied the 73c9a28 patch on top of 8.4.2-1 (from debian jessie). It all seems to be working (no errors in postgresql log, and syslog messages are being inserted into the db).

Thanks.

**Comment by rgerhards** [comment] 2015-07-13 12:18
Thanks for the feedback, this helps a lot!
